### ISSUE TITLE
How to set up a no go Area or a fence

### ISSUE THREAD

**Issue by Wessix** [rand256/valetudo#1]
First of all sorry for opening an issue for that. Maybe I'm just stupid and blind..... but how do i set up a fence/virtual wall or a no go area as shown in your Picures "Editing Markers" i can't find where to place those, i can set up a zone and rename it, but no no go areas or virtual walls.
Maybe you can provide a detailed information. 
Thank you in advance!

Lab mode is enabled. Do i have to reset the Map for them to work? 
I had resetted the map after installing the normal valetudo

**Comment by rand256** [comment]
You should open "Zones" tab and use "Configure forbidden zones" link.

Resetting the map is not required (if you haven't ruined it by not cleaning sensors regularly etc).
I've never reset the map on my vacuum.

**Comment by Wessix** [comment]
Mm there is no configure forbidden zones link when i go to the zones tab.

Under zones i can only see "configured zones" and configured "goto locations"




I have built the valetudo bin with the docker method and changed the link in the dockerfile to this repo, is this probably an issue?

I can see the zones i created on the map now in comparison to the valetudo master repo so i thought everything worked well.


https://imagebin.ca/v/4msclffVQxZE

**Comment by rand256** [comment]
Maybe. I never used docker so probably it builds something else. Will have to look at it.

**Comment by rand256** [comment]
Anyway, when building you seem somehow to be using /client directory or a part of it from the origin valetudo, not the modded one. In the modded zones.html there's [forbidden zones](https://github.com/rand256/valetudo/blob/testing/client/zones.html#L18) section shown unconditionally. If you can't see it, then in your sources something is messed up.

**Comment by Wessix** [comment]
ok thank you for your investigation. I'll donwload the base files manually and try to rebuild and report back.
mmh just did a git clone of your repo and run it with docker as described here : 
https://github.com/Hypfer/Valetudo/issues/266




seems not to work, i get following errors
~/Documents/valetudorand/valetudo$ sudo docker run --rm -it -v $(pwd):/host valetudo-compiler bash -c "cp /Valetudo/valetudo /host && chown $(id -u):$(id -g) /host/valetudo"

> valetudo@0.3.1-RE3 build /
> pkg --targets node10-linux-armv7 --no-bytecode --options max-old-space-size=32 --public-packages=prettycron . "bash" "cp /Valetudo/valetudo /host && chown 1000:1000 /host/valetudo"

> pkg@4.3.8
> Error! Not more than one entry file/directory is expected
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! valetudo@0.3.1-RE3 build: `pkg --targets node10-linux-armv7 --no-bytecode --options max-old-space-size=32 --public-packages=prettycron . "bash" "cp /Valetudo/valetudo /host && chown 1000:1000 /host/valetudo"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the valetudo@0.3.1-RE3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-06T11_09_08_173Z-debug.log


so i have to build it from scratch, having no native linux just a vm.... i have to do it with a live system 

omg     :-)

**Comment by Wessix** [comment]
Did a complete new build with this repo but something went wrong. I cant acces the http interface. I can connect to the device with roborock control center an read out the tokens, also with the mirobo tool, but no http, also no manual ssh connection.

**Comment by rand256** [comment]
I believe valetudo itself just can't break ssh keys auth unless you manually tried to edit them via web GUI (or /api/set_ssh_keys if that matters). And to understand why http is unavailable ssh access is required obviously...

AFAIU most of my code changes just can't lead to such issues though, so if they happen here they should also happen with origin Valetudo master branch too. I've just re-checked, I've built valetudo binaries exactly with the same code as in this repo, just by running "npm install && npm run build" on linux console, nothing else. Still can't say anything about docker, the configuration of my old linux server is lacking its support.

**Comment by Wessix** [comment]
Ok got it working. The error was i used wget for the config files and probably pointed it not to the raw files on github. Great Version. I enjoy setting up the zones and now everything is so plug and play that my wife can use it. Thx for your work..


You can close the issue if you like.

**Comment by rand256** [comment]
Glad you've figured it out.

However there's still a global unresolved issue with random firmware resets, which is generic for all valetudo 0.3+. It was already reported to happen with RE modded versions too, which is not surprising since the cause for it is yet to be found.

**Comment by Wessix** [comment]
Just wanted to let you know that there seems to be a workaround for the random resets described in the hypfer github issues

**Comment by Wessix** [comment]
I've followed your comments in the hypfer valetudo git. I'm using your fork.and had no reset so far. Just for your information. Don't know how to contact another way.
