### ISSUE TITLE
0.9.0 Telegram Bot issues

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#105]
Hello @rand256,
first of all: great work on the new telegram bot inline keyboard feature, I appreciate your work and I like this new kind of control :+1: Since I only have an Gen1 device, I cannot give you any feedback about the room cleaning feature. Just a question about the new symbol on map:

![map](https://user-images.githubusercontent.com/59822549/74072916-cb58a700-4a08-11ea-9af8-6bf3397e4cbb.jpg)

Is this marker for identifying the room? What's the number about? It cannot be dragged or renamed. 

Thus some issues concerning the telegram bot now:

- **Goto**-Button
The configured goto locations are displayed, but when trying to send the robot to a point by choosing one of them, there's an error message "You need to select a spot for Goto." and the robot isn't moving. The same command issued via the web gui is working.

![goto](https://user-images.githubusercontent.com/59822549/74071567-921e3800-4a04-11ea-8ea0-23aec516a113.jpg)

- **Status**-Button
The current value for the power state of the robot is not displayed. There's "undefined" all the time.

![status](https://user-images.githubusercontent.com/59822549/74071688-e2959580-4a04-11ea-8b19-6d6087b50bc2.jpg)

- **Power Mode**-Button
There's a difference of the displayed power modes compared to the web gui. 
With PR #87 the web gui doesn't show the Mop option on Gen1 anymore (thx @MadJoker0815). In telegram bot the mode "Whisper" is missing, and "Mop" is additionally shown.

![powermode_telegram](https://user-images.githubusercontent.com/59822549/74072334-c09d1280-4a06-11ea-91e4-fdf587244c48.jpg)

![powermode_webgui](https://user-images.githubusercontent.com/59822549/74072337-c266d600-4a06-11ea-86de-5c78bc2eba27.jpg)

- **Zones**-Button
After selecting a zone, the text above the inline keyboard states:
Currently selected: "Zone name" (1}/5 subzones). I think the "}" after the amount of selected subzones is unnecessary?!

- **Spot**-Button
After pushing the Spot-Button, nothing happens, no error message, no reaction of the robot!

**Vacuum Model:** Gen1 v11_003468
**Valetudo RE Version:** 0.9.0-beta

**edit:** just figured out, that the spot cleaning button isn't working at all. Added to the list.

**Comment by rand256** [comment]
Thanks for detailed description. Most of issues listed are already fixed by now.

> Is this marker for identifying the room? What's the number about? It cannot be dragged or renamed.

Err.. Yes, this is segment pin and 31 is its ID, but that's weird cause as far as I remember an old mapdata had all segment-related bits unset (I used a bit fw 1898 while having already updated map parser). Probably Gen1 is different and has those bytes filled with 0xff. I think for now I'd try to simply disable segments code when there's only one type of segment pixels present on the map.

**Comment by pidator** [comment]
All commands via telegram are now working with my Gen1 and the final version of 0.9.0. Also the segement marker isn't shown anymore.
