### ISSUE TITLE
How to update Valetudo RE from 0.8.2 to 0.9.0-beta2 on Gen1? 

### ISSUE THREAD

**Issue by waclaw66** [rand256/valetudo#112]
Hello,

I'm currently running Valeture RE 0.8.2 (fw 3468) on Gen1 vacuum. I've tried to update it to 0.9.0-beta2 using Info / Firmware update, but got error 400.
POST data were:
`{"url":"https://github.com/rand256/valetudo/releases/download/0.9.0-beta2/vacuum_valetudo_re_4004.pkg","md5":"https://github.com/rand256/valetudo/releases/download/0.9.0-beta2/vacuum_valetudo_re_4004.pkg.md5"}`

response text:
`Invalid parameters`

Originally I flashed Valetudo 0.4.0 image from Dustbuilder using mirobo tool. Later on I replaced Valetudo with Valetudo RE (just the binary).

Can I use mirobo tool for flashing new vacuum_valetudo_re_4004.pkg package? I'm not sure what could happen and I don't want to brick my vacuum. Will be my settings kept? Or shall I wait until Info / Firmware update will be fixed?

Thanks.

**Comment by rand256** [comment]
The thing is md5 should be md5 string, not md5 URL.

And the only issue with mirobo is that you can't use it to reflash already installed 4004, when it doesn't have miio client downgraded. Also it can't reflash already installed 2008 even with downgraded miio. Well, in fact it can, but pkg file should be specified explicitly and its URL should direct to external address, not to local one. And it always can be used to upgrade TO 4004 or 2008.

**Comment by waclaw66** [comment]
Thanks for explanation.
I tried to update Gen1 to vacuum_valetudo_re_4004.pkg (Github URL) via Info / Firmware update again.
This time with correct md5 value, it showed OK message, LED on vaccum started blinking for cca 30s.
Then stopped without any message or sound and it still shows fw 3468 and Valetudo RE 0.8.2.
What could be wrong?

**Comment by rand256** [comment]
Technically - whatever, really. Sorry, there's no status data for now. In most cases it means wrong md5 or badly downloaded file, which is not surprising considering quality of wifi modules of these vacuums.
