### ISSUE TITLE
Gen1: Resume function of paused-sendto-dock not working

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#114]
Hi,
I figured out an "unexpected" behaviour after using the "resume" button in telegram bot. I paused the robot on his way to the dock and after clicking resume, it started a full clean. Because of Gen1, I therby lost my map.

**How to Reproduce**

1. Send Robot to dock
2. Click in Telegram on 'Pause'
3. Click in Telegram on 'Resume'
4. Robot starts an full cleaning

**Vacuum Model:** Gen1 v11_003468
**Valetudo Version:** 0.9.0-beta2

**Comment by rand256** [comment]
I can't reproduce that on my Gen2. Could you copy the results from URL http://your-robot-ip/api/current_status when the device is on pause when going to dock?

**Comment by pidator** [comment]
Here's the output of current_status after the following steps:

1. Send Robot to dock
2. Click in Telegram on 'Pause'

`{"msg_ver":8,"state":10,"battery":100,"clean_time":3,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":0,"human_state":"Paused","human_error":"No error","model":"rockrobo.vacuum.v1"}`

3. Click in Telegram on 'Resume'

`{"msg_ver":8,"state":5,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":1,"fan_power":60,"dnd_enabled":0,"human_state":"Cleaning","human_error":"No error","model":"rockrobo.vacuum.v1"}`

Also after step 3 the robot didn't "say" _Resume drive_, instead it "says" _Start new cleaning_ (don't know the actual english words, because of installing the german sound file). So for me it seems the resume-command on gen1 will trigger a full cleaning!?

**Comment by rand256** [comment]
So Gen1 simply doesn't have "in_returning" field in status? Nice...

Well, to workaround this I don't think it would be correct to assume that if the vacuum is in paused state while not in cleaning then it was going to the dock before, but I don't have any better ideas for now. Btw without "in_returning" state return home phase couldn't be properly resumed in web interface too, not only in telegrambot ... it just didn't start a new cleaning cause was written a bit differently.

**Comment by pidator** [comment]
Just tested a normale zoned cleaning and push the pause-button via the Web Gui:
The Web Gui doesn't even offer me an _Resume_-Button:

![webgui](https://user-images.githubusercontent.com/59822549/74174404-2f12e800-4c34-11ea-9b2b-8003737ee781.jpg)

Will check the code later for an appropriate solution. 

Do you have an _Resume_-Button with Gen2 on the Web Gui? 
If so, there has to be an Gen1/Gen2-check while opening the home.html...

**Comment by rand256** [comment]
Nope, I was talking about map tab, there's a standalone resume button appearing after pressing pause button. Home tab was always missing it.

**Comment by pidator** [comment]
No resume button on map tab after pausing the robot:

![webgui2](https://user-images.githubusercontent.com/59822549/74175735-ad708980-4c36-11ea-8d64-766c13763237.jpg)

- Plus = will create a zone
- Play = will try zoned cleaning, but no zone specified so it proposes to do a full clean
- Down-Arrow = Spotcleaning
- Location = no function

**Comment by rand256** [comment]
Maybe you have dynamic map buttons option disabled.

**Comment by pidator** [comment]
nope, the _Disable dynamic buttons_ option is set to off.

**Comment by pidator** [comment]
just tested it again: the setting _Disable dynamic buttons_ off was the right one, when turning this option **on** there is **no** pause-button on map while the robot is moving!

I know now what's the _Location_-button is about: you can set manually an red dot/pointer on the map and with this button, you  can send the robot there. But unfortunately: no _Resume_-button is available when the robot is paused.

**Comment by rand256** [comment]
Due to [the code](https://github.com/rand256/valetudo/blob/testing/client/map.html#L182) it should appear below start button (though start button should be hidden at that time). Can't imagine the reason for it not being available in state=10 (paused).

As for goto (location) button being silently discarded when no point is set - it's a good find, I'll add a notification for that case. That part of code came unchanged from the stone age, when there were no motivation to put notifications on every step...

**Comment by pidator** [comment]
> Due to [the code](https://github.com/rand256/valetudo/blob/testing/client/map.html#L182) it should appear below start button (though start button should be hidden at that time). Can't imagine the reason for it not being available in state=10 (paused).

sorry for the confusion, it was my mistake: I've done just a **goto** instead of **zone cleaning** or **send to dock** while watching the map. Indead there **is** a resume button on the map when running zone cleaning or send to dock and then press pause. While zone cleaning is paused, the resume function **do work!!**

here's the steps and the api_status output for zoned cleaning:
1.  start zone cleaning

`{"msg_ver":8,"state":17,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":2,"fan_power":60,"dnd_enabled":0,"human_state":"Zoned cleaning","human_error":"No error","model":"rockrobo.vacuum.v1"}`

2. pause zone cleaning

`{"msg_ver":8,"state":10,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":2,"fan_power":60,"dnd_enabled":0,"human_state":"Paused","human_error":"No error","model":"rockrobo.vacuum.v1"}`

3. resume zone cleaning

`{"msg_ver":8,"state":17,"battery":100,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":2,"fan_power":60,"dnd_enabled":0,"human_state":"Zoned cleaning","human_error":"No error","model":"rockrobo.vacuum.v1"}`

4. additional step: stop zone cleaning

`{"msg_ver":8,"state":3,"battery":100,"clean_time":18,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":0,"human_state":"Idle","human_error":"No error","model":"rockrobo.vacuum.v1"}`

Everything's fine for this case!

Now I've done a **goto dock** from a random point in room, and this time the resume button did appear in map also:
1. send robot to dock

`{"msg_ver":8,"state":6,"battery":100,"clean_time":18,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":0,"human_state":"Returning to dock","human_error":"No error","model":"rockrobo.vacuum.v1"}`

2. pause sending to dock

`{"msg_ver":8,"state":10,"battery":100,"clean_time":18,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":0,"human_state":"Paused","human_error":"No error","model":"rockrobo.vacuum.v1"}`

3. **and now** resume sending to dock. this time, **the map data is lost and the robot starts a full cleaning**. here's the status-output in this case:

`{"msg_ver":8,"state":5,"battery":99,"clean_time":0,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":1,"fan_power":60,"dnd_enabled":0,"human_state":"Cleaning","human_error":"No error","model":"rockrobo.vacuum.v1"}` 

(so it's as you anticipated: the same result using the webgui like in https://github.com/rand256/valetudo/issues/114#issuecomment-584227366)

With [the query](https://github.com/rand256/valetudo/blob/testing/client/map.html#L264) and the not available "in_returning" field for Gen1, it is understandable that you can't reproduce the issue with your Gen2. If I compare the output of  api_status from "pause_zonedcleaning" and "pause_sendtodock" the only difference I see is the "in_cleaning" field. While in zoned cleaning the value is 2, when send to dock the value is 0. Can this perhaps be used to modify the query of resuming after paused sending to dock?

Annotation: Unlike the other states if you just do a goto and **then** press pause, no resume button is displayed (see map screenshot https://github.com/rand256/valetudo/issues/114#issuecomment-584250103) and no resume command is shown in telegram neither. Sorry for this confusion.

**Comment by rand256** [comment]
> While in zoned cleaning the value is 2, when send to dock the value is 0. Can this perhaps be used to modify the query of resuming after paused sending to dock?

Let's try to check this.

> Unlike the other states if you just do a goto and then press pause, no resume button is displayed

AFAIK that's because the device itself doesn't know how to pause it, so it just does a complete stop even on receiving pause command.

**Comment by pidator** [comment]
I've tested the pause/resume function both with zoned cleaning and send-to-dock via the web-gui and via telegram commands and now everythings working perfect! Thank you for fixing this issue.
