### ISSUE TITLE
DPKG is missing in 2008 0.9.0 beta.

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#115]
I wanted to Update from 2008 RE 0.9.0 beta to 0.9.0 beta2 with the deb package, but DPKG is missing now? How to install it? BTW: reboot command seems also missing. :-(

**Comment by rand256** [comment]
On 2008 fw valetudo can be upgraded like this:

```
/etc/init/S11valetudo stop
cd /mnt/data/valetudo
wget -O - https://github.com/rand256/valetudo/releases/download/0.9.0-beta2/valetudo.tar.gz | tar zxf -
mv valetudo /usr/local/bin
/etc/init/S11valetudo start
```

You may ask about dpkg at [vacuumz image builder](https://github.com/zvldz/vacuum), but I think if it wasn't already added then it probably can't be easily done.

**Comment by v-a-d-e-r** [comment]
Under Linux it works, on the bot I get this:
tar -xzf valetudo.tar.gz
tar: valetudo: Wrote only 8704 of 10240 bytes
tar: Exiting with failure status due to previous errors

So I moved the file from Linux onto the bot's '/usr/local/bin' and all is good... ;-)
Thanks.

**Comment by rand256** [comment]
That error in most cases means that there's no disk space left.

**Comment by v-a-d-e-r** [comment]
Hmm, fresh after a factory reset already no space?

**Comment by rand256** [comment]
Sure. You can check that by `df -h`.

**Comment by v-a-d-e-r** [comment]
Did this already. Result:
.....
7.0K    ./etc/profile.d
616.0K  ./etc
505.2M  .
root@rockrobo:/#

**Comment by rand256** [comment]
Idk, I see this:

```
Filesystem                Size      Used Available Use% Mounted on
rootfs                  169.5M    153.8M      6.9M  96% /
/dev/root               169.5M    153.8M      6.9M  96% /
```

So there's no chance to unpack 2 valetudo binaries on rootfs at the same time. Thus I suggested to chdir first to /mnt/data and then do wget & tar.

**Comment by v-a-d-e-r** [comment]
Ok, I see what my mistake was: I did it in the /home folder! Bad idea... So I made a '/temp' folder in /mnt/data and then it works. :-) Many thanks!
