### ISSUE TITLE
Valetudo application, iptables and /etc/hosts added config disappear without apparent reason

### ISSUE THREAD

**Issue by teixeluis** [rand256/valetudo#117]
**Describe the bug**

After using this Valetudo fork (v0.8.2) on top of rooted fw 3.5.0_003532 in gen1 vacuum for more than a month, I suddenly could no longer have access to its web UI.

Connected via ssh and found that valetudo binaries disappeared and configuration under /etc as well. Also found that /etc/hosts file was back to the original state (without any xiaomi cloud host names) and iptables was missing all the added configuration too.

The custom audio files that I placed in the robot were preserved though.

After this, installed valetudo 0.9.0-beta2 from the deb package, and everything seemed back to normal. 

After a day or so, found that the vacuum was deprovisioned and in AP mode (SSID roborockXXX). My wife started a cleanup and voices were in chinese.

Do you have a clue as to to how/why this behaviour can occur? I read in the past that a misbehaved application could cause the robot to trigger a factory reset (some kind of watchdog in place?).

Could this particular firmware version + valetudo version + the fact that I have installed valetudo on top of a baseline rooted image have anything to do with this behavior?

Thank you

Cheers.

**Comment by rand256** [comment]
See #76.

This issue happens to almost _all_ valetudo enabled devices. It is advised to use firmware image created by _[vacuumz image builder](https://github.com/zvldz/vacuum)_ with default settings or at least to disable logging that writes enormous amount of data for sending to xiaomi cloud (even though there is no more cloud connection with valetudo, by default this data is continually collected). This way my Gen2 had its last reset around 7 month ago.

**Comment by teixeluis** [comment]
> See #76.
> 
> This issue happens to almost _all_ valetudo enabled devices. It is advised to use firmware image created by _[vacuumz image builder](https://github.com/zvldz/vacuum)_ with default settings or at least to disable logging that writes enormous amount of data for sending to xiaomi cloud (even though there is no more cloud connection with valetudo, by default this data is continually collected). This way my Gen2 had its last reset around 7 month ago.

Thanks for the feedback @rand256. I was planning to disable the logging. I wasn't fast enough though. The reset will happen anyway, albeit after a longer time?

Thank you

**Comment by rand256** [comment]
When I started using valetudo (origin at that time, RE was yet to come) it reset my vacuum almost every 2-4 weeks. And now it's running more than half a year and counting. Some says vacuumz images do never reset, although nobody could tell exactly why.
