### ISSUE TITLE
Improvement: cancel button for renaming prompts (zones, spots, rooms)

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#119]
The popup shown when renaming a zone, spot or room is still 'on top' when using the android back button (while in the background the page is changing). I do have this situation, if I accidentally opened the rename popup, but don't want to change the name. Can this action (backbutton) be triggerd or can you add perhaps an 'Cancel' button for a clear cancellation of the action?

**Vacuum Model:** Gen1 v11_003468
**Valetudo Version:** 0.9.0-beta2

**Comment by rand256** [comment]
Well, those prompts are the builtin functionality of onsen framework and it doesn't have an option to add other buttons like 'cancel' there. Phone's backbutton itself doesn't have its own event that could be captured, it just replicates behavior of 'back' button on any desktop browser which also neither have its event nor can be cancelled.

So if you happen to erroneously open rename dialog, it always can be closed by tapping outside of it, or as it is pre-filled by default with current name it can be safely pressed OK to rename as nothing will change. Esc button on the PC keyboard will also close the dialog, but I see no way how to rebind it to something available on phone's keyboard.

**Comment by pidator** [comment]
Ah, I do get it, just read the onsen documentation of ons.notification.prompt and figured out, that there's no second parameter for a button, like you described. I already figured out to close the dialog with tapping outside and I can image why you set the prefilled content of the prompt to the current name :-) 
It's just "used" to have a cancel button besides an ok-button to abort an input. 

Just played a little with the onsen online emulator and got this working, a "self-created" template for an alert-dialog with an prompt, ok and cancel button:

```
<ons-page>
  <ons-button onclick="createRenameDialog()">Rename</ons-button>
</ons-page>

<template id="rename-dialog.html">
  <ons-alert-dialog id="my-alert-dialog" modifier="rowfooter">
    <div class="alert-dialog-title">Prompt</div>
    <div class="alert-dialog-content">
      Enter new name for zone:
      <ons-input modifier="underbar"></ons-input>
    </div>
    <div class="alert-dialog-footer">
      <ons-alert-dialog-button onclick="hideAlertDialog()">Cancel</ons-alert-dialog-button>
      <ons-alert-dialog-button onclick="hideAlertDialog()">OK</ons-alert-dialog-button>
    </div>
  </ons-alert-dialog>
</template>

var createRenameDialog = function() {
  var dialog = document.getElementById('my-alert-dialog');

  if (dialog) {
    dialog.show();
  } else {
    ons.createElement('rename-dialog.html', { append: true })
      .then(function(dialog) {
        dialog.show();
      });
  }
};

var hideAlertDialog = function() {
  document
    .getElementById('my-alert-dialog')
    .hide();
};
```
![onsen](https://user-images.githubusercontent.com/59822549/74353739-a2466680-4dba-11ea-8084-62f1d783b340.jpg)

What do you think, could this be a solution or will it distrub other features/is it to much work for the result of "just an cancel button"?

**Comment by rand256** [comment]
Yes, it's definitely possible to write our own dialog windows for every case, but it will require a huge amount of code.

**Comment by pidator** [comment]
no big advantages with my improvement idea and no issue, therefore I'll close this. :)
