### ISSUE TITLE
Zone Timers

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#12]
Hey rand, got the latest version from your fork installed.

I know its still in beta, but want to notice that the 4th and later timer for a zone cleaning will always beeing disabled after reloading the page.

And: I can't delete them.

**Comment by rand256** [comment]
Should be fixed in 8b0172c5f3244f4f03e06aeffa3d15d5535bc4c8.

**Comment by nicedevil007** [comment]
Ok thank you :)
Guess it will run. Did a fresh compile. What I always notice is, that the precompiled version from your official releases are around 4MiB bigger than the compiled ones I do by myself. Is that normal?

**Comment by rand256** [comment]
That's because it is based on custom built node.js which is not requiring to install newer libstdc++ to the vacuum.

**Comment by nicedevil007** [comment]
Ah ok, so I'm doing everything right :D
Ticket could will be closed, everything seems to work.
