### ISSUE TITLE
[Feature request] Hide blue FW 2008 map marker

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#120]
Is it possible to hide the new "blue room markers" in the map that came with FW 2008? I use valetudo for the room selection, so I do not need them. And one "Goto" location is exact under such a marker!

**Comment by rand256** [comment]
Elaborate, please. There's no such thing like "map that came with FW 2008" - it didn't "came", it was written this way by me. Also it's weird to say "you use valetudo to select rooms": without those markers created in valetudo it's simply impossible to select rooms. To be more exact, it's possible to code rooms to be selectable without special markers just by clicking anywhere on the room pixels, but then it'd make impossible to put Goto points onto the map where the rooms are.

And if you mean classic zones under "room" term, well, you simply may stay on 1898 firmware - there will be no room markers as well as rooms at all.

**Comment by v-a-d-e-r** [comment]
Reverted to 1910... Thanks
