### ISSUE TITLE
install - issues with WIN-MIROBO

### ISSUE THREAD

**Issue by dnl0319** [rand256/valetudo#122]
Hello,

I've tried to install a pre rooted version as described in the guide but I had problems with WIN-MIROBO.
I get the toke from my android phone with the modified Mi Home App. I downloaded the Version root_1898.pkg and placed it into the firmware folder. But the I received the following error:

"WIN-MIROBO INITIALIZATION ERROR
Can not connect to device: Device handshake error on socket receive..."

Does anyone has an idea what I can do?

**Comment by rand256** [comment]
I'd say it could be firewall blocking connections or wrong IP address of a robot specified in configuration.

**Comment by dnl0319** [comment]
Okay, I reset the Wifi of the robot. Then I connected directly to the robot via Wifi with a Win Notebook and disable all firwalls. But now I receive the following error.

"WIN-MIROBO INITIALIZATION ERROR
Can not connect to device: Method 'miIO.info' error on socket receive...
Press any key for exit..."

Does someone have an idea what I did wrong?

**Comment by lemuba** [comment]
@dnl0319  I had the same problem on my Gen.1 a couple of days ago, running the original and current Xiaomi firmware (not Valetudo).
It seems that the current Xiaomi firmware blocks flashing, even if you have the token.
So I resetted the robi to the factory firmware and picked up my token. After that I was able to flash Valetudo via rrcc and possible also via WIN-MIROBO.

**Comment by ministryofsillywalks** [comment]
Sorry to go gravedigging but I have the same problem.
After my valetudo rrand robot seemed to once again reset itself I'm back on a chinese speaking robot.
Tried connecting to it with win-mirobo to reflash but I get the error
"WIN-MIROBO INITIALIZATION ERROR
Can not connect to device: Method 'miIO.info' error on socket receive...
Press any key for exit..."
Tried completely resetting my robo but the issue persists.
The MiHome App says the robo is on firmware 3.3.9_003088 (and this is after a complete reset.)
Any ideas what I can try to connect to the robo?

**Comment by rand256** [comment]
Try flashing via XVacuum app on the smartphone.

**Comment by ministryofsillywalks** [comment]
> XVacuum

"Requested page not found" on XDA when trying to download the apk. 
Is the app hosted somewhere else?
nvm found a link

**Comment by ministryofsillywalks** [comment]
no dice.
using the app and connecting directly to the vacuumAP i with the correct token I get:
The server started
Handshaking...
Handshake is successful
The token is got
Trying to get the status (this 50 times)
timeout: Call to the vacuum timed out

Any ideas?

Added the robo to my wifi and its the same. Gets stuck on "Trying to get the status"

**Comment by ministryofsillywalks** [comment]
I'm dumb.
Typo in the token.
Works now
