### ISSUE TITLE
currentCleanTime in minutes in MQTT status?

### ISSUE THREAD

**Issue by rmrustem** [rand256/valetudo#123]
While it's pretty reasonable to convert almost all time periods (consumables, etc) to hours, it seems a little bit more rational to show the **[current clean time](https://github.com/rand256/valetudo/blob/a82dd3991cb3ee502e2a7a8a32346bcced61f2e5/lib/MqttClient.js#L300)** in minutes, as it usually does not exceed one hour. The value can be converted back to minutes, but it would lose its precision up to ~6 minutes.

Thoughts?

**Comment by rand256** [comment]
Yeah, there were already questions regarding changing units for current cleaning time, and seems that I successfully forgot about it then. Will fix it.
