### ISSUE TITLE
Rooms feature - buttons greyed out on map

### ISSUE THREAD

**Issue by Stramm** [rand256/valetudo#124]
Hi Rand 256, I updated my S5 from the prerooted Valetudo 0.4.0 1898 with build in password and tried to test the rooms feature on 0.9.0 beta4 2008 (at least I'm nearly sure I flashed beta4, however it shows beta2 in the settings). First I enable rooms in settings then I try to create this rooms. For that I click the zones tab -> edit rooms and get to a map. However all buttons are greyed out and I can't do anything. Am I missing something? Tried FF beta and Chrome on Android and FF 72.0.2 on win.

I guess the buttons should let me devide the map into parts/ rooms and name this parts so the rooms feature from the main site can be used. 

And I also wanted to mention that I absolutely love this version. There are so many improvements I didn't even know I would need them. Map saving works great as multi floor feature. Enhanced timers or the dark mode are excellent and all the other little additions (zoom lock) make RE really useful.
Thanks,
Thomas

**Comment by rand256** [comment]
Hi. Er... Just a few notes:
1. There's nothing to **enable** for rooms, it's only possible to **disable** room markers in settings;
2. You can't create rooms yourself, the device does it. You can only edit what it has already created;
3. To make something with rooms it's required to select a room first: i.e. if you want to split a room into two - you need to select one room to work with, and if you want to merge two rooms into one - at first you need to select exactly two rooms. Otherwise the buttons are disabled. If you have no rooms, use the device as usual until it creates some.
4. There's no beta4 yet and I suppose it'll never be. The only available so-called release names are shown in Releases section here at Github.

To sum everything up, are you definitely sure you installed my version of valetudo? :)

**Comment by Stramm** [comment]
1. Uhm, yes, that's what I mean. Displaying room markers is enabled.
2. Then it seems nothing's created as there is nothing I can edit or is shown in the map.
3. I can not select any room 
4. I downloaded it from here https://vacuumz.info/download/gen2/
And cause you link to that site I assumed this verion is good to go.

But to avoid any confusion I used the build in update feature and updated to the beta2 provided here on github. Result is the same. It doesn't show anything to select, to edit and therefore I can not use the rooms feature. I attatch a screenshot of the rooms edit screen. Maybe that's a better description.

![Screenshot_2020-02-17 Mi Robot Vacuum - Zones](https://user-images.githubusercontent.com/61154100/74675467-eae39280-51b3-11ea-9839-207e12c277c4.png)

**Comment by rand256** [comment]
Well, I can't force your vacuum to create the rooms as it's not the thing valetudo can influence at all. :\
Try running full cleaning once maybe.

The images from vacuumz.info site were always good to go, but right now I don't know which exactly versions of my valetudo RE are included to which images there and that's upsetting.

**Comment by zvldz** [comment]
> The images from vacuumz.info site were always good to go, but right now I don't know which exactly versions of my valetudo RE are included to which images there and that's upsetting.

0.9.0-beta2

**Comment by zvldz** [comment]
The latest version of valetudo is used when building the firmware. 
It's enough to compare the date of the last release of valetudo and the date of the firmware release to understand which version.

**Comment by Stramm** [comment]
Thanks for the help. So the creation of the rooms is done by the roborock firmware itself and has nothing to do with Valetudo or RE. Good to know and I'll start with a clean map (map reset) tomorrow and give your suggestion a try. Will keep you updated...

**Comment by rand256** [comment]
@zvldz, okay, but there are people who just doesn't like playing comparing dates and guessing.

@Stramm, as far as I understand there's no need to reset map. For me at least it was enough to run full cleaning on existing map for some time (it even didn't finish the whole area).

**Comment by zvldz** [comment]
> okay, but there are people who just doesn't like playing comparing dates and guessing

I try to support the latest versions of valetudo. The difference can be a few days at most. Who is not satisfied with it can build firmware himself. But so you build the firmware yourself, there should be no problem.

**Comment by Stramm** [comment]
@rand256, thanks for the hint. Works now like a charm. Actually I had to start with a new map. Just starting a new full cleaning job wasn't enough. 

@zvldz, I appreciate that you build the firmwares every few days. It was just a little bit confusing for me to hear, there isn't a beta4 when I have downloaded it. Now I know that it was your naming scheme and that version was indeed the most actual one. Thumbs up for your work.

**Comment by zvldz** [comment]
> Now I know that it was your naming scheme and that version was indeed the most actual one. Thumbs up for your work.

Any developer (not just me) feels good, when someone evaluates his work.

**Comment by jcplu** [comment]
Rooms appear after full cleaning.
When I try to rename a room, I have an error message
There was an error (500) Process busy (-10001)

**Comment by rand256** [comment]
@jcplu, I've seen that error too, it is simply returned by firmware blackbox exactly this way without any further explanation. I had to reboot the device in this case for it to start working properly again. Fortunately it happened only once or twice for me.
