### ISSUE TITLE
A few initial questions before rooting

### ISSUE THREAD

**Issue by radokristof** [rand256/valetudo#126]
Hi everyone!

Thanks @rand256 for keeping this project alive!
However I have some questions which I couldn't find an answer for.
- I'm using custom voicepacks now. Are these will be lost after upgrade? If yes, can I change/upload these voicepacks easily? (I found a PR in the original Valetudo repo which is merged, this still works?).
- Some integration uses (for example I'm using openHAB) the local reverse-engineered API to control the robot locally. Are these are also lost in these fws, or only the cloud connection is removed?
- Are the firmware reset bug is gone? If I remember correctly there was some problem which caused the firmware to reset to the original one.
- After flashing, the Wi-Fi will be lost? You need to reconnect the robot to the Wi-Fi or it will use what was set before?
- On the provided [firmware collection](https://vacuumz.info/download/gen1/) site, there are firmwares with 'valetudo_re'. If you install these, it will install this fork of Valetudo? I mean it also contains the modded fw (htop, wget, etc...) + this Valetudo?

**Comment by rand256** [comment]
1. If firmware upgrade completes OK (and it usually does) you won't lose your already installed voicepack. Anyway you can always install it again provided you have it in *.pkg format (or you can manually upload it as a set of *.wav files to /mnt/data/rockrobo/sounds).
2. Valetudo itself uses the same local miio api for controlling the robot, as there not much else is possible to use.
3. Nope, there were no specific case found for reset bug and therefore nothing was specifically fixed for that. I personally have my Gen2 running without a single reset for as long as 8+ months now and counting, but others' experience may differ.
4. See 1.: no settings should be lost, but in general making backups is recommended just in case.
5. Yes it would. But the owner of the site (hi, @zvldz!) suggests you should guess which exactly version of RE will be preinstalled there based on the date when the image was created. Right now it looks like those images contain the latest 0.9.0.

**Comment by radokristof** [comment]
Thanks for the detailed answer! This looks really good to me!
I will try to install it on my gen1 vacuum tonight.

**Comment by zvldz** [comment]
> 5\. Yes it would. But the owner of the site (hi, @zvldz!) suggests you should guess which exactly version of RE will be preinstalled there based on the date when the image was created. Right now it looks like those images contain the latest 0.9.0

Yes, it is.
But I don't see any other way yet.

**Comment by zvldz** [comment]
But now Rand256(Erinome) makes firmware based on my (modified) builder, the difference is almost no.
Rand256, thank you for using my builder.

**Comment by radokristof** [comment]
Thanks!
So the flashing was not that simple.
I was on the latest firmware (4004 for gen1) where I was not able to flash it.
Used the recovery partition which had some really old fw, the update failed there again.
I had to update with the app to (34xx) version then I was able to install 3532 with valetudo_re from @zvldz .

Can I somehow upgrade to 4004? Is it worth it, hope that if I got it rooted once it will stay there?
Also I'm struggling with the map and docking also. It seems that now every time I do any command a new map will be created. With the original fw, usually this was done when a full cleanup was initiated. Why is it not like that here?
Also it is not really able to dock itself... I haven't restarted the vacuum since the install (only the automated reboot) I will try that first...

**Comment by rand256** [comment]
Yes, stock 4004 can't be locally reflashed. I'm not sure whether it's worth upgrading Gen1 device as I don't have one. But as far as I understand in no case normally should it create a new map on every command.

**Comment by radokristof** [comment]
Ok thanks!
The docking is solved, it was not caused by the firmware, but something blocked the dock :)
I will experiment more with this map creating thing. It wouldn't make much sense to redraw every time, because it migh get rotated, so even a previously selected zone cleaning will not fit the map...

**Comment by pidator** [comment]
> Also I'm struggling with the map and docking also. It seems that now every time I do any command a new map will be created. With the original fw, usually this was done when a full cleanup was initiated. Why is it not like that here?

What commands do you enter?
Gen1 doesn't have a persistent memory for the map, so indeed, if you start a new full clean a new map will be build. But with using the zone cleaning function you can bypass this behaviour. Thats like I'm using my Gen1 with Valetudo RE 0.9.0 and without any problems. I've my ontime build map, put my zones on the right place and everything's fine.

**Comment by radokristof** [comment]
And does your map rotates sometimes?
I haven't tried zone cleaning yet, only started a full cleanup and stopped after a few mins. However even when stopping and sending it back to the dock, cleaned the map and started to create a new one...

**Comment by pidator** [comment]
yes, it's random, on every new "full clean" (press "start" in Valetudo) there's a new map and often with a new rotation. this is normal behaviour of Gen1, you can't influence this.

What fw do you use before? A stock fw with MiHome App? It's the first time I hear about an Gen1 "keeping" the map.

**Comment by radokristof** [comment]
Sorry don't get me wrong... My map always got rotated even on the stock firmware.
I only read somewhere that you can leave it in a narrow straight place so the first movements will be the same also, that leaving with the same rotation...

My only assumption was that it looked like that this fw is cleaning the maps more often (not just when you start a new full cleanup).

**Comment by pidator** [comment]
> I only read somewhere that you can leave it in a narrow straight place so the first movements will be the same also, that leaving with the same rotation...

Can't say anything about this, haven't read and haven't tested. I'm using the zone cleaning from the beginning :-)

> My only assumption was that it looked like that this fw is cleaning the maps more often (not just when you start a new full cleanup).

Can't confirm: I've created my map the first time by a full cleaning and after this I only use zone cleaning, goto points or send-to-dock. Since Valetudo RE 0.9.0 rand256 also fixed the pause/resume function you'll found as dynamic buttons on the map. I've never had a new map with this controls.
**Edit:** But I'm still on FW 3468, perhaps there is/was a change in some control functions or robot states to FW 4004...

**Comment by radokristof** [comment]
I'm on 3532 now. Basically it now runs really smoothly (my main reason to use Valetudo was that I'm using Pi-hole to block unwanted domains and xiaomi always changed it's domain and the app loaded really slowly or never) - and in general it was slow. Valetudo seems running butter smooth compared to the app...
@pidator Did you had any firmware reset on the gen1?

**Comment by radokristof** [comment]
@rand256 I'm also using Telegram, which works great!

However it would be possible later to specify which status changed will be sent?
Right now it sends when it goes to sleep, starts charging etc... I would rather use something in the original MiHome app, only send on start, stop, error, etc...

**Comment by AlexOnFOSS** [comment]
> 
>     3. Nope, there were no specific case found for reset bug and therefore nothing was specifically fixed for that. I personally have my Gen2 running without a single reset for as long as 8+ months now and counting, but others' experience may differ.
> 
@rand256 
My S50 does reset itself almost once per month. What tweaks have you done to the version you are running your robot with?

**Comment by rand256** [comment]
@radokristof, well, that should be possible I suppose. Which exactly groups of states would you suggest? Errors of all kinds, everything related to cleanings of all kinds, everything related to moving (goto maybe, back to dock, docking, charging), anything else?

@AlexOnFOSS, fairly speaking, none of those which aren't already known to public. Before the latest release I had used [that image builder](https://github.com/rand256/dustcloud) for creating firmware for my own device, now I use [this one](https://github.com/rand256/vacuum). Dunno whether it's important, but I never use full cleaning - only zoned and also room cleaning now.

**Comment by pidator** [comment]
> @pidator Did you had any firmware reset on the gen1?

Till now, i've never had a firmware reset. I'm still using my rooted firmware build with the imagebuilder from dustcloud repository. Because of that, I've never tried a image of @zvldz, but if I will be affected in future of the reset bug, I probably will.

**Comment by radokristof** [comment]
@pidator I'm now using @zvldz firmware, I will see... Only using since a few days ago...
@rand256 Basically I want to eliminate the messages which happens so quickly.
So following the original fw and its notifications: all cleanups when started (full, zone, room... maybe inidicating what kind of cleaning is started), when cleaning finished and returning to dock, and all errors (stuck during cleanup, can't reach dock, ...).

What kind of messages I don't really need is going into idle mode, going into sleep mode (mostly after an error and I can't restart).
