### ISSUE TITLE
Verticel no go lines altered in the wrong direction

### ISSUE THREAD

**Issue by Wessix** [rand256/valetudo#13]
![Screenshot_20190813-094009](https://user-images.githubusercontent.com/4333994/62923782-cc3cb300-bdae-11e9-9e1d-46a259656514.png)

Those two vertical lines shoul "bend" the other way around. I painted them correct. 

I experimented with rrcc in the past where there was a button for flipping coordinates horizontal. Is it possible that i changed something back then and it survived a complete reflashing?

**Comment by rand256** [comment]
It looks like the whole map is distorted, being a bit rotated clockwise. But Valetudo can't help with that, as it receives the map as-is from the vacuum's firmware, and the firmware is a black box for us. You can only try to reset the map so it will be recreated again, hopefully with straight lines and square corners.

**Comment by rand256** [comment]
And probably it should be fixed in 9900c18, though looking at the screenshot given it's not obvious you've talked about virtual walls issue.
