### ISSUE TITLE
Nginx with paths different from "/"

### ISSUE THREAD

**Issue by s1lvi0** [rand256/valetudo#130]
I have tried to configure my roborock trough nginx to a path different from "/" and I have had some problems with map update. So I have find a possible problem in vacuum-map.js at line 69:
`ws = new WebSocket(protocol + '://' + (localStorage['urlOverride'] ? localStorage['urlOverride'].replace(/^.+:\/\/(.*?)\/?$/,"$1") : window.location.host) + '/');`
I have temporary fixed with:
`ws = new WebSocket(protocol + '://' + (localStorage['urlOverride'] ? localStorage['urlOverride'].replace(/^.+:\/\/(.*?)\/?$/,"$1") : window.location.host)+ window.location.pathname + '/');`
Is that the right way or can be fix in some other ways?
Thanks

**Comment by rand256** [comment]
This duplicates last '/' when pathname itself ends with it, but otherwise should probably be ok.

**Comment by rand256** [comment]
Fixed in 00c8840.
