### ISSUE TITLE
RE 0.9.0 : SSH

### ISSUE THREAD

**Issue by jcplu** [rand256/valetudo#132]
I upgraded to 0.9.0.
How can I restore my ssh key that doesn't work anymore ?
I can connect only with the password root/cleaner.

In Settings > Access Control Settings :
What information should I paste before clicking Save SSH keys ?
Thx

**Comment by rand256** [comment]
> How can I restore my ssh key that doesn't work anymore ?

Most likely you can't - upgrade procedure is a manufacturer's blackbox that doesn't preserve the old keys, so you'll need to copy it again from your PC/device.

> What information should I paste before clicking Save SSH keys ?

Er.. You need to paste your rsa-key, which looks like `ssh-rsa [many-letters-and-numbers-here] email@example.com`.

**Comment by jcplu** [comment]
It's ok. Thx

**Comment by jcplu** [comment]
Can I disable the connection with root/cleaner or change it ?

**Comment by pidator** [comment]
> ... or change it ?

```
root@rockrobo:~# passwd
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
```
