### ISSUE TITLE
RE : cleaning optimization

### ISSUE THREAD

**Issue by jcplu** [rand256/valetudo#133]
Is it possible to implement/optimize the robot movements ?
ie. the robot should clean a rectangle area by moving lengthwise in the area.

**Comment by rand256** [comment]
Maybe. But this would require disassembling and modifying firmware binaries, and I have no such experience.

**Comment by jcplu** [comment]
Where is located the firmware binary and do you think that is encrypted ?
And same question for the code that interacts with Telegram ?

**Comment by rand256** [comment]
See /opt/rockrobo/cleaner.

**Comment by jcplu** [comment]
It's not crypted. Do you know what are rr_loader (for firmware reset) ? and sysupdate (for pkg update) ?

**Comment by jcplu** [comment]
RoboController , RoboControllerM and RoboControllerR ? Do you know why 3 files ?

**Comment by rand256** [comment]
As I said, I have no experience of digging in binary files. All of these are created by the device's manufacturer. I have no idea what's happening inside of them.

**Comment by jcplu** [comment]
Ok, we will wait for manufacturer implementation. Thx.

**Comment by rand256** [comment]
Why, do you surrender so quickly? :) Really I'd rather not count on manufacturer implementing something above the current functionality for S5 series. It's already surprising they backported rooms from S6.
