### ISSUE TITLE
Save/Restore zones and forbidden-zones 

### ISSUE THREAD

**Issue by snowwiddow** [rand256/valetudo#137]
Hi,
first of all thanks for this great fork of valetudo.
Currently I use firmware 1898 with valetudo-re 0.9.2-beta 2 on a S55. Save and restore maps works as expected.
I have two floors. On the first floor I defined some zones and forbidden zones.
Now when I restore the map for the second floor the zones and forbidden zones of the first floor are still there and my vacuum won't go to the places it should go. In another words:
Zones and other things are not coupled to a specific map.
Maybe it's a problem by me but my intention is:
When I load a map the corresponding zones and forbidden-zones are also loaded.
But that's only a luxury problem.
Thanks a lot

By the way:
How can I update to firmware 2008 with the features of 1898 (I mean in a way that I don't get a crippled/stripped down ubuntu). The explanations on the wiki are a little bit "strange").

**Comment by rand256** [comment]
> When I load a map the corresponding zones and forbidden-zones are also loaded.

Zones are currently not coupled to the maps, but forbidden zones and virtual walls definitely are. I've just tried to save my current map as "A", then add some forbidden zones to it and save the result as "B". Next if I load back "A" newly created forbidden zones will be gone, and if I load "B" - they will appear again. I've checked it on 2008 firmware, but as I recall it worked exactly the same on 1898 too.

> How can I update to firmware 2008 with the features of 1898 (I mean in a way that I don't get a crippled/stripped down ubuntu).

Nobody has succeeded with this for now.

**Comment by snowwiddow** [comment]
Hello rand256,
thanks for the explanations and the top fork.
Greetings

**Comment by LordMike** [comment]
Stupid question - how does one save and restore maps ?

**Comment by pidator** [comment]
> Stupid question - how does one save and restore maps ?

Just answered this yesterday here https://github.com/rand256/valetudo/issues/166#issuecomment-600864778
