### ISSUE TITLE
Where to get FW 1886?

### ISSUE THREAD

**Issue by ualex73** [rand256/valetudo#14]
**Descriptiong**

The website mentions FW 1886, but i can't find it on the regular sites (the original valetudo website doesn't mention this version either).

**Vacuum Model:** 
Roborock S55
**Valetudo Version:** 0.4.0 

**User-Agent** 

**Additional context**

**Comment by rand256** [comment]
You can download it [here](https://vacuumz.info/download/gen2/stock/). If you don't trust that site, you can at least see the original file name and download it yourself from xiaomi CDN.

**Comment by ualex73** [comment]
Thanks, I found them now ... The filename is with an unique identifier in there, that's why I could find them ;-) Maybe add that site also to your wiki?

**Comment by josch** [comment]
Yes, please write down the filenames somewhere.

For everybody else reading this issue, this link works:

https://cdn.awsde0.fds.api.mi-img.com/rubys/updpkg/v11_001886.fullos.ee205b4f-7d81-45c9-95a3-a4eaeed1af52.pkg

**Comment by rand256** [comment]
Created a wiki page.
Feel free to contribute any additional info there if needed.
