### ISSUE TITLE
WiFi credentials confirmation message wrong for Gen1

### ISSUE THREAD

**Issue by TheAssassin** [rand256/valetudo#144]
When setting the WiFi credentials, the following message is shown:

https://github.com/rand256/valetudo/blob/abafff731d9feeeb5a83c07bcbdbcb482f503a2d/client/settings-wifi.html#L124

On Gen1, there's a reset button, but it just resets the entire bot. To *only* reset the WiFi, one has to press the home and power buttons together for a few seconds. The bot confirms this by playing a message that it resets the WiFi, and the hotspot is immediately available.

I would like to improve this description, but I don't know whether the instructions are actually correct for Gen2. Could anyone with a Gen2 please send a picture of the section under the lid?

![DSC00806](https://user-images.githubusercontent.com/4503202/75393412-5503e200-58ee-11ea-9191-1b0efacf7a3e.JPG)

**Comment by rand256** [comment]
Kinda fixed in 60c060c.

**Comment by TheAssassin** [comment]
Yup, seems okay.
