### ISSUE TITLE
Incorrect password for prebuilt v11_001898

### ISSUE THREAD

**Issue by junior013** [rand256/valetudo#147]
Neither the default "cleaner" password nor the one in the .password file works for root login to the prebuilt v11_001898.pkg over SSH
(the firmware itself is OK, Valetudo also accessible)

**Comment by rand256** [comment]
Older images created with origin dustcloud builder have default username _ruby_ and the password provided in .password file.
Newer `vacuum`-prefixed images have username _root_ and password _cleaner_.

**Comment by junior013** [comment]
Thanks, @rand256,
I tried _root_ and _cleaner_ user, but didn't know about _ruby_ :/
My friend pointed to the _vacuum_- prefixed images, that works fine.
