### ISSUE TITLE
Check box hard to see on Firefox Android

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#149]
The check box for zone cleaning selection is hard to see with light grey on white....

![Screenshot_20200301-080454](https://user-images.githubusercontent.com/36039152/75623022-68d96d80-5ba6-11ea-8873-fe9657aa6f81.png)

**Comment by pidator** [comment]
has to be an firefox specific problem with the interpretation of the onsen ui...
with opera or chrome the checkboxes are with an grey background and easy to see:

![checkbox](https://user-images.githubusercontent.com/59822549/76112016-ae040200-5fe1-11ea-8b9b-960a1292eacb.jpg)

**Comment by v-a-d-e-r** [comment]
Ok, thanks for the hint. Then I must live with it, because another browser only for the robot is no option....
