### ISSUE TITLE
Improperly formatted map data

### ISSUE THREAD

**Issue by ghost** [rand256/valetudo#150]
I've managed to get Valetudo RE 9.0 going on my Gen 2. But the valetudo-mapper addon in Hass.io doesn't like the data it's sending to the map_data topic.

Showing this error in the logs of the add-on:
```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:80:42)
    at MqttClient.emit (events.js:223:5)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:336:12)
    at work (/app/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```
Looking at the MQTT-topic with MQTT-explorer clearly shows that there is data being sent to the topic while cleaning. Data looks like this (just the first chars, you get the gist):
```
�4I�Iox	_��#WA?r��>x��ֱ�������w ��\���pv����γ�
���y��8
```

I'm at a loss as to how to fix this.

**Comment by rand256** [comment]
For me it looks like you're using some outdated valetudo-mapper addon of Hass.io or whatever it is. Looking at stack trace, the issue happens at line 80 in MqttClient.js, but current version of the mapper doesn't have JSON.parse call at that line.

Could you try running default [valetudo-mapper](https://github.com/rand256/valetudo-mapper)? Most likely it should work ok with that map data.

**Comment by MakkaKaplar** [comment]
Which hassio addon are you using? I found this one: https://github.com/Poeschl/Hassio-Addons which seems to just pull the latest valetudo-mapper master branch when building.
Edit: I installed it and tried it out, working fine! I don't know in which step Hassio addons rebuilds the Docker Image, but if stop+start doesn't do it try reinstalling it.
I am however using a Gen1, but that shouldn't make a difference afaik

**Comment by ghost** [comment]
Apologies, I was indeed using one of the addons in Poeschl's repo. He actually has two versions in there, and I was using the wrong one. Installed the Valetudo-mapper addon and everything is running perfectly.

**Comment by HIT2022** [comment]
I'm encountering the same issue with Poeschl's CantBelieveItsNotValetudo addon. His valetudo-mapper addon on the other hand brings the map in w/o issue, but some of the draw-related config options were not 'taking' as expected for me, so I'd thought I'd give CantBelieveItsNotValetudo a shot. Spent several hours tinkering with this so glad to hear I'm not alone. I'll open an issue on his repo
