### ISSUE TITLE
Problems with rooms

### ISSUE THREAD

**Issue by MaluNoPeleke** [rand256/valetudo#152]
I have S50 with firmware 2008 and Valetudo RE 0.9.1 installed.
The robot has already identified some rooms which I now wanted to give a name or split in smaller parts but it doesn't work because of the following errors:

1. Name a room: 500 - process busy (-10001)
  This error is now showing all the time after it worked for one room name.
2. Split a room: 500 - Split map failed (-10000)
This error is now showing all the time after it worked for one room split.

Anyway to fix this?

**Comment by rand256** [comment]
Try rebooting the device. It looks for me like some issue with manufacturer's firmware, don't think it can be fixed in valetudo.

**Comment by MaluNoPeleke** [comment]
I just tried it and it helped with the naming problem but not with the room splitting. Anyway to debug it?

**Comment by rand256** [comment]
For splitting the most important part is to place the cutting line the way firmware would like it. It _seems_ like it wants the cutting line to be inside the area, not touching the edges. But sometimes it's not. You just need to keep trying to find the position that will fit. I've wrote the note you see when clicking split button exactly about that.

I don't see the way how to fix that, its code is in a manufacturer's blackbox. It just works as is.

**Comment by MaluNoPeleke** [comment]
Thanks for your support but it only worked once for a small room but even after over 50 tries it doesn't work again. But at least I know it is nothing you can do.
