### ISSUE TITLE
telegram message grouping feature: group "all" not working

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#154]
hi @rand256,
what's the difference between the telegram message grouping `all` and `cleaning + errors` - what additional messages should be included in `all`?

If I set the notifications to `all`, I've got only one message after starting a zoned cleaning run (telling me the name of the choosen zones) and then no more messages! Nothing about _going to the dock_ after finishing of the cleaning and no message that the robot is _charging_. however these two messages for example were delivered with `cleaning + errors` set, so I  supposed them to be send also with `all`.

**Vacuum Model:** Gen1 (4004)
**Valetudo Version:** 0.9.1

**Comment by rand256** [comment]
The logic behind those selectors is straightforward. See the code [here](https://github.com/rand256/valetudo/blob/testing/lib/Telegrambot.js#L67):
- if types set to 0 (any) - literally any event is allowed;
- if types set to 1 (cleaning) - only a subset of events related to cleaning can trigger notifications, a few events can trigger them only if they appear after another events (i.e. "going to dock" is shown only after any "cleaning", but not after "paused"), and errors are always allowed;
- if types set to 2 (or anything else) - only error-type events (codes 9 and 12) are allowed to send notifications.

There can be an issue that if a bunch of events are received by the bot fast, some of them may become omitted, and this can lead to some cleaning-related events might be mistakenly missed.

And I don't know how could it work so weird for you. The sole reason I can imagine is that you've disabled receiving all notifications altogether (using crossed dynamic icon at bot's main menu), if so you won't receive any status changes at all regardless of the setting at web interface, while messages sent after starting cleaning aren't status changes by their nature but a simple messages, so they aren't influenced by notification disabling switches.

**Comment by pidator** [comment]
I see... and I can't explain at the moment neither.

> The sole reason I can imagine is that you've disabled receiving all notifications altogether (using crossed dynamic icon at bot's main menu), 

Nope, all notifications are allowed.
Perhaps this is related with upgrading from 0.9.0 to 0.9.1: I haven't explicit clicked _saved_ on telegram bot settings, just saw that the notifications were set to `all` automatically with the new version. I've now changed the notifications back to `all` and will try with some cleaning runs tomorrow and will report my results.

**Comment by pidator** [comment]
was possibly an error by only replaceing the binary file and don't confirm/save the telegram bot settings again. After doing so, I've got all the wanted messages with setting `all`. Sorry for confusing, i'll close this issue.
