### ISSUE TITLE
Telegram authorize user

### ISSUE THREAD

**Issue by mtjoernelund** [rand256/valetudo#155]
Think I am missing something obvious here, but I cannot figure out what. 

I have created a boot for my vacuum and added to the config. Config says that it is connected but it has no authorised clients yet. When I write to the bot in telegram I get no response. What am I missing here?

**Comment by rand256** [comment]
If you have version 0.9.0 or below, the bot may ignore your messages when internal datetime on the device is not correct. That was actually done to prevent the bot answering an outdated messages, but I had to remove that check in 0.9.1 since it appears that quiet a few users have their device with completely wrong time set.

**Comment by mtjoernelund** [comment]
I’m on ver 0.8.1 so might be it. Although timezone is correct but not sure if the time is off. I can’t even find anywhere in the web interface to check the actual
time?

**Comment by rand256** [comment]
There's nowhere to see current time in the web interface. Generally it should be synchronized on every device boot, so it was meant it would be OK by default if only one wouldn't block internet connection to the device.

So to actually check date it's required to do ssh login and call `date` command. And probably google around on how to set datetime manually.

**Comment by mtjoernelund** [comment]
Don’t have ssh access until home. Going to check when I get home.

**Comment by mtjoernelund** [comment]
Just wanted to confirm. As soon as I got time corrected on the vacuum, the Telegram bot started responding. 

Thanks for your feedback!
