### ISSUE TITLE
rootfs full

### ISSUE THREAD

**Issue by miodzicho** [rand256/valetudo#158]
Hi all, i tried to upgrade to 0.9.1 but I was unable to do so. I did quick look with ssh and see this 👍 

root@rockrobo:/# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                  169.5M    169.5M         0 100% /
/dev/root               169.5M    169.5M         0 100% /
devtmpfs                 64.0K         0     64.0K   0% /dev
none                    249.3M     32.0K    249.3M   0% /run
tmpfs                    30.0M    372.0K     29.6M   1% /var
tmpfs                    64.0K         0     64.0K   0% /dev
tmpfs                    30.0M         0     30.0M   0% /tmp
tmpfs                   100.0M      2.6M     97.4M   3% /run/shm
/dev/mmcblk0p1            1.5G    136.1M      1.3G   9% /mnt/data
/dev/mmcblk0p6           62.0M      5.3M     53.5M   9% /mnt/default
/dev/mmcblk0p10         169.5M    153.9M      6.8M  96% /mnt/updbuf
/dev/mmcblk0p11          15.5M      2.0M     12.7M  14% /mnt/reserve
tmpfs                     5.0M     16.0K      5.0M   0% /mnt/data/rockrobo/rrlog
root@rockrobo:/#

Seems like rootfs is full...how to clean it ?

**Comment by rand256** [comment]
You can't. The image of 2008 firmware has rootfs set way smaller than it was in the previous versions.

Use large /mnt/data partition to download binary, then overwrite the old one in /usr/local/bin.

**Comment by rand256** [comment]
Oh, and remove that partially downloaded file at rootfs.
By default it has several MBytes of empty space when valetudo installed and you have none.

**Comment by miodzicho** [comment]
Which one...

root@rockrobo:/# ls -hal
drwxr-xr-x   19 1000     1000        1.0K Dec  5 09:48 .
drwxr-xr-x   19 1000     1000        1.0K Dec  5 09:48 ..
drwxr-xr-x    2 root     root        1.0K Jan  3 12:23 bin
drwxrwxr-x    2 root     root        1.0K Dec  5 09:48 boot
drwxrwxrwt    7 root     root        2.9K Mar 11 09:15 dev
drwxr-xr-x   14 root     root        1.0K Feb 26 14:30 etc
drwxr-xr-x    3 root     root        1.0K Jan  2 10:36 home
drwxr-xr-x    5 root     root        1.0K Jan  3 20:33 lib
lrwxrwxrwx    1 1000     1000          11 Nov 15 07:23 linuxrc -> bin/busybox
drwx------    2 root     root       12.0K Dec  5 09:48 lost+found
drwxrwxr-x    6 1000     1000        1.0K Aug 11  2018 mnt
drwxr-xr-x    3 root     root        1.0K Oct  3 14:21 opt
dr-xr-xr-x  107 root     root           0 Jan  1  1970 proc
drwxr-xr-x    4 root     root        1.0K Mar 11 16:50 root
drwxrwxrwt    4 root     root         260 Mar 11 16:23 run
drwxr-xr-x    2 root     root        1.0K Jan 16 16:12 sbin
dr-xr-xr-x   12 root     root           0 Jan 10  1970 sys
drwxrwxrwt    2 root     root        1.4K Mar 11 17:17 tmp
drwxr-xr-x    7 root     root        1.0K Feb 14 14:00 usr
drwxrwxrwt    7 root     root         160 Jan 10  1970 var

**Comment by miodzicho** [comment]
Ok, did reboot, rootfs looks better, but I cannot open web page anymore...

Filesystem                Size      Used Available Use% Mounted on
rootfs                  169.5M    124.9M     35.8M  78% /
/dev/root               169.5M    124.9M     35.8M  78% /
devtmpfs                 64.0K         0     64.0K   0% /dev
none                    249.3M     32.0K    249.3M   0% /run
tmpfs                    30.0M    360.0K     29.6M   1% /var
tmpfs                    64.0K         0     64.0K   0% /dev
tmpfs                    30.0M         0     30.0M   0% /tmp
tmpfs                   100.0M      2.5M     97.5M   3% /run/shm
/dev/mmcblk0p1            1.5G    151.0M      1.3G  10% /mnt/data
/dev/mmcblk0p6           62.0M      5.3M     53.5M   9% /mnt/default
/dev/mmcblk0p10         169.5M    153.9M      6.8M  96% /mnt/updbuf
/dev/mmcblk0p11          15.5M      2.0M     12.7M  14% /mnt/reserve
tmpfs                     5.0M     24.0K      5.0M   0% /mnt/data/rockrobo/rrlog

**Comment by rand256** [comment]
So it seems like you've solved it.

**Comment by Andoramb** [comment]
it's actually full for me too. now that I'm trying to update to 0.9.3.
I already removed the binary from _/usr/local/bin_ but still no space left to copy the new version.
What can be removed or maybe linked to different partition?
Thanks

**Comment by Andoramb** [comment]
hm, after a reboot I got 50MB free space, so it was solved after all

**Comment by rand256** [comment]
So if you removed the binary but didn't stop running application, it won't free the space allocated for it.

**Comment by Andoramb** [comment]
yes, true. thanks for the confirm :)

**Comment by jnsw** [comment]
still full for me, what can I delete probably? i used dpkg to remove it, damn
