### ISSUE TITLE
How to use mqtt

### ISSUE THREAD

**Issue by Riseryn** [rand256/valetudo#159]

**Comment by Riseryn** [comment]
question cancelled

**Comment by Riseryn** [comment]
Hello
I can't use basic command like
mosquitto_pub -h localhost -p 1883 -t 'valetudo/rockrobo/command' -m '{"command":"start"}'

but 
mosquitto_pub -h localhost -p 1883 -t 'valetudo/rockrobo/custom_command' -m '{"command":"zoned_cleanup","zone_ids":["kitchen"]}'"

works fine.

what's wrong with  my first command?

Thanks

**Comment by rand256** [comment]
I guess you may need to use just `-m 'start'` instead.

PS: I'm not using mqtt.

**Comment by Riseryn** [comment]
Thanks,
That was so simple and I searched so complicated solutions ^^
