### ISSUE TITLE
Document 'SEGMENTED_CLEANUP' command

### ISSUE THREAD

**Issue by LordMike** [rand256/valetudo#161]
It's my understanding this repo adds the `SEGMENTED_CLEANUP` command, as this wasn't in the original Valetudo project. This should be documented somewhere :)

.. I found it in the code.

**Comment by rand256** [comment]
> It's my understanding this repo adds the SEGMENTED_CLEANUP command, as this wasn't in the original Valetudo project

This is not surprising to add room cleaning mqtt command along with overall room cleaning support.

> This should be documented somewhere :)

So, are there all other commands documented somewhere?

**Comment by LordMike** [comment]
Nothing documented in this project, no. Valetudo had a minimal of documentation in the wiki, [f.ex. here](https://github.com/Hypfer/Valetudo/wiki/Home-Assistant-Integration).

A similar page could be added to Valetudo RE :)

**Comment by Hypnos3** [comment]
A wiki is a knowledge base website on which users collaboratively modify and structure content.

Why don't you add the desired documentation as a new wiki pages yourself?

**Comment by Stefan300381** [comment]
hey guys, I was about to give it a try but I'm too stupid. When I try to create a new wiki page in githuba and once I enter code, it does not properly detect line breaks.

I tried to paste an example mqtt configuration like this:

```
  "mqtt": {
    "enabled": true,
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://myser:mypassword@myhost:1883",
    "provideMapData": false,
    "caPath": "",
    "qos": 0
  },
```

but every line was above was just in one single line (at least in the preview window, maybe a github bug?) :-/

Here a screenshot:
![2020-04-13_15h39_15](https://user-images.githubusercontent.com/33487900/79124648-1098ac80-7d9d-11ea-83c1-c16d26fc3746.png)

**Comment by rand256** [comment]
It properly detects new lines for me when I enclose the code with ```, in the preview at least.

**Comment by LordMike** [comment]
Good start @Stefan300381 - Githubs docs for Markdown [is here](https://help.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github), and the relevant section for code blocks [is this](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code).

A trick to get syntax highlighting, is to start your block with the name of the language. Like this for JSON:

> \```json
> { "my-json": "value" }
> \```
