### ISSUE TITLE
Add unique_id to HA discovery document

### ISSUE THREAD

**Issue by LordMike** [rand256/valetudo#162]
Add a unique id to the HA discovery document, so HA will be able to identify the vacuum between HA restarts.

One option is to use the unique device id (did), og the WIFI MAC address.

**Comment by rand256** [comment]
There was some unique_id [already added](https://github.com/rand256/valetudo/commit/7f8c8ba1aec82695251edeaddbbee5db47fbb4c3) the last year. Should it be changed somehow? I'm not using HA, so not sure about its requirements.

**Comment by LordMike** [comment]
You're correct. I needed to restart HA for it to overwrite the original entity from the original Valetudo project.

My bad.
