### ISSUE TITLE
Set Vacuum Power with Timer

### ISSUE THREAD

**Issue by radokristof** [rand256/valetudo#166]
In the Xiaomi App, you have the ability to set different Vacuum Power for each Timer.
Can this be possible with Valetudo also?

Thanks!

**Comment by doemEINS** [comment]
Which Valetudo RE version are you running? It's possible already:

![image](https://user-images.githubusercontent.com/56892878/76759858-cec01a80-678c-11ea-9fc5-1b382407b6c9.png)
(Gen2, FW2008, Valetudo RE 0.9.1)

**Comment by radokristof** [comment]
I'm using the latest one RE 0.9.1.
![image](https://user-images.githubusercontent.com/36210568/76759940-fdd68c00-678c-11ea-9d8d-785957301bd9.png)

**Comment by pidator** [comment]
Timer dialouge seems to be different for Gen1 (@radokristof) and Gen2 (@doemEINS) devices!?

**Comment by rand256** [comment]
Timers API is different for 2008 firmware and the previous ones. The former allows specifying the number of repeats, fanpower and desired rooms while the latter doesn't.

**Comment by radokristof** [comment]
@rand256 Also you can't add a Timer name with spaces in it. No errors will be shown, it simply doesn't save the timer.

**Comment by doemEINS** [comment]
@pidator indeed power states for timers are not available on Gen1, had the chance to check that now, too. The OP should have given some more infos about the issue and the circumstances.
But I can't tell if it is a missing implementation for Gen1 or if it's simply not possile on Gen1.

Timers with a blank in the name is also not possible on Gen2. The timer dialogue closes without a message, warning or error.

**Comment by radokristof** [comment]
@doemEINS Yes I forgot to include that this is a Gen1 Vacuum.
In the original app and on the original fw it is possible a long time ago... (maybe since I have the vacuum, around 2 and half years ago).

About the name problem: at least a warning could be added, if it is possible...

**Comment by rand256** [comment]
> Timers with a blank in the name is also not possible on Gen2. The timer dialogue closes without a message, warning or error.

Yeah, this is a bug, it appears it doesn't like spaces, a workaround will be available in the next release.

> In the original app and on the original fw it is possible a long time ago... 

Well, if it has worked on Gen1 for a long time already, then it's just a matter of guessing correct parameters to timer setup command I believe. I don't own a Gen1, so the only thing I could do is to try blindly adding a fanpower value into the command and hope it'd work. Though it definitely would be better if someone could setup some mirobo-like tool that can send raw miio commands and find the proper format.

**Comment by rand256** [comment]
I've made a few changes and build this [beta binary](https://fs.erinome.net/valetudo-0.9.2-beta.tar.gz). Could anyone with Gen1 check whether this can change fan power in scheduled cleaning?

**Comment by pidator** [comment]
> Could anyone with Gen1 check whether this can change fan power in scheduled cleaning?

Will do tomorrow and provide you the result!

**Comment by pidator** [comment]
Hi @rand256,
no power mode setting available in timer setting dialog for Gen1 with your provided beta:
![timers](https://user-images.githubusercontent.com/59822549/76952954-318cef80-690e-11ea-9e90-e211428bf6c7.jpg)

the creation date of the binary file besides is 07.03.2020 5:50pm!

**Comment by rand256** [comment]
Ooops. Seems that I've scp'ed the wrong file. Reuploaded the correct one. Sorry.

**Comment by pidator** [comment]
new file installed, now on 0.9.2-beta ;)
indeed I have a new field for the fan power in the normal cleaning schedule settings:
![timers2](https://user-images.githubusercontent.com/59822549/76975796-5d6e9c00-6933-11ea-99c4-f38ff99753e1.jpg)
is it possible to add this also to the zoned cleaning setting?
![timers3](https://user-images.githubusercontent.com/59822549/76975861-6cede500-6933-11ea-9b08-264cca865f5c.jpg)

Because of Gen1 I will lose my map when starting a full clean run now, but if it's not possible I would also test it with a full run ;)

**Comment by rand256** [comment]
The thing is zoned scheduled cleaning simply starts common zoned cleaning at the specified time, and it just doesn't have a way to specify a fanpower for that exact cleaning. But the native scheduled cleaning does have some parameters section for it, though it may not work as we don't know its proper format.

It is possible to add a fanpower setup for zoned scheduled cleaning (via directly running an additional command), but then it won't be able to set back the previously chosen fanpower when that zoned cleaning ends or gets aborted.

**Comment by pidator** [comment]
ah ok, I do understand. Tomorrow I will sacrifice my map and we'll see if the power mode is changed during scheduled cleaning. If I get you right, the power mode should be reset to the value it was before after the scheduled cleaning is finished?

**Comment by rand256** [comment]
> the power mode should be reset to the value it was before after the scheduled cleaning is finished?

I believe it should. At least in fw 2008 at Gen2 this is how it works.

> Tomorrow I will sacrifice my map and we'll see if the power mode is changed during scheduled cleaning

Wait, are there issues with map save/restore feature on Gen1? Or why are you saying so like you can't easily restore a "sacrificed" map?

**Comment by pidator** [comment]
Oh, till now i believed saving/restoring a map needs the persistent mode of the roborock and therefore a Gen2 is necessary. That's why I've never tested to save or restore a map on my Gen1. 

Will do this task also :-) thanks for the hint!

**Comment by radokristof** [comment]
@pidator I also thought that :) 
How can I save the map on the Gen1?
Persistent Data sub-menu says that this is only available on the Gen2.

**Comment by pidator** [comment]
Settings -> Webinterface -> Show multi map button

Then you'll have two new buttons on home tab.

**Comment by radokristof** [comment]
Oh thanks :) I will try this what happens if the map is lost and I load the saved map, will it use that one correctly.
Maybe, another feature could be if this works (on the Gen1), if you start a predefined zone cleanup, it should load a map first (so that ensure that the zone fits on the map - in an event when the map is rotated).

**Comment by rand256** [comment]
> Oh, till now i believed saving/restoring a map needs the persistent mode of the roborock and therefore a Gen2 is necessary

Map restore requires more time on Gen1 (20-30 seconds on Gen1 compared to 2-3 seconds on Gen2) since it requires a full restart of all map-processing daemons on Gen1 while for Gen2 it's only a matter of quickly sending a start/stop commands, but it works on both devices nonetheless.

> Maybe, another feature could be if this works (on the Gen1), if you start a predefined zone cleanup, it should load a map first

IMO it's not the procedure that can be used completely automated due to a lot of, well, let's call it "necessary overhead" of the process. After all it wasn't designed by the manufacturer that we'll be riffling map files inside the device while it's operational.

**Comment by radokristof** [comment]
> After all it wasn't designed by the manufacturer that we'll be riffling map files inside the device while it's operational.

I'm don't know much about how this hack works so I understand if this is can't be possible. However the robot will not be operational (if you mean operational is when the robot is cleaning currently or moving).
What would be needed is to call Restore map (with one of the loaded maps) and then send the commad with the zone coordinates to the robot (which will start the cleanup).

**Comment by pidator** [comment]
Nice, great work! I've just run the scheduled cleaning:
Robot is set normally to "Balanced", I've created a timer with mode "Max", the robot started just in time, set the fan power to "Max", after finishing the cleaning (on his way back) the mode was already reset to "Balanced". So power mode setting for (normal) scheduled cleaning works on Gen1, too!

I've additionally restored my previously saved map -> works also without any problems on my Gen1. Tried to run a zoned cleaning then -> works with the previous saved zone coordinates and the standard power setting (Balanced). Great!!

Just one thing to mention:
You'll just have to hide the power mode "Mop" in the drop down list in timer configuration window for the Gen1 device:

![dropdown](https://user-images.githubusercontent.com/59822549/77059641-89435d80-69d7-11ea-9b46-dba577edde67.jpg)

;-)

**Comment by radokristof** [comment]
Great! How can I update to this version?
dpkg says this is not a deb archive :(

**Comment by pidator** [comment]
> dpkg says this is not a deb archive :(

yea,because it's just a binary file, nothing to install. You can either wait till @rand256 will include these changes in the official build or using the beta binary by doing

- `root@rockrobo:~# service valetudo stop`
- Replacing current binary `valetudo` in `/usr/local/bin`
- `root@rockrobo:~# reboot`
- voila

**Comment by radokristof** [comment]
@pidator Thanks I have figured it out since :) 
Firstly I just thought I'm using wrong commands and didn't thought about it not being an archive file...

**Comment by radokristof** [comment]
Valetudo RE 0.9.2 is out, which adds this functionality to missing fws also.
Thanks @rand256 !
