### ISSUE TITLE
Stop song always in chinese

### ISSUE THREAD

**Issue by DavidB81** [rand256/valetudo#168]
After installing the French voice pack, the sound of the stop is still in Chinese. 
I tried with a voice pack in English and it's the same problem. All voices are in English except that of the stop sign.
How to solve the problem to have all the voices in French?

**Vacuum Model:** Gen2 S5

**Valetudo Version:**  0.9.1 RE
Thanks

**Comment by rand256** [comment]
You have to find a voice pack updated for 2008 firmware, as the old ones doesn't contain some newly added phrases.
