### ISSUE TITLE
Browsing vacuum history pushes mapData updates to MQTT

### ISSUE THREAD

**Issue by LordMike** [rand256/valetudo#169]
When I browse old vacuum history entries, and view their maps, I receive a new image from the Valetudo companion mapper service. It seems to me, as the history is being pushed as "current" map data over MQTT.

**How to Reproduce**
1. Visit a history element on the Valetudo vacuum, view the associated map
2. Visit the Valetudo mapper image, at `http://ip:port/api/map/image`, and observe the historic map rather than the current map

**Expected behavior**
Valetudo mapper only works with current maps.

**Screenshots**
N/A

**Vacuum Model:**
Roborock S5

**Valetudo Version:**
`0.9.1`

**User-Agent**
N/A

**Additional context**

**Comment by rand256** [comment]
This is how it currently works - vacuum pushes all the maps to a single upload point.

Feel free to suggest better implementation, but remember that originally configured firmware uploads map snapshots to the huge cloud and valetudo has to upload them back to the device, and its available resources are limited. You can see in [that old comment](https://github.com/Hypfer/Valetudo/issues/86#issuecomment-466096432) how exactly multiple map upload points can be configured.

**Comment by LordMike** [comment]
Hmm. I feared as much, in which case there probably isn't much to do, other than hacks, such as "if this new map changes too much since the last, it's probably a history thing", or setting a value when browsing history and not pushing mapdata if that value is set (and then clearing it ..)..

It's probably fine. I don't view the history that often anyways :)
