### ISSUE TITLE
No No-Go Zones would be saved?

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#17]
hey rand,

2 days before my Rockrobo S50 flashed back to original firmware by itself. I was able to get it back to Firmware 1720 and installed your version of valetudo as always. Then I made a whole run of my robo through my whole flat to get the initial map.

Then I started configuring my zones. Everything was done and worked as intended.
Then I wanted to add my "no go zones"... I could add them on the map and then I hit the "save" buton.

After beeing back in the menu I just wanted to take a 2nd look at them and go back to setup of the no-go-zones but... nothing is there anymore, just a clean map. :(

**Comment by nicedevil007** [comment]
nvmd... forgot to enable persistent data.
But maybe you can add a warning if someone enter the configuration for nogo-zones and didn't enabled persistent data?

**Comment by rand256** [comment]
Should be implemented in e66a931
