### ISSUE TITLE
Timers seem to be 12hrs off

### ISSUE THREAD

**Issue by hammondses** [rand256/valetudo#170]
I've been banging my head against a wall for a few hours and can't figure it out, I'm located in NZ using the latest RE 2008 on my S5. 

The time zone I have selected in the timers tab is Pacific/Auckland. 
Time output of date & hwclock are both correct, yet my robot runs 12hrs out of sync. 

Any ideas?
![robot time](https://user-images.githubusercontent.com/21191206/76842201-c35d1400-689e-11ea-8a2e-279c2342f025.PNG)

**Comment by pidator** [comment]
you've already tried this https://github.com/rand256/valetudo/issues/4#issuecomment-510554485?

**Edit**
> The time zone I have selected in the timers tab is Pacific/Auckland.

ah ok, I've overlooked this, sry

**Comment by hammondses** [comment]
Yep, I even changed it to something random & no change :(
![timezone](https://user-images.githubusercontent.com/21191206/76843186-4b8fe900-68a0-11ea-8887-512e1f279e17.PNG)

**Comment by pidator** [comment]
the correct timezone is also set in 
`/mnt/default/roborock.conf`
?
Do you use a NTP server?
`/opt/rockrobo/watchdog/ntpserver.conf`

**Comment by hammondses** [comment]
In /mnt/default/rockrobo.conf its set to Europe/Berlin, though I can't edit it as its read only. I seem to also recall reading somewhere to not change that one as its a system requirement for some reason. 

Wasn't using NTP, so I added it, no change. Setup 2 timers 12hrs apart for 2 different zones and it started the one that is 11am when it's 11pm.

**Comment by rand256** [comment]
I've just checked this setup: 2008 firmware, no other NTP except default called by rrwatchdoge at boot, timezone at Timers page is "Pacific/Auckland", zoned cleanup configured at 0:50. This resulted in starting cleaning at Tue Mar 17 11:50:00 UTC 2020 (as printed by `date` at ssh console of the device). Looks correct as Auckland is UTC+13, isn't it?

**Comment by hammondses** [comment]
I've played around with it for a few hours, changed time zones to different places etc and thought it was working, yet I got home to find no vacuuming had been done. 9:41pm rolls round and sure enough the vac starts cleaning.

Any suggestions?
(times are a bit off due to taking a minute to capture each screenshot)

![1](https://user-images.githubusercontent.com/21191206/77048310-14017800-6a2b-11ea-8ea8-384b839768e8.PNG)
![2](https://user-images.githubusercontent.com/21191206/77048314-149a0e80-6a2b-11ea-93be-05d1251fd255.PNG)
![3](https://user-images.githubusercontent.com/21191206/77048315-1532a500-6a2b-11ea-8216-a3f4678301c4.PNG)
![4](https://user-images.githubusercontent.com/21191206/77048317-15cb3b80-6a2b-11ea-8fc3-0b3ac00dccd7.PNG)

**Comment by rand256** [comment]
Does it happen only in zoned scheduled cleaning or in native scheduled cleaning too?

**Comment by hammondses** [comment]
I can't actually add a scheduled clean, when I press save it just disappears & nothing gets added. Possibly because I haven't done a full clean since updating to the new version?
I put my old map in from prior to upgrading and haven't done a full manual clean.

![1](https://user-images.githubusercontent.com/21191206/77107105-0a0c6300-6a85-11ea-86bc-c6da0ae0c6ac.JPG)
![2](https://user-images.githubusercontent.com/21191206/77107108-0bd62680-6a85-11ea-9cc6-7c0ff8052cd2.JPG)

**Comment by rand256** [comment]
That's because roborock doesn't like names with spaces, and the fix isn't released yet.
