### ISSUE TITLE
Map not loading on iOS devices, menu broken

### ISSUE THREAD

**Issue by AlCalzone** [rand256/valetudo#171]
**Describe the bug**
When opening Valetudo on my iOS devices, I don't see the map. The status panel in the top left corner is stuck on "Status: connecting" and "Battery: 0%". Afterwards the "Home" button in the menu is no longer working.
If I don't click on "Map", the Home screen works.

On my desktop PC it works fine (Firefox).

**How to Reproduce**
Click on Map, then Home

**Expected behavior**
See the live map, then see the home screen.

**Screenshots**

**Vacuum Model:** Gen1
**Valetudo Version:** 0.8.1

**User-Agent** iOS default browser

**Additional context**

**Comment by rand256** [comment]
I have no ios devices so I have no idea what is broken there.

**Comment by AlCalzone** [comment]
How can I help you find the problem?

**Comment by rand256** [comment]
Today I've tried loading a macos (v10.14) in vmware and checked current valetudo web interface in Safari 12.1. Everything worked fine: both map and main menu. Then I've installed XCode to see its Device Simulators tool, where I loaded the emulation of an iphone with ios v13.3. I've started a mobile Safari and again it correctly loaded the map and everything.

It took me some hours and a few dozens on GBs of bandwidth, but... Everything works there.
And I have no other option to test on ios devices anyway.

Which ios version does your device run?

**Comment by AlCalzone** [comment]
Both my iPhone and my iPad are on 13.3.1. Sadly the dev tools aren't an option, because I don't have a Mac.

**Comment by radokristof** [comment]
For me it works on an iPad and iPhone also (latest iOS) with Safari...

**Comment by AlCalzone** [comment]
@radokristof which Valetudo version do you have?

**Comment by radokristof** [comment]
The latest one 0.9.1

**Comment by AlCalzone** [comment]
Ok I'll need to check that out. I'm still on 0.8

**Comment by pidator** [comment]
Can't reproduce this. Just finished an Gen1 installation of 4007 0.9.2 with iOS and macOS without any problems...

**Comment by AlCalzone** [comment]
After updating to 0.9.2 it works like a charm.
