### ISSUE TITLE
Original Xiaomi Soundfiles 3.5.7_002008

### ISSUE THREAD

**Issue by Titanius** [rand256/valetudo#172]
How can I get the newest original de.pkg Sound file from Firmware 3.5.7_002008 ?

Valetudo RE 0.9.1 - 02008 Roborock S50 Gen 2

Many Thanks

**Comment by zvldz** [comment]
https://vacuumz.info/download/voice/s5/2008/de.pkg

**Comment by rand256** [comment]
The straightforward solution is something like installing only rooted firmware without valetudo, then registering the device in mi home app and downloading needed sound pack via mi home. This way you'll get a set of wav files in your device in the localization you want, so you can download it back to your computer. Then you can use these files in either building own sound *.pkg package or by simply copying them to the device when required.

Or search the internet to check whether someone already uploaded such package somewhere.

Anyway this is out of scope for valetudo.

**Comment by Titanius** [comment]
Many Thanks! I Love the new Valetudo 0.9.1 Firmware and Thanks to everyone who helped. 
Thanks for the many, many time on developing the firmware and improvements
