### ISSUE TITLE
SSH login pre installed img Valetudo RE 0.9.2 2008

### ISSUE THREAD

**Issue by Twsts** [rand256/valetudo#173]
Hi!

Having trouble with ssh login root/cleaner not working after updating the last pre installed img. 

On ssh login it says "Unable to negotiate with 192.168.1.222 port 22: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,kexguess2@matt.ucc.asn.au"

Have cleared the known hosts and added my rsa key via the web interface.

Rolling back to 1998 firmware gives back ssh login.

I understand the 2008 firmware is somewhat locked down, but we are still expected to have ssh login via these custom firmwares?

**Comment by rand256** [comment]
I haven't encountered such issue myself (i.e. my openwrt snapshot and oracle linux 8 are fine with connecting to the device), but if you try to simply paste what you've quoted into google search, it'll provide a bunch of links with possible solutions.

And, anyway, it's out of the scope for valetudo. We just use the base firmware provided by roborock.

**Comment by Twsts** [comment]
Allright. Thanks.
For other who might experience this. To fix this I added;
```
Host 192.168.1.222
    KexAlgorithms +diffie-hellman-group1-sha1
```

to my ~/.ssh/config
