### ISSUE TITLE
Update Valetudo RE

### ISSUE THREAD

**Issue by Titanius** [rand256/valetudo#174]
What is the best way to update Valetudo 0.9.1 to 0.9.2 without losing Maps, Roms and Zones? I use to first Install the vacuum_valetudo_re_2008.pkg Image File.

**Comment by rand256** [comment]
https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware

**Comment by Titanius** [comment]
and in which case I use the firmware update in the Valetudo web interface.  Under Settings - System (send request) ?

**Comment by pidator** [comment]
To switch to a new (roborock) base firmware (e.g. 2008), not the Valetudo Version!

**Comment by Titanius** [comment]
Ok Thank you I Unterstand.
