### ISSUE TITLE
Upgrading firmware via webui shows: 400 error invalid parameters

### ISSUE THREAD

**Issue by bruvv** [rand256/valetudo#175]
**Describe the bug**
Upgrading the firmware via the web ui never succees and shows a 400 error.

**How to Reproduce**
1. Copy firmware link + MD5 from here: https://github.com/rand256/valetudo/releases/tag/0.9.2
2. Go to the web ui: http://XXX.XXX.XXX.XXX/#settings.html
3. Click on send request under firmware update
4. Paste link from step 1
5. Add the MD5 as well
6. Error ```400 error invalid parameters``` shows and nothing happens

**Expected behavior**
Update the firmware and upgrade valetudo without updating it via FTP.

**Vacuum Model:**  Gen2

**Valetudo Version:** 0.9.2

**Firmware Version:** 002008

**Miio-client:** 3.3.9

**User-Agent** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

**Comment by pidator** [comment]
Do you insert the link to the MD5 file or the content of the file?

**Edit:**
Btw your already on fw 2008 and valetudo re 0.9.2 and tries to update never the less?

**Comment by bruvv** [comment]
I am on 2008 already and want to upgrade valetudo and yes both of them are links. I do not paste the raw file.

**Comment by pidator** [comment]
For just upgrading valetudo see
https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware

For upgrading the whole fw via the send request function you'll have to insert the plain md5 hash (the content of the file), not the link!

**Comment by bruvv** [comment]
Thanks that did it :) until there will be an easier way of upgrading just the binary file.
