### ISSUE TITLE
valetudo-mapper python

### ISSUE THREAD

**Issue by guinmoon** [rand256/valetudo#178]
Hey. A huge request to write a mapper for python. It is possible without a server, only an convert map to image.

**Comment by pidator** [comment]
What's the issue here related to Valetudo RE? To get just a image of the current map, try 
`http://robot_ip/api/simple_map`

**Comment by guinmoon** [comment]
Thank you very much for your answer. I did not know where else to ask.

**Comment by rand256** [comment]
> [...] to write a mapper for python. It is possible without a server [...]

I can't get the idea of this. There's no python on the robot, so even if someone would write a mapper on python, it will require some server-like device to run at. And if you already have a server-like device, why wouldn't you run the already-existing node-based mapper there?

PS: Simple map at the robot is _really_ simple and looks awful. And even so it is extremely slow.
PPS: I don't know python, don't ask me.
