### ISSUE TITLE
Normal behavior? AppProxy is going 100% CPU after cleaning...

### ISSUE THREAD

**Issue by stpmuspro** [rand256/valetudo#182]
It's my first valetudo install - so I don't know if this is normal. So I´ve just did some "htop"-watching.

After rebooting AppProxy seems to be sleeping.
After first cleaning AppProxy is going to use 100% CPU in 1 Thread and 20% in another one.
So what is it doing?

I would expect it should go to sleep again after cleaning.

 PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  572 root        0 -20  112M 97244  4604 R 102. 19.0 49:38.86 AppProxy
  536 root        0 -20  112M 97244  4604 S 118. 19.0 58:10.84 AppProxy
  576 root        0 -20  112M 97244  4604 S  7.3 19.0  3:28.40 AppProxy
  574 root        0 -20  112M 97244  4604 S  0.0 19.0  0:23.58 AppProxy
  575 root        0 -20  112M 97244  4604 S  0.0 19.0  0:00.81 AppProxy
  571 root        0 -20  112M 97244  4604 S  0.0 19.0  0:01.92 AppProxy
  553 root        0 -20  112M 97244  4604 S  0.0 19.0  0:01.38 AppProxy
  573 root        0 -20  112M 97244  4604 S  0.0 19.0  0:00.13 AppProxy

**Vacuum Model: S50

**Valetudo Version:** 0.9.2

**Comment by stpmuspro** [comment]
Follow up:
I just found out, if I do a reload of the map after cleaning, AppProxy is going to sleep.
So something is missing after the normal cleaning process...

**Comment by rand256** [comment]
Nothing to be done from valetudo: it only sends a command to start cleaning and then everything is done by robot's blackbox-like firmware which we can't control.

Though I've never seen an AppProxy consuming 100% CPU on my Gen2.

**Comment by stpmuspro** [comment]
Thanks for your reply,

so I did some more map reloading, trying another build, rebooting etc...
At least disabling mihome.vacuum adapter in iobroker stopped this strange behavior for me...
