### ISSUE TITLE
Cleaner Icon driving backards

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [rand256/valetudo#184]
It's just a small thing but my cleaner icon is driving backwards.
The lid of the robot is on the backside.

**Comment by rand256** [comment]
This is the icon source: [[link]](https://www.flaticon.com/free-icon/robot-vacuum-cleaner_1199855), and I doubt it will look better if rotated by 180 deg.

Probably it would be better to find more proper icon for roborocks, but I didn't succeed with that.

**Comment by pidator** [comment]
Hm, for a Gen1 everything fits perfect: the moving directions match exactly the alignment of the current symbol ;-)

**Comment by radokristof** [comment]
@pidator
Same for me, works correctly :) It is even better than in the original fw. I can see exactly the rotation of the vacuum

**Comment by rand256** [comment]
So, I took a paint and made a new icon:

![1199855 (4)](https://user-images.githubusercontent.com/30267719/78132061-befb3400-7424-11ea-92fa-abf455f4b566.png)

In theory it should resemble a Gen2 device, at least that was my intention. It isn't very detailed, but I've tried to test more detailed ready-to-use icons and when shrank to low sizes their look isn't very pleasing.

Any suggestions? Should I replace the current icon with this?
Though I'd guess one could say to keep both and use them depending on the device detected.

**Comment by radokristof** [comment]
From this perspective the two devices (Gen1 and Gen2) almost look identical, only the position of the Radar is different (as I know). So I think we could use your icon in both models... the little sidebrush helps identify the orientation easier.

**Comment by pidator** [comment]
Nice work! Looks bretty good.

> Though I'd guess one could say to keep both and use them depending on the device detected.

this would be awesome, changing the cleaner symbol related to the value of `device.model` :-)
