### ISSUE TITLE
Firmware compatibility (i.e. valetudo-re 0.9.2 on 1886?) 

### ISSUE THREAD

**Issue by crbble** [rand256/valetudo#186]
Hi, I am running a Gen 2 with firmware 1886 and wondered whether it is possible to run the newest valetudo-re on this firmware. I downloaded the binary and replaced the currently running one, restarted the service and everything looks normal for now. 

Are there any restrictions when running older firmware? Does the software check for compatibility?

Thanks,
Robert

**Comment by rand256** [comment]
There's no restrictions, it even works on Gen1.

The only thing you lose on older firmware is per-room cleaning. And probably 2008+ is less impacted by random resets issue, but that is yet to be known.
