### ISSUE TITLE
[ENHANCEMENT] Set whether to return to dock or stay in place after finishing.

### ISSUE THREAD

**Issue by arieltools** [rand256/valetudo#188]
After finishing a cleaning run, it would be helpful to be able to select whether the vacuum should go back to the base (the default) or whether it would stay put in place.

Sometimes when mopping, if the vacuum goes back to the base, it would wet or dirty-up other sections of the map as unfortunately this vacuum can't still disable the mop cloth.

**Comment by pidator** [comment]
Afaik is this behavior (returning to dock after cleaning) part of the roborock blackbox that can't be modified via the gui. Valetudo just submitted the cleaning command.

**Comment by arieltools** [comment]
The cleaning could be monitored, even in front-end (though better through a demon or crontab in the vacuum), then a trigger could be set.

**Comment by v-a-d-e-r** [comment]
Similar to my topic...
https://github.com/rand256/valetudo/issues/93

**Comment by arieltools** [comment]
> Similar to my topic...
> #93

Yes.

**Comment by rand256** [comment]
Implemented in 0.9.5.
