### ISSUE TITLE
[ENHANCEMENT] Charge and continue

### ISSUE THREAD

**Issue by arieltools** [rand256/valetudo#189]
Thank you for these enhancements to the amazing Valetudo!

I think it would be nice to be able to trigger the last un-finished zoned clean when the vacuum runs out of battery. The Roborock could go to the base, recharge and then finish up the zoned clean.

**Comment by pidator** [comment]
Hm, I thought all the time this should be normal behaviour of the roborock firmware. But to be honest: I've never had this situation yet. My robot finishes always before he runs out of battery. Perhaps I will provoke such a sitation in near future and will let you know what happens :-)

**Comment by rand256** [comment]
I also believe this is already implemented in roborock firmware.
