### ISSUE TITLE
Delete saved map data

### ISSUE THREAD

**Issue by radokristof** [rand256/valetudo#190]
It seems that something went wrong during update (or maybe the map data is different?!) and the old map is not working...
I have created a new one. Can I somehow delete the old unusable map from the selection? Where these files are stored?

Thanks!

**Comment by pidator** [comment]
Push the Loap Map Button and then the cross on the right side of the map name.

**Comment by radokristof** [comment]
Oh sorry for the noob question... On the dark interface, I can barely see that icon...
Thanks!
