### ISSUE TITLE
Enhancement request: when configuring zones, set suction power for each zone

### ISSUE THREAD

**Issue by mvmaastricht** [rand256/valetudo#191]
I LOVE _Valetudo RE_, thanks a lot Rand! 

Right now, I've set a cleaning mode of 5 areas in my living room for my Gen1 vacuum cleaner, to prevent the robot to get stuck in the convection heating put (because Gen1 does not support no-go zones).

Since 0.9.2 you've added the possibility to set the suction power within the timer. That's nice, but I find myself searching for a use for it: i.e. make the robot clean **twice** a night? With different area's and different suction power settings?

I think another, maybe more convenient, way to tweak suction power settings during cleanup, would be to add a button in the interface were you set the zones. I.e.: now, there the 'k' button to set the amount of times one would like to have the zone cleaned. You could probably add another 'sp' button to toggle through the 5 (or 6, if you include mopping) power modes. 

I my case, the suction power would increase as soon as the 5th zone would get a cleanup (which happens to be our cat litter area). See screenshot. 

Would that be possible?

<img width="1273" alt="Schermafdruk 2020-03-30 15 18 43" src="https://user-images.githubusercontent.com/60920461/77916946-2afd6100-729a-11ea-95b7-08314e78b095.png">

**Comment by rand256** [comment]
This can't be done. A single command is sent to firmware to start cleaning of all 5 zones at once, and there's no way to:
a. ...set different power modes for different sub-zones;
b. ...even know which exactly sub-zone is currently being cleaned.

**Comment by mvmaastricht** [comment]
Ok... And what if I'd only configured a zone with _one_ area? Would it then be possible? I could then separate the fifth area as a separate zone, add the suction power to only that area, and set up a timer to clean the 1st zone with 4 areas and the 5th zone with 1 area...?
In the interface you could disable the suction power buttons, as soon as the user chooses more than one zone...

Or is this impossible too?

**Comment by rand256** [comment]
>  and set up a timer to clean the 1st zone with 4 areas and the 5th zone with 1 area...?

A timer runs via exactly the same command to start zoned cleaning. And if you request it to run several pre-configured zones, all their areas will be simply concatenated together and sent into that command. As such you can't run multiple zones having more than 5 areas in total because of that.

**Comment by mvmaastricht** [comment]
I know about the 5 area-limit. Just was hoping that there'd be a work around to make it possible to add suction power configuration to at least one zone/area.

But it seems to be impossible, due to the concatenation. So that'll leave me to keep on using the other valuable option you've already added: to clean up the same area several times. 

Thanks a lot for taking the time to explain it!
