### ISSUE TITLE
SSH Key refused :/

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#2]
Hey rand256,
just wanna try your very awesome version of valetudo.
I rebootet my Roborock S50 after installing your version of valetudo and now I can't connect anymore to my Roborock via ssh because my key is refused.

Now I have to start from ground up right?

**Comment by rand256** [comment]
How did you install it?

**Comment by nicedevil007** [comment]
> How did you install it?

Hey rand256, 

I ve got a fully functional rooted S50 with "normal" valetudo installed. I transfered your version of valetudo to the S50 and stoped the service valetudo before, then started it again. 

It did run until I rebooted the S50 with "reboot" inside the CLI.

Then that happened what I described above... no access to the S50 anymore with my sshkey.

I did a fresh reflash with your valetudo version and the 1864 firmware now. It seems to work for now :)
So maybe there were strange things happening.
