### ISSUE TITLE
How to change timezone via ssh

### ISSUE THREAD

**Issue by HHenning0815** [rand256/valetudo#204]
Hello,

timezone in ssh shown in terminal is utc.
Change via dpkg-reconfigure tzdata not work.
How do I do?

Cleaning Timers not work...

**Comment by rand256** [comment]
Timezone for timers is set via Settings->Timers->Gear icon at top right.
What you see in ssh doesn't matter for timers.

**Comment by HHenning0815** [comment]
Thanks for answer.

OK, but times dont work - cleaner not start at the time.

I can change the two existing timers (existing from original valetudo), but cannot create a new:

"Fehler beim Senden: 500 - The Lab Status is disabled (-10000)"

Any ideas where i can search why timers dont work?

**Comment by zvldz** [comment]
> How do I do?

Try it via ssh(root)
` ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime`

**Comment by HHenning0815** [comment]
thank you,

now I get from date:
Fri Apr 10 08:49:36 HST 2020
Should be 20:49 CEST - am I right?

**Comment by zvldz** [comment]
> Should be 20:49 CEST - am I right?

Yes, that should be it.

**Comment by HHenning0815** [comment]
After set Berlin in Webinterface (there was honululu set) via ssh is shown:
Fri Apr 10 18:59:10 UTC 2020

Question is: why the timers completly not working- not at "other timezone", cleaner is not starting at the two timers.

**Comment by rand256** [comment]
> "Fehler beim Senden: 500 - The Lab Status is disabled (-10000)"
> 
> Any ideas where i can search why timers dont work?

It tells you to enable persistent data in settings (so-called "Lab Status").
Unfortunately it is impossible to change that text, it is the error message from the firmware itself.

**Comment by HHenning0815** [comment]
I enabled the persistent data, deleted all timers and create one now - but this new dont work also

Is there one point where I can see where the problem is?

**Comment by pidator** [comment]
> I can change the two existing timers (existing from original valetudo)

What do you mean with the last sentence "existing from original valetudo"?
Which firmware is currently installed on your robot and what version of valetudo?
What timezone is written in your 
`/mnt/default/roborock.conf`?

**Comment by HHenning0815** [comment]
First I had Valetudo, then I changed to Valetudo RE.
Valetudo RE 2008.
timezone=Europe/Berlin
