### ISSUE TITLE
[feature] Add mqtt config in settings

### ISSUE THREAD

**Issue by thelittlefireman** [rand256/valetudo#206]
Hi,
realy great projet i love it !
I wonder if it could be possible to add a category on settings to edit the mqtt configuration ?

Thanks

**Comment by rand256** [comment]
How often do you need to edit mqtt config on the robot after initial setup?

**Comment by thelittlefireman** [comment]
Hi, it's just to be more usefull like as the other settings are already editable by GUI (wifi, access control, etc). I often change the mqtt password for security reasons, it could be a great help.

I could try to make a PR for this
