### ISSUE TITLE
Feature request: option to disable the step-sensors

### ISSUE THREAD

**Issue by Schluggi** [rand256/valetudo#21]
Hi,

at the moment i've to cover the step-sensors of my S5 to get it work on black carpet. It would be awesome to have a switch in the settings for this :)

Nice Fork!

PS:
This also was an [issue](https://github.com/Hypfer/Valetudo/issues/329) in the original Valetudo repo by Hyper, but didn't get any attention.

**Comment by rand256** [comment]
Unfortunately, this requires disassembling and patching original software, since there's no valid way to disable those sensors otherwise. And right now the only thing valetudo can do is to call functions already implemented in the firmware.
