### ISSUE TITLE
Get coordinates

### ISSUE THREAD

**Issue by MickL** [rand256/valetudo#210]
Really great project, thanks so much!

Is it possible to get the coordinates of a point on the map somehow?

E.g. I can go to `http://vacuum-ip/api/get_config` and see the goto-spots I defined, but when I use this coordinates in `python-miio` or `node-red` the vacuum tries to go somewhere else. Are this coordinates not correct?

**Comment by pidator** [comment]
perhaps this could help: https://github.com/Hypfer/Valetudo/issues/270
Or have a look in the code :)

**Comment by MickL** [comment]
I tried but with no success. Its a shame Hypfer just closed the issue without taking 5 seconds to answer it... Maybe it has something todo with the rotation of the map

**Comment by rand256** [comment]
For goto spot locations see "conversion" [here](https://github.com/rand256/valetudo/blob/testing/lib/miio/Vacuum.js#L629).

**Comment by MickL** [comment]
> For goto spot locations see "conversion" [here](https://github.com/rand256/valetudo/blob/testing/lib/miio/Vacuum.js#L629).

Interesting.  I will try that out and give feedback. Could have something to do with the map rotation.
