### ISSUE TITLE
Feature Request: Save map zoom and position

### ISSUE THREAD

**Issue by Xento** [rand256/valetudo#211]
It would be glad if the position and the zoom level of the map could be saved.
So you can zoom and move the map to fit your needs and on every reload, the map would be at the saved position.

**Comment by Stramm** [comment]
Would be a nice addition.

**Comment by p1ranha** [comment]
Yes, I would also love that. Have to scroll everytime.

**Comment by Xento** [comment]
I'm working on a hackish version.
At the moment you have to zoom, than reload and than pan to where you want the map to be.
This is because I don't know how to calculate the position when you zoom in.
I have no experience with canvas.
