### ISSUE TITLE
Feature request: save/load zones, forbidden zones, and goto locations with map

### ISSUE THREAD

**Issue by elgesl** [rand256/valetudo#213]
Hello,

 first of all thank you so much for your great work! Especially, the multi-map feature is really important for us. However, we have zones on each floor where the robot mustn't go and cannot use forbidden zones as any forbidden zone would remain at the same position on each floor (relative to the station which we have on each floor). If they were saved/loaded with the map of the floor, we could just define them per floor. The same is true for zones and goto-areas.

 The same feature could also be used to define no-go zones where carpet lie on a map for mopping the floor and one for vacuuming.

 Would that be possible?

All the best,

Chris

**Comment by pidator** [comment]
hm, following https://github.com/rand256/valetudo/issues/137#issuecomment-590733094 forbidden-zones and virtual walls should be saved related to the different floor maps, shouldn't it?

**Comment by elgesl** [comment]
I may be stupid, but saving the map named A, adding forbidden zones, saving the map as B, and then restoring A does not remove the forbidden zones. Neither does it reappear after deleting it and restoring B.

**Comment by elgesl** [comment]
Okay forget it. Obviously a bug which was fixed. At least it works after updating to 0.9.3 (from 0.9.2)
Thanks nevertheless

**Comment by rand256** [comment]
There were no multimap-related changes between 0.9.2 and 0.9.3 though.

**Comment by elgesl** [comment]
Now, you made me completely confused. I did exactly the same before and after the update. And before it nothing happened and afterwards everything worked as expected.

Any plans for saving/loading the zones?
