### ISSUE TITLE
Looses map when lifting

### ISSUE THREAD

**Issue by z7y8hsBP** [rand256/valetudo#218]
**Describe the bug**
I've installed rand256/Valetudo on my Roborock S55 using a dustbuilder image, afterwards updating it to the current release (0.9.3).
I now have several problems:
* When lifting the Roborock, the maps are lost.
What could help?
Thanks!

**How to Reproduce**
1. (I'm sorry, my mistake)
2. Lift the robot because it cannot find its dock -> all map data is lost

**Expected behavior**
1. (I'm sorry, my mistake)
2. Roborock not loosing its map when being lifted

**Screenshots**
![screenshot_home](https://user-images.githubusercontent.com/51470766/80074395-5c8be400-8549-11ea-93d2-f5dbcbc082ab.png)
![screenshot_settings](https://user-images.githubusercontent.com/51470766/80074398-5f86d480-8549-11ea-9c61-b794d1874d52.png)

**Vacuum Model:** 
S55

**Valetudo Version:** 
0.9.3

**User-Agent** 
Current Chrome on Windows 10

**Additional context**

**Comment by z7y8hsBP** [comment]
I am sorry - I somehow missed the "web interface"-settings and now store/restore buttons are present. It still looses the map though :(

**Comment by rand256** [comment]
Valetudo is a kind of extended UI for roborock firmware. What you describe looks like an issue with the firmware and isn't connected to valetudo.

Make sure you have parsistent data enabled in settings and the robot has at least once run full cleaning and - important part - returned to the dock itself after that. That means it wasn't interrupted or manually carried to the dock.
