### ISSUE TITLE
Unknown error code

### ISSUE THREAD

**Issue by bruvv** [rand256/valetudo#22]
When you place a virtual wall, pickup the robot and move it in this forbidding zone the web ui shows:
![image](https://user-images.githubusercontent.com/3063928/67095856-36127800-f1b7-11e9-9ab6-3de4dfda5609.png)
The robot says:
"Error no go zone please move the robot away from the no go zone." (or something simmilar)

**Comment by rand256** [comment]
Probably a26a98b should help. Didn't check that myself yet.

**Comment by bruvv** [comment]
fixed thanks
