### ISSUE TITLE
Q: Change from hyperf Valetudo to rand256

### ISSUE THREAD

**Issue by jackydany** [rand256/valetudo#220]
Hi,

im new to this Software and Vacuums.
I flashed my Gen1 and Gen2 with selfbuild images with Valetudo.
Now on my Gen2 i want to try rand256/Valetudo .
Could you tell me how to get from V to rand256/Valetudo ?

Thanks a lot.

Btw: Great work!

**Comment by rand256** [comment]
The simplest way is to download a prebuilt image and flash it with xvacuum tool from a smartphone.

Or, if you know linux console and don't wish to use new firmware, you can always keep your already installed firmware and just ssh to the device, stop valetudo service and scp unpacked valetudo RE there, overwriting the former valetudo binary with the new one. Though if you built your own images and didn't disable xiaomi excessive logging, I'd still better suggest to create a new image or use something pre-built.

**Comment by jackydany** [comment]
Hi,

i build my firmware image by using the instructions on valetudo/dustcloud.
i would prefer not to use ready build firmware images.
i am using debian linux on my laptop and build the firmware with this and flashed 2 S50 and 1 Gen1 with it right now.
i dont now if there is excessive logging enabled in my build image, how to tell the difference? where to look at?
my image is based on 1886 for the S50 and its loosing the map even if i enable the lab mode.
the second S50 cant load the webUI completly, i cant start the cleaner from it, seems like a process cant gather the information needed. but i am not familiar with the software to have a deeper look.

Thats why i would try a new Valetudo binary first. 
So just download the binary and overwrite the existing?
Where to find only the correct binary? Could you give me a link please, i cant find only the binary. All firmware images and complete packages, but not single files.

Thanks so much for the work and your help.
really appreciated!

Stefan

**Comment by rand256** [comment]
> Where to find only the correct binary? Could you give me a link please, i cant find only the binary. All firmware images and complete packages, but not single files.

Have you ever looked at releases section of this repo? There's a tar.gz archive containing only the binary.

Then you may want to consult /deployment section, it's a bit outdated but still relevant for 1886-like firmware. Also you should probably know that self-built dustcloud images are known to occasionally factory reset the device at 3:15 AM, so I'd suggest you to set a timezone where 3:15 AM would happen either earlier in the evening or later in the morning, since it isn't very nice to be woken up by the robot loudly saying that it's going to reset itself.

**Comment by jackydany** [comment]
HI, i read the wiki, and from there you can only find the pre build firmware images. i just found the binary, thanks.

is there any place to find some information about the differences of hyperf V, yours and v-RE ?
with my self deployed image, this should be the same as the prebuild, right?
i am trying to find out where the main differences are between the different versions / forks and also within the firmware versions as well. you prefer 2008, hyperf does 1886 as mentioned in the wiki for building the image yourself.
thats confusing me a bit.
sorry for the dumb questions and thanks again for your help.

**Comment by rand256** [comment]
> is there any place to find some information about the differences of hyperf V, yours and v-RE ?

I don't know what do you mean by 'v-RE'. Some initial differences between RE/non-RE are listed on the index page of this repository. I'm not aware of latest origin valetudo changes.

> with my self deployed image, this should be the same as the prebuild, right?

It depends. There are a lot of options in image builder. Also my prebuilt images as well as those listed on vacuumz.info, are build by [vacuumz image builder](https://github.com/zvldz/vacuum), not by dustcloud. So I highly doubt it's exacly the same, it's more like resembling.

> and also within the firmware versions as well. you prefer 2008

2008 fw is the first (and currently the only) one that does support rooms cleaning on Gen2 devices.
That's why I "prefer" it.

**Comment by jackydany** [comment]
Hi,
sorry if my questions / answers are misleading or unclear.
v-re i mena valetudo-re ;) (just too lazy to write valetduo all the time).
the initial differences i know. but whats underneath? is it nearly the same or does it differ a lot?
i used options like ntp, disable updates, adb exchange etc.

but with the 1886 i could use zoned cleaning as well on my gen2 and even gen1 i think.
wheres the difference?

i just took a shortcut know and downloaded your 2008 all inc package with 0.9.3.
its working much much better than my own 1886 build.
it kept the wifi settingbs, and my language files.
now its keeping the map and the zones correctly.
are there the same issues know with the occasionally rebooting and resetting robots as on original valetudo?
i kblock the internetconnection for the robots, so i want to use my own ntp (my router). i can set the timezone in the settings, but not my ntp. thats the last thing i need to find out.

and the integration to ioborker, this seems different to the original valetudo, right? but thats not so important.

if i can help i would like to, but i am not programming for more than 10 years now, so i cant contribute any code i think.
if you have an idea, let me know!

great work, works flawlessly at the moment. much more improved and convenient than the original.  every feature i need and even more!

thanks a lot

**Comment by rand256** [comment]
> v-re i mena valetudo-re

And I meant that there's no "yours and v-RE", as that is the same thing.

> but whats underneath? is it nearly the same or does it differ a lot?

You always can read the commit history here.

> are there the same issues know with the occasionally rebooting and resetting robots as on original valetudo?

There were a few reports about resets on images created with dustcloud builder.
And I don't remember any mentions of that on images from vacuumz builder.

I did never block internet connection for my gen2 and it is running fine for months.

**Comment by pidator** [comment]
> i can set the timezone in the settings, but not my ntp. thats the last thing i need to find out.

Check 
`/opt/rockrobo/watchdog/ntpserver.conf`

**Comment by jackydany** [comment]
ok, i just messed up between hyperf, you and alexkn, sorry!

my gen1 on my dustcloud build just reseted this night. i am flashing your 4000 image now.
it really improved everything on my gen2.

@pidator, thanks, rand256 already mentioned it. thanks non the less.

**Comment by jackydany** [comment]
i just realized, he didnt mention it!
sorry! and thanks again pidator (and rand256 of course)
