### ISSUE TITLE
[feature] strip the symbols of the valetudo binary for the Gen2 2008 images and increase filesystem size

### ISSUE THREAD

**Issue by canope-25** [rand256/valetudo#221]
Hi,
realy great projet i love it !
I wonder if it could be possible strip the symbols of the valetudo binary used for the Gen2 images.

the root filesystem is almost full:
Filesystem                Size      Used Available Use% Mounted on
rootfs                  169.5M    154.3M      6.5M  96% /

the valetudo binary is big because of the symbols:
du -hs /usr/local/bin/valetudo
44.5M	/usr/local/bin/valetudo

/usr/local/bin/valetudo: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 4.4.174, not stripped

The same binary ( stripped of the symbol) is 20 mbytes ligoter !!:
24M	valetudo

valetudo: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 4.4.174, stripped

I don't think users plan to debug locally the valetudo binary, so the symbols are not really useful.

This will give us some space in the rootfs/root filesystem.

Do you know if its also possible possible to increase the filesystem size ?
the underlying partition size is (if i remember well) 512mbytes.

Thanks in advance

**Comment by rand256** [comment]
> The same binary ( stripped of the symbol) is 20 mbytes ligoter !!:
> 24M valetudo

Can it still run?

> Do you know if its also possible possible to increase the filesystem size ?
> the underlying partition size is (if i remember well) 512mbytes.

It definitely can be done provided the pre 2008 firmware had much larger filesystem than it is now. But I'm personally not ready to hack into this right now and watch numerous resets along the way, nor this whole idea is directly related to valetudo as it still fits even on the current small filesystem.

But if someone would make that happen, I'd be grateful for that.

**Comment by canope-25** [comment]
Yep, for your information.
Allmost all the binaries are stripped in the firmware:

```
/opt/rockrobo/cleaner/bin/AppProxy:        ELF 32-bit LSB  executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=88843f2572cee3e2c22e5a578f0a8968cd210af3, stripped
/opt/rockrobo/cleaner/bin/RoboController:  ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=a2ce8c299763a35a7c743f659de452ed8b768549, stripped
/opt/rockrobo/cleaner/bin/RoboControllerM: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=dbe130be0152afe1aba516cb9815910e048ddd1e, stripped
/opt/rockrobo/cleaner/bin/RoboControllerR: ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=02bc63a782a777802dc9b7ac33210696b847c9fc, stripped
/opt/rockrobo/cleaner/bin/SysUpdate:       ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=313411db40e927c1b98519d751a9e30689841085, stripped
/opt/rockrobo/cleaner/bin/rr_loader:       ELF 32-bit LSB  executable, ARM, EABI5 version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=85f0c8f7f0fedc420525a363451208d82b832586, stripped
```
But, I'm not sure regarding the fact that the application rely on NPM.

I've done some tests and was not able to obtain anything good ...
[https://github.com/zeit/pkg/issues/50](url)

i'm almost sure that it's possible to improve the way that the binarie ( arm native ) is done.

regarding the second question, i've done the job and it's seem to be working :)

```
root@rockrobo:/mnt/data/valetudo# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                  495.9M    155.0M    318.7M  33% /
/dev/root               495.9M    155.0M    318.7M  33% /
devtmpfs                 64.0K         0     64.0K   0% /dev
none                    249.3M     28.0K    249.3M   0% /run
tmpfs                    30.0M    132.0K     29.9M   0% /var
tmpfs                    64.0K         0     64.0K   0% /dev
tmpfs                    30.0M         0     30.0M   0% /tmp
tmpfs                   100.0M      2.5M     97.5M   3% /run/shm
/dev/mmcblk0p1            1.5G    243.0M      1.2G  17% /mnt/data
/dev/mmcblk0p6           62.0M      5.3M     53.5M   9% /mnt/default
/dev/mmcblk0p10         169.5M    154.2M      6.5M  96% /mnt/updbuf
/dev/mmcblk0p11          15.5M      1.3M     13.4M   9% /mnt/reserve
tmpfs                     5.0M     16.0K      5.0M   0% /mnt/data/rockrobo/rrlog
```

I'm monitoring the robot and will do some tests regarding the next 7 days before sharing the solution.
I've found an efficient (  subtle and elegant )  way to do it :)

**Comment by rand256** [comment]
> i'm almost sure that it's possible to improve the way that the binarie ( arm native ) is done.

Definitely. But as you see in the link you've posted, the pkg dev isn't going to add compression and stripping the binary created by pkg just cuts off valetudo files from it.

> regarding the second question, i've done the job and it's seem to be working :)

Nice to hear!

**Comment by canope-25** [comment]
> > i'm almost sure that it's possible to improve the way that the binarie ( arm native ) is done.
> 
> Definitely. But as you see in the link you've posted, the pkg dev isn't going to add compression and stripping the binary created by pkg just cuts off valetudo files from it.
> 
Maybe i can help, do you have details regarding the custom made zeit pkg you are using for generating the "valetudo" exec for the Gen2 2008 users ?
i would like to build in on my side ( if ok with you) and if you can share with me the way ( or even an archive or ova vm image) you build it.

Thanks in advance

**Comment by rand256** [comment]
You just get a patch from [pkg-fetch](https://github.com/zeit/pkg-fetch) for appropriate version of node.js, apply it to sources and build them normally using any toolchain suitable to your operating system for cross-compiling to arm.

And if you take gcc6 for cross-compiling, you won't need to install additional libs to the device for running the app.

**Comment by Archetrix** [comment]
Have you ever tried to use [UPX](https://github.com/upx/upx) on these binaries? Last time is checked they had arm32 and arm64 support.

**Comment by rand256** [comment]
@Archetrix, yeah, I've tried that a while ago, but it didn't work for me on the pkg-packed executable.

By the way some may have noticed that I've made some changes and the latest release binary size was reduced from around 45MB to 35MB. Though that was the only thing I could do, further shrinking without compression looks impossible to me.

**Comment by zvldz** [comment]
The problem of increasing fs size can now be solved with the key --resize-root-fs=522240 in builder.

**Comment by canope-25** [comment]
> The problem of increasing fs size can now be solved with the key --resize-root-fs=522240 in builder.

To be honest , this is how i solve the problem by myself:

- Mount in read-only the recovery partition
- chroot into it
- use resize2fs to entend the two partition used by the firmware ( the primary and the backup)
- fsck the backup partition

and that's it, it's working perfectly for more than a month :)

**Comment by canope-25** [comment]
> @Archetrix, yeah, I've tried that a while ago, but it didn't work for me on the pkg-packed executable.
> 
> By the way some may have noticed that I've made some changes and the latest release binary size was reduced from around 45MB to 35MB. Though that was the only thing I could do, further shrinking without compression looks impossible to me.

I've noticed the change immediately, but i think the  is still a lot of things that can be done but it will require a lot of work.

you reduced the size of the pkg binary by 4 Mbytes.
the "valetudo" payload seem to have been reduced by 7mbytes.

the size reduction for the binary package seem to only be done trough reduction of the "code" part of the binary.
the data have almost the same size ( a few bytes bigger in 0.9.4).

Actions that can be done to help reduce the size:
- embed the web pages (html/css)  in gzip format ([https://stackoverflow.com/questions/44739374/serve-gzip-html-page-in-node) ](url))
- cleanup the dependencies of unused parts ( like the unused glyphs )
