### ISSUE TITLE
Calibration?

### ISSUE THREAD

**Issue by ThrashinVictim** [rand256/valetudo#223]
I am wanting to add this [card](https://github.com/PiotrMachowski/Lovelace-Xiaomi-Vacuum-Map-card) to my Home assistant. But it requires you to calibrate your map. The problem I am running into is the calibration settings. It requires you to use Mi Home or Flolevacs app. But since I installed Valetudo I cannot add my machine to either.

Is there a way to set Calibration points in Valetudo?

Thank you.

**Comment by rand256** [comment]
I have literally no idea how this whole thing is supposed to work.

As for calibration exactly, you can probably use manual for flolevac then save zone and a set of 3 spots in valetudo, and after that get their coordinates from /mnt/data/valetudo/config.json. But you'll have to recalculate them using [these rules](https://github.com/rand256/valetudo/blob/testing/lib/miio/Vacuum.js#L640) (where DIMENSION_MM is simply 51200) to match roborock input format.

Though, read my first sentence again.

**Comment by ThrashinVictim** [comment]
Thanks for the reply. Think I figured out a way to get it connected.

**Comment by ThrashinVictim** [comment]
Actually found out cant view maps using flolevac if you flashed it to valetudo. So back to the drawing board.
