### ISSUE TITLE
Firmware update not working

### ISSUE THREAD

**Issue by RDSpt** [rand256/valetudo#228]
**Describe the bug**

I'm trying to update the firmware via valuetudo interface, however I receive a 400 error, only being able to update externally

**How to Reproduce**

1. Go to Settings
2. In firmware update click in [send request]
3. Paste direct link to github request

**Expected behavior**

It should update but I receive a 400 error invalid parameter

**Screenshots**

![image](https://user-images.githubusercontent.com/28611644/80864490-eab74700-8c7a-11ea-9e99-708579a7de0d.png)

**Vacuum Model:** 
Gen 1
**Valetudo Version:** 
Currently 0.9.3, but error was present in 0.9.2
**User-Agent** 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
**Additional context**

**Comment by pidator** [comment]
You're probably pasting the link to the md5 hash file instead of the pure md5 hash value like noted in the help section (questionmark)?!

**Comment by RDSpt** [comment]
Well, now I feel dumb. It's exactly that! Thank you.

To any future noob with the same problem:

1. for the pkg use the actual direct link
2. for the md5 download, open it with your editor (I used notepad++) and copy the first part of the file. Eg. **c7f4dc211c73f978554d01c85fb48a37**  vacuum_valetudo_re_4007.pkg <- the bold part

and then wait.
