### ISSUE TITLE
Accessing map data as json with /api/map/latest

### ISSUE THREAD

**Issue by Fynmar91** [rand256/valetudo#233]
Hi, 
I am playing around with valetudo and valetudo RE and I am having trouble with /api/map/latest.
When I call /api/map/latest on valetudo 0.5.1 I get a nice json with x,y coordinates.
Doing the same on 0.8.x or 0.9.x I get a file without ending that doesn't seem to hold useful data. 

Not sure what I am doing wrong. I am probably being stupid. 
Best Regards

**Comment by rand256** [comment]
> Doing the same on 0.8.x or 0.9.x I get a file without ending that doesn't seem to hold useful data.

This "file without encoding" contains all the useful data and takes multiple times less bandwidth.
Some reasoning behind that change was published in changelog for [0.4.0.-RE6](https://github.com/rand256/valetudo/releases/tag/0.4.0-RE6).

**Comment by Fynmar91** [comment]
> 
> 
> > Doing the same on 0.8.x or 0.9.x I get a file without ending that doesn't seem to hold useful data.
> 
> This "file without encoding" contains all the useful data and takes multiple times less bandwidth.
> Some reasoning behind that change was published in changelog for [0.4.0.-RE6](https://github.com/rand256/valetudo/releases/tag/0.4.0-RE6).

**Comment by Fynmar91** [comment]
Thank you for the fast reply. 
*"file without ending"
I am sure it is encoded I just cant figure out how to decode it. I figured it was gzipped, since I read that somewhere, but no luck so far. I can probably find out how to decode it by checking out valetudo-mapper? 
Sorry for the bother

**Comment by rand256** [comment]
Yes, there its content is ungzipped and then put into PARSE() from [RRMapParser.js](https://github.com/rand256/valetudo-mapper/blob/master/lib/RRMapParser.js).

**Comment by Fynmar91** [comment]
Very nice, thanks!
