### ISSUE TITLE
Roborock Gen1 crashes

### ISSUE THREAD

**Issue by UltraSub** [rand256/valetudo#235]
**Roborock S50 crashes at the end of each run**
A few weeks ago I installed Valetudo on my gen1. Up until flashing it worked flawlessly. Since flashing every run fails at the end. The robot just stops, is unreachable and when it's put back in the dock it restarts 10 seconds later, and all is fine. Nothing to be found in logs.
Thought it might be battery, but data shows that it's at ~ 50% if it stops sending to mqtt due to the crash. Started with `Valetudo RE 0.9.2` and prebuild pacakage `vacuum_valetudo_re_4007.pkg`, because of the crashes and hoping for a fix I installed `Valetudo RE 0.9.4` but that didn't help.

The robot is vlanned, and has zero internet access. It is only allowed local dns (pihole).
All is working flawlessly until the sudden crash, it has only done 2 completed runs out of 40 runs after flashing.

Did someone experience the same behavior?

**How to Reproduce**
Just starting a run, almost certain guaranteed to fail at around 90% of the run.

**Expected behavior**
No crashes

**Vacuum Model:**
First roborock, Gen1

**Valetudo Version:**
0.9.2

**Comment by rand256** [comment]
> Did someone experience the same behavior?

I believe no one did.

> hoping for a fix I installed Valetudo RE 0.9.4 but that didn't help

It couldn't. Valetudo is GUI, it just runs commands on the device. When cleaning is started, it can do nothing with it. And if device fails during cleaning... You can probably do ssh login to the device and check its RAM usage at 80-85% of cleaning, but I believe all RAM issues were fixed long ago. Also even if it leaks memory, only valetudo itself should be terminated, not the whole system.

I'd suggest to try re-flashing firmware, maybe with different base version. Try 4004 or even 3532 from [vacuumz.info](https://vacuumz.info/download/gen1/).

PS: 

> Roborock S50 crashes at the end of each run
> A few weeks ago I installed Valetudo on my gen1

S50 is gen2.

**Comment by UltraSub** [comment]
> It couldn't. Valetudo is GUI, it just runs commands on the device. When cleaning is started, it can do nothing with it. And if device fails during cleaning... You can probably do ssh login to the device and check its RAM usage at 80-85% of cleaning, but I believe all RAM issues were fixed long ago. Also even if it leaks memory, only valetudo itself should be terminated, not the whole system.

I know. But it adds resource usage on a device that has very limited resources. So that's why I thought to ask if someone has seen the same issue.

> I'd suggest to try re-flashing firmware, maybe with different base version. Try 4004 or even 3532 from [vacuumz.info](https://vacuumz.info/download/gen1/).

That's next on my list for the upcoming weekend indeed.

> PS:
> S50 is gen2.

Oops. I thought it was the gen1 :)

**Comment by pidator** [comment]
>  Started with `Valetudo RE 0.9.2` and prebuild pacakage `vacuum_valetudo_re_4007.pkg`

> > PS:
> > S50 is gen2.
> 
> Oops. I thought it was the gen1 :)

If you own a S50 you're using the wrong prebuild image! You'll need `vacuum_valetudo_re_2008.pkg` for a Gen2 / S50 device!

**Comment by UltraSub** [comment]
I'm running one of the first. Purchased in april 2017. Pretty sure it's a gen1. Confusing names :)

**Comment by pidator** [comment]
```
root@rockrobo:~# cat /mnt/default/device.conf | grep '^model' | cut -f2 -d=
rockrobo.vacuum.v1
```

then you'll have a Gen1 ;)

**Comment by rand256** [comment]
> I know. But it adds resource usage on a device that has very limited resources. So that's why I thought to ask if someone has seen the same issue.

While that's true in general, currently it has quiet minor resource consumption after I moved map parsing from device to clients. Anyway I've never seen vacuum crashing because of valetudo even before.

**Comment by UltraSub** [comment]
> then you'll have a Gen1 ;)

Thanks, confirmed it's a `rockrobo.vacuum.v1`.

> While that's true in general, currently it has quiet minor resource consumption after I moved map parsing from device to clients. Anyway I've never seen vacuum crashing because of valetudo even before.

That's good to hear! Nice work!

But it happened the first full run after flashing, coming from stock firmware. So it must be something in the prebuild image not  cooperating with my robo then. Will try some different ones, or build it myself. Will report back if I find something.

**Comment by pidator** [comment]
I've installed the current prebuild on a Gen1 without any errors, so I can't confirm your experiences. Perhaps you can do a factory reset before flashing the new image, too. To make sure you'll have a "clean" start...

**Comment by UltraSub** [comment]
Tried all prebuilds all the way back to 3570, every time factory resetting before installing. They all do the same, it's a crash just before the run is complete. Will try 3532 today and then I'm calling it a day and replacing it.

**Comment by UltraSub** [comment]
I think it's the battery pack. Might very well be bad luck that it started right after flashing. Pack is at 810 cycles and as we know, after 500-600 you're on borrowed time.

Ordered an S55 for fast replacement and will order a new battery pack for the v1 which can then move to the upper floor if it really was the pack.

**Comment by Hypfer** [comment]
@UltraSub `Pack is at 810 cycles and as we know, after 500-600 you're on borrowed time.`

How do you check that value?

**Comment by thelittlefireman** [comment]
I'm experencing the same issue. Robots crash in a middle of cleaning right after flashing 9.5.0. I believe it's the battery pack. But i'm looking for a way to test it too. Or Maybe it's 002020 firmware ?

**Comment by UltraSub** [comment]
I received the new battery pack a week ago. Will test soon.

> How do you check that value?

I seriously don't know where I've seen that. Maybe I messed up and it was the number of full clean starts.

**Comment by frostnatt** [comment]
I observe similar behavior of my Gen 1 robot i think since 0.9.5. (not sure). Robot just stops in the middle of cleaning process. It is not responsive, even if i press buttons. Putting it back to docking station was the only solution so far. I even started thinking about buying new battery pack. Hmm..
Maybe i should try to rollback to 0.8.x and see what happens.

**Comment by frostnatt** [comment]
With valetudo 0.8.2 installed the robot has the same behavior as described above. It seems to be a battery issue in my case...

**Comment by thelittlefireman** [comment]
For me, that's was the battery too. After changing all is working
