### ISSUE TITLE
[Not an issue] Building notice

### ISSUE THREAD

**Issue by Ubimo** [rand256/valetudo#24]
User "swappers" took the latest firmware 1910, ripped the miio environement (since the chinese developers decided to not let you update the fw over local area network anymore), took the miio environement from 1898 and built a firmware with valetudo. Take a look at the discussion:
https://4pda.ru/forum/index.php?showtopic=881982&view=findpost&p=89473369
And his collection:
https://vacuumz.info/download/gen2/

Is it possible for you to build a firmware based on 1910?

**Comment by rand256** [comment]
Right now I actually see no reason for that: I could be wrong, but it looks like there's almost no changes between 1898 and 1910 except for miio client update and some workaround for mi wireless router bug. All navigational software looks just the same.

If the next update will appear to have more substantial changes, I'll probably try to create firmware image with downgraded miio client for that.

Btw, there's experimental firmware upgrade button in Settings -> Info that was added just to test the ability to upgrade firmware with newer miio versions, when LAN updates are disabled. Unfortunately I have no time to play with it myself now, but it should work I hope. (Note: its interface feedback is a bit unfinished: after entering firmware URL and MD5 hash in the appropriate forms, it is supposed to blindly wait until Power LED on the device will start blinking).

**Comment by Ubimo** [comment]
Thank you for the answer, really appreciate your work. And nice settings. :-)
