### ISSUE TITLE
Feature Request: Update integrated Dropbear to support ed25519 SSH keys

### ISSUE THREAD

**Issue by PirMei** [rand256/valetudo#241]
**Describe the bug**
Adding SSH keys of type ed25519 over the web interface as well as via dustbuilder service does not allow SSH access, resulting in a fallback to password authentication.

**How to Reproduce**
1. Add a ssh-ed25519 public key via the web interface or via dustbuilder service
2. Try to connect via ssh with `ssh -i $ssh_key_in_ed25519_format root@roborock`
3. SSH client falls back to password authentication

**Expected behavior**
SSH ed25519 keys are accepted by the Dropbear SSH server.

**Vacuum Model:** Roborock S5

**Valetudo Version:** RE 0.9.4 

**User-Agent** irrelevant

**Additional context**
Dropbear got support for ed25519 keys with this Pull Request: https://github.com/mkj/dropbear/pull/91
It's not included in an official release yet afaik, but this might be worth to look into in the future.
See also this comment by tripplet: https://github.com/rand256/valetudo/issues/151#issuecomment-596092209_

**Comment by rand256** [comment]
Dropbear is definitely not a part of Valetudo application, and this is not an image builder repository.
I use [vacuumz image builder](https://github.com/zvldz/vacuum) for creating pre-built images, so that is better place to ask.
