### ISSUE TITLE
Broken/Old links on 0.9.5.1

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#242]
Hey @rand256 ,

just for quick note if you missed it:

Wikipage https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware
The "latest" link on this site will link to 0.9.4.

I also did a download of the 2020 with 0.9.5 after you reuploaded the fix to 0.9.5.1.
After rechecking the version after I updated over webgui from 2008 / 0.9.4 it is still on 0.9.5 and not 0.9.5.1. So maybe this is not newest release as well?

EDIT: Maybe I'm wrong with the links and the new version is still 0.9.5

This was the code for my update to 0.9.5.1:

```
/etc/init/S11valetudo stop
cd /mnt/data/valetudo
wget https://github.com/rand256/valetudo/releases/download/0.9.5.1/valetudo.tar.gz
tar xvzf valetudo.tar.gz
rm valetudo.tar.gz
mv valetudo /usr/local/bin/
/etc/init/S11valetudo start
```

![image](https://user-images.githubusercontent.com/17103076/83409421-a99a8a00-a414-11ea-86fa-7af5db2146dc.png)

**Comment by rand256** [comment]
I believe "latest" link should lead to really latest "release". And I've initially marked 0.9.5 as "pre-release" and it looks like it was definitely correct for doing that. But I'm really sorry I wasn't correct in some places in the map code which required those reuploadings...

**Comment by nicedevil007** [comment]
ah ok :) everything is fine with that, was just here to let you know what isn't doing as expected... just in my expectations hehe
