### ISSUE TITLE
Consumables display inconsistency

### ISSUE THREAD

**Issue by pwrsoft** [rand256/valetudo#246]
There is an inconsistency between displaying consumables times in Settings and in Telegram

**How to Reproduce**
1. Go to 'Settings'
2. Click on 'Consumables'
3. Scroll down to 'CONSUMABLES'
4. See the invalid timer's values (as compare to Telegram values - please refer to the screenshots)

**Pre-conditions: setup up 'Telegram Bot' option "Send a massage when one of the consumables expire"**

**Expected behavior**
Expecting those values to be the same in web app and telegram.

**Screenshots**

Telegram:
![зображення](https://user-images.githubusercontent.com/2362805/83567163-d7bdbe00-a529-11ea-9af7-49a0c3fd24ac.png)

Web:
![зображення](https://user-images.githubusercontent.com/2362805/83566997-8ca3ab00-a529-11ea-857f-b2b3671aea5a.png)

**Vacuum Model:** S5
**Valetudo Version:** 0.9.5.2

**Comment by rand256** [comment]
It is a bug in "default" localization. You can temporary workaround it by explicitly setting localization to English (or any other language). Thanks for reporting!
