### ISSUE TITLE
Feature request: edit map

### ISSUE THREAD

**Issue by Stefan592** [rand256/valetudo#247]
Is it possible to edit the map of the robot. I have a big mirror and several ground level windows that mess up the map.

Maybe it would be possible to save the map according to the real boundaries?

![image](https://user-images.githubusercontent.com/14180760/83852717-832a6680-a714-11ea-9fa1-f02548f4e9b8.png)

**Comment by rand256** [comment]
As far as I know nobody has managed to figure out how to edit map files.

Also I guess even if it was possible, device would redraw those parts of the map on the next cleaning anyway...

**Comment by doguitar** [comment]
I know this is a huge necro so sorry about that but this is where a google search brings me. 

Is it possible to mark the map files as read-only on the vacuum file system to prevent them from being modified by each run?

My maps are usually in a good place at some point but then, over several runs, the room borders get askew and I end up with a lot of strange looking rooms that cause the vacuum to vacuum (for example) the hallway but a pixel of the hallway is now in the office so it drives all the way around to get that last spot. It'd be nice if I could just freeze the map when it was good (and unfreeze when I wanted to make changes. If this is something that's possible, I'll make a new feature request.

<img width="435" height="354" alt="Image" src="https://github.com/user-attachments/assets/73d007ce-ce89-464c-825d-a7d25053a7ef" />

**Comment by rand256** [comment]
>  It'd be nice if I could just freeze the map when it was good (and unfreeze when I wanted to make changes

don't know whether what you're talking about is possible, but in valetudo RE there's an option to do an auto-restore a pre-saved map upon every return to the dock:

<img width="370" height="656" alt="Image" src="https://github.com/user-attachments/assets/68c17438-3f61-417d-8f2d-c0c57ee08abc" />

as far as i recall, that was made by someone's request for a similar reason.
though your screenshot makes me think you're probably using not valetudo RE but the original valetudo.

**Comment by stefanmd023** [comment]
Haha it's a wonder there aren't more people banned by Hypfer that end up posting here instead
