### ISSUE TITLE
Other way to install update

### ISSUE THREAD

**Issue by HHenning0815** [rand256/valetudo#250]
Hello,

i have 0.9.3 on my robo.
I tried to install update to 0.9.5 4007 with win mirobo 1.1.0 - says firmware is transfered and installed (in under a second) - but nothing happens.
With rrcc 0.8.8 (on win and mac) it says that the robo not answers on point where firmware is sent...
Is there any other chance to get it on robo?

**Comment by james-99** [comment]
I've just followed the instructions on the [Wiki Updating-valetudo-binary-on-2008-firmware ](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) page using an android ssh app.

Pre prepare the script with the correct url and once connected paste the prepared text in the command line.
It'll download the files so may take a few seconds to complete. Just make sure the last line is executed.

**Comment by rand256** [comment]
Manufacturer in newer firmware disabled the possibility to install fw images using the old ways.

So you need either to do a manual factory reset to downgrade to older firmware first and then install using update with mirobo etc. Or you may use Settings->Info->Firmware Update to install fw via valetudo RE.

**Comment by liamrpowell** [comment]
Hello, I tried the Settings->Info->Firmware Update to install fw via valetudo RE. and pointed it to the pkg and the md5 (newest version) but it gave a 400 error when updating. I have a S5 that already has Valetudo. 

So I also read the  https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware and did that and it worked well. Is there a benefit to the 2020 firmware over the 2008?

**Comment by rand256** [comment]
>  and pointed it to the pkg and the md5 (newest version) but it gave a 400 error when updating

In most cases that's because you didn't read what exactly it asked to supply.

> Is there a benefit to the 2020 firmware over the 2008?

I personally couldn't find a difference. Maybe some unevident bugfixes.

**Comment by HHenning0815** [comment]
> I've just followed the instructions on the [Wiki Updating-valetudo-binary-on-2008-firmware ](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) page using an android ssh app.
> 
> Pre prepare the script with the correct url and once connected paste the prepared text in the command line.
> It'll download the files so may take a few seconds to complete. Just make sure the last line is executed.

Thanks you for answer - I get error:
root@rockrobo:/mnt/data/valetudo# wget https://github.com/rand256/valetudo/releases/download/0.9.5.2/vacuum_4007_valetudo_re_0_9_5.pkg
--2020-06-11 06:18:51--  https://github.com/rand256/valetudo/releases/download/0.9.5.2/vacuum_4007_valetudo_re_0_9_5.pkg
Resolving github.com (github.com)... failed: Name or service not known.
wget: unable to resolve host address 'github.com'

It has dhcp address from router and should have valid dns configuration - how can I check on device what this problem is?

**Comment by james-99** [comment]
> > I've just followed the instructions on the [Wiki Updating-valetudo-binary-on-2008-firmware ](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) page using an android ssh app.
> > Pre prepare the script with the correct url and once connected paste the prepared text in the command line.
> > It'll download the files so may take a few seconds to complete. Just make sure the last line is executed.
> 
> Thanks you for answer - I get error:
> root@rockrobo:/mnt/data/valetudo# wget https://github.com/rand256/valetudo/releases/download/0.9.5.2/vacuum_4007_valetudo_re_0_9_5.pkg
> --2020-06-11 06:18:51-- https://github.com/rand256/valetudo/releases/download/0.9.5.2/vacuum_4007_valetudo_re_0_9_5.pkg
> Resolving github.com (github.com)... failed: Name or service not known.
> wget: unable to resolve host address 'github.com'
> 
> It has dhcp address from router and should have valid dns configuration - how can I check on device what this problem is?

Not sure about the error but aren't trying to download the wrong file?
You need the tar.gz file.
https://github.com/rand256/valetudo/releases/latest/download/valetudo.tar.gz

**Comment by HHenning0815** [comment]
Hello an thank you very much - this works perfect!
