### ISSUE TITLE
Feature Request: Room numbers/names in MQTT

### ISSUE THREAD

**Issue by povlhp** [rand256/valetudo#252]
Can we please get the room names/numbers in MQTT ? 
Like the data we can get with "miio protocol call 192.168.1.70 get_room_mapping"
Would rather make something in Home Assistant that is dynamic based on this, than hardwire the miio result in my code. Or have "app_segment_clean" accept names

**Comment by rand256** [comment]
Custom command "segmented_cleanup" already accept both names and ids.

Payload example (taken directly from source code):

```
{
  "command": "segmented_cleanup",
  "segment_ids": [
 	 16,
 	 "Room Name 1",
 	 18
  ],
  "repeats": 1
}
```

**Comment by povlhp** [comment]
Great, then I can close this. 
Now I just want a property where I can see what room it is currently in :-)
