### ISSUE TITLE
[Feature Request] Option in the settings for slowing down the driving speed when room changes

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#256]
I have the problem that some rooms have a small "stair" of 1cm (tiles) between them. The robot now drives with full speed over that "stair". That does not only hurt the robot, me too! So it would be nice to slow down the driving to a maximum speed of let's say 10% when it drives over that border line in the map.

**Comment by rand256** [comment]
I'm almost sure this can't be done dynamically. I can image the robot speed could possibly be changed by patching _something_ in manufacturer's binaries, but even then it definitely will be a permanent change - not something you can quickly turn on and off. Also, valetudo isn't patching native apps, that's what some image builders do.
