### ISSUE TITLE
Feature request: allow default tab to be the map and allow PWA page to be consistent with that setting

### ISSUE THREAD

**Issue by teixeluis** [rand256/valetudo#257]
**Describe the bug**

Today even if we first point the browser to the map tab in an Android device running Chrome, when we setup the  page as a Progressive Webapp, it will always open on the home tab. 

Inspecting the manifest file, as expected, it doesn't include any of these tab related anchor links. Looking at the manifest.json file:

`{
  "short_name": "Mi Robot Vacuum",
  "name": "Mi Robot Vacuum",
  "start_url": "/index.html",
  "icons": [
    {
      "src": "icon.png",
      "sizes": "192x192",
      "type": "image/png"
    }
  ],
  "display": "standalone",
  "orientation": "portrait"
}`

It would however be interesting to either have the option (as a configuration setting) to select another tab as the initial tab (and have this reflected in the PWA), or have the manifest include the correct URL depending on the current anchor.

In situations where we would launch a PWA automatically (e.g. in a kiosk) it would be interesting to land straight into to the map instead of the home tab. It is not possible to change the URL of the PWA, as the PWA configuration (including the URL in the manifest.json) is signed with a key.

**How to Reproduce**
Create PWA in Chrome on Android

**Expected behavior**

Possibility of landing on the map when opening.

**Screenshots**

**Vacuum Model:** 

Gen1

**Valetudo Version:** 

0.9.2

**User-Agent** 

**Additional context**

**Comment by rand256** [comment]
Looks like it would be enough to simply remove "start_url" key from the manifest.json to be able to create shortcut to currently opened tab. I'll change that in the next release.
