### ISSUE TITLE
Telegram bot in a group shows client as undefined

### ISSUE THREAD

**Issue by gerard33** [rand256/valetudo#258]
**Describe the bug**
First of all thanks for this fantastic piece of software. Was a bit reluctant to put the software on the robot, but after a bit of reading I found out that it was really easy and I am very happy to have done it. I am now even using more functions than with the standard Xiaomi software like zones, spots because it's so easy to configure via the web interface and also the live map in Home Assistant is great 😄. And no data sent to China 👍 

The Telegram bot is also brilliant. I have one tiny remark for this part though which hopefully can be improved.
I have put the bot in a group which works great. In Settings - Telegram Bot the Telegram client for the group is called `undefined`. Is it possible to use the name of the group here, with addition that it's a group?

**How to Reproduce**
- Add the Telegram bot to a group
- Set the password from the group (if applicable)
- Go to Settings - Telegram Bot

**Expected behavior**
The name of the group (including that it's a group) is shown.
From the Telegram Bot API [documentation](https://core.telegram.org/bots/api#chat) this should be:
`title` for the name of the group and
`type: "group"` to see that it's a group.

And for a authorized user currently the `first_name` is shown. Maybe good to also add the `username` there as well to make it fully clear who is authorized.

**Screenshots**

![telegram-bot](https://user-images.githubusercontent.com/11230573/84953867-9e25af00-b0f4-11ea-881b-4be5269fd80d.png)

**Vacuum Model:** 
S5

**Valetudo Version:** 
0.9.5.2

**User-Agent** 
Applies to all user-agents.

**Additional context**

**Comment by rand256** [comment]
This is because of telegrambot initially was meant to be used in private chats only. But if I understand correctly it can be easily fixed. I've created a [test build](https://erinome.net/valetudo-0.9.5-20200618.tar.gz) including the necessary changes, could you test it to see if it shows all your authorized clients properly now?

There's [a guide](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) on how to quickly replace valetudo binary on 2008+ firmware.

**Comment by gerard33** [comment]
Thanks for the quick reply.

~~I was updating following the guide, but after a succesful wget and when I just wanted to start the tar command, the SSH connection failed with `Network error: Network error: Software caused connection abort`.~~

~~I have tried to reconnect via Putty, that worked for a few seconds but now I don't even get the login prompt.
Any idea how to fix this?~~
Connection is up again, trying to update the firmware now. 

Edit: updating the firmware worked. Connection via Putty was lost a couple of times after a short period, but managed to update the firmware in a few steps and trying to enter the commands as quickly as possible 😅

**Comment by gerard33** [comment]
The clients are shown properly now. The group symbol is also nice!

![telegram-bot-new](https://user-images.githubusercontent.com/11230573/85056276-3e381280-b19f-11ea-83a5-9645de47e037.png)

Thanks for the quick fix 👍
