### ISSUE TITLE
S50 does not resume after low battery

### ISSUE THREAD

**Issue by Krazy998** [rand256/valetudo#260]
**Describe the bug**

S50 robot running 1898 does not resume after recharging and valetudo commands are unresponsive once back on the dock after a low battery recharge.

Reboot of the robot fixes the issues, until next time it goes back to the dock after hitting low battery.

**How to Reproduce**

Basically robot cleans 3/4 of the house then hits 20% battery left and goes back to the dock to recharge. I can see the finished flag is not set. Robot basically is stuck in charging mode even once at 100%. I cannot manually tell the robot to do anything once its back at the dock. If i issue any cleaning commads to it. it just ignores them.

**Expected behavior**

Once robot hits 80-100% charge resume and clean left over parts of map

**Screenshots**

**Vacuum Model:** 

S50

**Valetudo Version:** 

0.9.5.2

I am running Version 1898 and valetudo 0.9.5.2. Reason Why im not using 2008 is because of the change in vacuuming behaviour which randomly just does half the house and thinks it done.

**Comment by rand256** [comment]
Are you sure that in stock firmware it acts better on your hardware?

**Comment by Krazy998** [comment]
Thanks for responding. Yes this was not an issue before. I think the last time i think it worked was around valetudo 9.0.

I think it might have something to do with the robot going back to the dock after a low battery state. As once it does that valetudo just shows a charging state and none of the commands in valetudo work (e.g spot clean or goto..)

Its like there is a status mismatch between valetudo and the robot.

Sending the robot back to the dock via valetudo works fine and I am able to control it afterwards as well.

**Comment by Krazy998** [comment]
Heres some images of whats occuring. Logs dont seem to show anything. But as you can see its 100% charged but the clean buttons etc are all greyed out. Pausing does nothing and its just stuck like that until i restart.


![stuck-charging](https://user-images.githubusercontent.com/47444724/86084303-d7d8bb80-badf-11ea-8634-b045bfdb38ad.png)


![stuck-chargin2](https://user-images.githubusercontent.com/47444724/86084312-deffc980-badf-11ea-852f-0e7b5cfc3d3d.png)

**Comment by rand256** [comment]
Could you please show what is being printed at http://your_robot_ip/api/current_status when this happens?

**Comment by Krazy998** [comment]
bugger i just rebooted the robot to recover it. Will run a full run again tomorrow and reproduce the issue and send you what happens.

Thanks!

**Comment by rand256** [comment]
> Yes this was not an issue before. I think the last time i think it worked was around valetudo 9.0.

Also you should understand that valetudo is a Web GUI for base firmware - it doesn't alter the behavior of the available commands and how they are being run, it just composites them in the desirable sequence. The "return-to-base-at-20%-wait-for-charge-and-continue" is a functionality of the base firmware that can't be changed or disabled without patching base firmware files which valetudo doesn't do. I'm almost certain that if you replace your current valetudo binary with the one from pre-0.9 release - it won't change a thing with the issue you're facing.

Though I guess that in this situation the device reports something like positive "in_cleaning" flag along with "charging" state which wasn't ever supposed to happen, thus you're having most buttons disabled. While this can (and will) be fixed, valetudo however will be most likely unable to fix the issue that the device doesn't return to cleaning after being fully charged - as that could be done solely by base firmware.

**Comment by Krazy998** [comment]
I think you maybe onto something here. I just realised I maybe had the DND schedule on the wrong way. I wonder if I was starting the robot before the schedule kicked in and it was going back to the dock inside the DND schedule. I have deleted the DND schedule now and see how I go tomorrow!

**Comment by Krazy998** [comment]
Closing this issue! Yes it was a silly DND rule which was between 8-22. I was starting the robot before 8 and it was going low power during the DND schedule and causing the problem.
