### ISSUE TITLE
no update possible (solved with taking the hash value instead of the URL in the WEBGUI)

### ISSUE THREAD

**Issue by cma0815** [rand256/valetudo#262]
HI first of all thank you for all the effort you made for this and it is awesome. 

 i am not able to update the image anymore also on the robot is no dpgk or apt-get so it is not possible to install something else 
i am running -> 

on robo: Model S502 (maybe i installed the wrong image?)

MODEL...........: roborock.vacuum.s5
SERIAL..........: R0018S81505229
PRODUCTION DATE.: April 2018
FIRMWARE........: 3.5.7_002008
BUILD NUMBER....: 2019120503REL
REGION..........: de

i tried to factory reset --> not worked
i tried via venv -> flasher.py from dustcloud reflash the robot --> download ok, no error but no change 
i tried app --> did not worked
i tried valetudo -- web -- not worked

is there a possebility to reflash some how diferent? 
otherwise everything works so far despite of updates i was even able to update the valetudo

**Comment by rand256** [comment]
For updating newer firmware (1910 onwards) to anything modified there are two ways which don't require opening the device and soldering uart into it:

a. Do a manual factory reset - see device manual on how to do that. This rollbacks firmware to initial factory version (presumably pre-1910) and you lose ssh access and all current settings in process, including valetudo. After that the device should create its own wifi spot like at its first launch. Then you can update it the common way. If settings weren't lost, then you didn't performed a factory reset properly.

b. If you have not an ancient version of valetudo RE installed, you should be able to reflash from web settings -> info. It requires reading what is said in notices and then it works most of the time. Anyway stating it just "not worked" isn't very informative to be able to help.

Other ways may not work and depend on the exact build you have currently flashed on your device.

**Comment by cma0815** [comment]
you are so right. 
Sry i did not read the second part correct of the web/gui -> and now i did not give the link of the hash md5 file just the hash and it worked sry for bottering. And thank you for the response
