### ISSUE TITLE
Automatic room splitting rotates the map slightly

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#263]
Is this a bug of valetudo or the firmware (2020)? After the first room cleaning I use the room splitting function and see that it rotates the map a bit. And this looks ugly....

Before splitting
![Pic2](https://user-images.githubusercontent.com/36039152/86530221-1e029600-beb7-11ea-8b54-b77af8d6f511.jpg)
After...
![Pic1](https://user-images.githubusercontent.com/36039152/86530212-16db8800-beb7-11ea-964d-a3bf0a166c26.jpg)

**Comment by rand256** [comment]
Valetudo can't affect on how firmware commands are being performed. You may want to try running a full cleaning instead of a room auto splitting, it will also split the map into rooms in the end, but maybe it'll do it better.

**Comment by v-a-d-e-r** [comment]
I did the splitting after a first full cleaning. And only an automatic splitting can be done. The other buttons for manually do that are disabled in valetudo.
![Pic3](https://user-images.githubusercontent.com/36039152/86535290-9715e380-bedf-11ea-9aa8-d721509595b1.jpg)

**Comment by rand256** [comment]
That's quiet strange - when I've first used 2008 firmware half a year ago it automatically split the map for me at the end of the first full cleaning, right after the device had on its own returned to the dock (that is important IMO). I thought it should work the same way on 2020 too... And the "auto-split" button is shown in valetudo's settings only when there's no already defined rooms on the map.

Anyway, there's nothing to be done with this issue from the valetudo side I believe, as the function called by pressing the "auto-split" button has no parameters and is run by the firmware just as is.

**Comment by v-a-d-e-r** [comment]
I know it was already working in the past. Will check it what the version of valetudo and/or firmware it was....

**Comment by v-a-d-e-r** [comment]
I made a downgrade to FW2008 and valetudo 0.9.1 but with no success (did not reset the map). Can still not select other options than auto-split.

**Comment by rand256** [comment]
>  Can still not select other options than auto-split.

Again, if you have no rooms on the map then only auto-split button will be available. I know only two ways to get initial room splitting: either via auto-split button or by running full cleaning uninterrupted until the device returns back to the dock.

**Comment by v-a-d-e-r** [comment]
Did some research now. I have done a complete cleaning without resetting the map and the room splitting is done automatically now. Result: map rotated => BAD!! Restored the maps I saved before on the PC and it seems all ok now. All walls are straight again (like in the pic below) and the room splitting is also done. :-)
![Pic4](https://user-images.githubusercontent.com/36039152/86582017-4951b780-bf81-11ea-92a9-d08e19b36896.jpg)
