### ISSUE TITLE
Sox/Play instead of  /usr/bin/uart_test

### ISSUE THREAD

**Issue by willchr** [rand256/valetudo#264]
Hi,

I think, it would make sense to integrate the play command of sox for playing sounds after receiving the mqtt-command "play_sound" instead of using just the /usr/bin/uart_test.

I assume that a lot of RE-Users are using or will use the ready-built-firmware with integrated ValetutoRE from zvldz (https://github.com/zvldz/vacuum) or are building / will build their firmware there. And because since fw2008 there is just a cuttedOS inside without the possibiliy of using "apt", Users, who want to play sounds (wavs or mp3 or ..), have to build the image with the sox-parameter or they have to use the prebuiltFirmware from zvldz, where sox is integrated as standard already.

The difference between these 2 players are mp3-Files:  with uart_test it's not possible, with sox it works. 
Regards
Christian

**Comment by rand256** [comment]
Well, okay, I have no sox/aplay on my device and I'm not planning to add any, but it's not hard to call it from the code if it's already installed. As far as I understand, we can run sox preinstalled in vacuumz firmware builder by just running `/usr/bin/sox </path/to/filename> -d`, am I correct?

**Comment by zvldz** [comment]
Yes,  sox is here - /usr/bin/sox

**Comment by rand256** [comment]
I've uploaded [a test build](https://erinome.net/valetudo-0.9.6-20200712.tar.gz) that should call `/usr/bin/sox </path/to/filename> -d` (if it's available) upon receiving `play_sound` mqtt command. Also in this case is now possible to optionally set `volume` parameter which specifies the volume in percents/100, so 1 is the initial loudness and 0.5 is two times quieter.

I still have not test that since I don't have sox installed, but probably it should work.

**Comment by willchr** [comment]
works like a charm, thank you very much!

**Comment by teixeluis** [comment]
I am using Valetudo RE 0.9.8 (just installed a pre-built image using xvacuum) and was able to successfully install sox and lame via apt-get (just did an apt-get update before that) and packages were installed just fine and it plays well (not an a high end bose audio speaker but it does the job).

Could there be any implications down the road from installing packages like this? Can the vacuum watchdog detect this and switch back to the factory firmware?

Thanks

**Comment by rand256** [comment]
Watchdog doesn't detect installation of additional software, so random factory resetting depends only on whether the image builder you've used included "anti-factory-reset" workaround patch or not.

**Comment by teixeluis** [comment]
Thanks for the feedback @Erinome. I used the pkg provided in the release:

https://github.com/rand256/valetudo/releases/download/0.9.8/vacuum_4018_valetudo_re_0_9_8.pkg

I'm guessing it's already patched (?)

Cheers

A sábado, 10/10/2020, 15:05, Erinome <notifications@github.com> escreveu:

**Comment by rand256** [comment]
Yes, it's patched.
