### ISSUE TITLE
return_to_base not possible when in state "cleaning"

### ISSUE THREAD

**Issue by ghost** [rand256/valetudo#266]
I'm using v0.9.6 with Home Assistant and Homekit integration.
I can start the cleaning process via Homekit, which will send the "start" command to start cleaning. Re-pressing the button in Homekit will send the command "return_to_base", which is not working when the vacuum is in "cleaning" state. The vacuum has to be stopped manually, in order for the "return_to_base" command to be working.
Imho this was working before release 0.9.6.

**Comment by rand256** [comment]
Before 0.9.6 it had always implicitly sent "stop" MiIO command upon receiving "return_to_base" MQTT command. But then I've found out that it isn't required and works without it (at least in Gen2 with 2008+ fw). Well, looks like it was not always so.

**Comment by ghost** [comment]
Sorry, forgot to mention that I'm running Valetudo on Gen1.

**Comment by rand256** [comment]
Which firmware version it has exactly?

**Comment by ghost** [comment]
Firmware Version: 004018

**Comment by rand256** [comment]
Okay, I see... It will be fixed.

**Comment by rand256** [comment]
Fixed in 0.9.7.
