### ISSUE TITLE
Checking the manual control mode

### ISSUE THREAD

**Issue by rand256** [rand256/valetudo#271]
I've made an embedded map on manual control tab for some unknown reason. But it seems that determining the direction of the robot in manual control mode isn't working properly for me (simply speaking, device thinks that it rotates all the time). Yes, there's a workaround for this, but it requires using 2008+ firmware and is obviously available only on Gen2.

So, the actual issue is that I'm not sure whether it is exactly my device malfunctioning or it behaves the same way on all devices.

Because of this I'd like to ask valetudo RE users running latest stable release to do a simple check:
1. Open two tabs in your browser: one with Map page and another with Manual control page.
2. Enable Manual control mode and make the device simply stay still.
3. Look at Map page for 5-7 seconds and check if robot icon rotates.
4. Manually drive the vacuum somewhere else and make 1-2 more observations.

Depending on your results, the next release will include manual control tab with embedded map either on Gen2 devices with newer firmware only or it will be available for everyone.

<details><summary>example of how this would look like</summary>

![picture](https://user-images.githubusercontent.com/30267719/88387969-43026e80-cdbc-11ea-8c96-3631fc2f5d5a.png)</details>

Also, I'm interested in user opinions on whether there should be an ability to disable showing the map, or maybe you think it shouldn't be in valetudo RE at all (spoiler: unfortunately, it seems impossible to make map updates really "live", they are always a bit delayed).

**Comment by jdanders** [comment]
I've got 2020 firmware on an S5 and did the above steps. The robot icon did not rotate when I started manual control mode, but after moving it and then stopping again, it does rotate pretty randomly for a little bit, and then settles down. Maybe 5-7 seconds like you say. So step 3: no rotation, step 4: rotation every time for several seconds.

**Comment by rand256** [comment]
Thank you for your reply! Then probably my device isn't completely faulty. Though it doesn't settle down with time and shows imaginary rotations continuously, but in this context it won't change much.

It still would be interesting to see how it's going on Gen1 devices exactly, but I'm afraid I'll have to limit this functionality for Gen2 with 2008+ fw only anyway.

**Comment by pidator** [comment]
> It still would be interesting to see how it's going on Gen1 devices exactly, but I'm afraid I'll have to limit this functionality for Gen2 with 2008+ fw only anyway.

Upgraded today to 0.9.6, will provide the results for Gen1 in the next days!

**Comment by Stramm** [comment]
Tested with a Gen2. When staying on spot the icon is very slowly rotating a few degree every few secs. Moving the vac to another spot and stopping it again shows then the same results.

**Comment by pidator** [comment]
> It still would be interesting to see how it's going on Gen1 devices exactly

Have done the desired tests:
I'm running RE 0.9.6 on a Gen1 with base firmware 4007 and I can't observe any rotations of the icon while manual mode is enabled and the robot keeps staying on a spot! Have done it severals times, moving the robot from spot to spot and the icon on map page always keep it's direction. Sometimes a little "skip", I think to readjust it's position on map, but no rotation!

> Also, I'm interested in user opinions on whether there should be an ability to disable showing the map

imho it would be great to have the ability to choose whether to show the map or to hide it. From time to time it seems to me that I'll need my whole smartphone screen to successfully navigate the robot :D so having half ot the space could be a problem, I don't know ;) On the other hand it could be very usefull to see, where's the robots current position.

**Comment by rand256** [comment]
Well, that's interesting. So it seems that on pre-2008 fw it correctly works only on some devices while on others random rotations can be observed having different intensity levels, that most likely depend on the hardware sample. Okay then, I'll add a new switch in web interface settings and the feature will be available for every device.

Thanks everyone for testing.
