### ISSUE TITLE
No Linux commands

### ISSUE THREAD

**Issue by jbrink90** [rand256/valetudo#273]
Hello. New Roborock S5 owner here. Just flashed vacuum_2020_valetudo_re_0_9_6.pkg, set up my SSH keys and got into the shell just fine. However, when I try to run normal linux commands like apt, dpkg, yum, etc, I get "command not found". Anything I am missing? Thank you.

**Comment by rand256** [comment]
Nope, that's correct: manufacturer have cut "unnecessary" tools from device's OS since base firmware version 2008.
They are physically missing in firmware.

**Comment by jbrink90** [comment]
I see quite a few tutorials out there for installing random things on our robots. Spotify, wifi strength monitors, etc. and a lot of them use apt-get. Have you heard of any way of running apt-get recently?

**Comment by rand256** [comment]
Then probably those tutorials were written before firmware version 2008 release, when there was almost full-featured ubuntu 14.04 installed on the device.

And I'm not aware that someone has successfully ported apt-get to 2008+ fw, but theoretically that might be possible.

**Comment by jbrink90** [comment]
Damn. I was so excited of the possibilities of having a full-fledged Linux vacuum. Thank you for your help!

**Comment by rand256** [comment]
Well, you should be able to easily downgrade to i.e. 1898 as the latest known good working version with full Ubuntu. But then you'll lose the ability to run room cleaning and the device will always clean zones using only one direction (it won't change direction of cleaning based on which side of the zone is larger). Otherwise it will operate almost the same.

**Comment by eeshaan** [comment]
@TheConsciousness 
For Spotify, I'm using [spotifyd](https://github.com/Spotifyd/spotifyd)'s [pre-built ARM binary](https://github.com/Spotifyd/spotifyd/releases/download/v0.2.24/spotifyd-linux-armv6-slim.tar.gz). Hope that helps!
