### ISSUE TITLE
Display error of valetudo systemlog

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#277]
The timestamp of valetudo system log in the Web Gui is clutched in symbols that are not displayed when having a look at the file via ssh:

![log2](https://user-images.githubusercontent.com/59822549/89359816-f9245d00-d6c6-11ea-8f9b-ecd392cafe3e.jpg)

![log1](https://user-images.githubusercontent.com/59822549/89359819-fb86b700-d6c6-11ea-8ddf-89033f0447f3.jpg)

Perhaps the color code?!

**Vacuum Model:** Gen1
**Valetudo Version:** 0.9.7 (4007)

**Comment by rand256** [comment]
Yes, those are the color codes. Will fix it soon, thanks.

**Comment by rand256** [comment]
Fixed in 0.9.8.
