### ISSUE TITLE
How to use play_sound via mqtt?

### ISSUE THREAD

**Issue by thundergreen** [rand256/valetudo#278]
Hi all ..great work  .can someone explain me how to use this feature ?
Thanks in advance

**Comment by rand256** [comment]
You can find example usage i.e. [here](https://github.com/rand256/valetudo/issues/56#issuecomment-646177864) or in comments in MqttClient.js file. It's for sure would be great if someone could write docs for MQTT features specific to RE, but it still hasn't happened AFAIK.

**Comment by Andoramb** [comment]
@thundergreen in HA it goes like this: 
![image](https://user-images.githubusercontent.com/3399628/90000727-cebb3c80-dc90-11ea-99c0-e5177a72eddf.png)

**Comment by thundergreen** [comment]
by trying this I get 

```
[35m2020-08-14T20:32:02.923Z[39m MQTT Error : null : Unable to parse received command

```

**Comment by Andoramb** [comment]
Also @thundergreen are you using the custom fw from zvldz?

**Comment by thundergreen** [comment]
ALL GOOD @Andoramb  typo on my side! .. thanks for your help

**Comment by Progaros** [comment]
`topic: valetudo/rockrobo/custom_command`
`payload: "{ \"command\": \"play_sound\", \"file\": \"/root/bell.mp3\" }"`
When I use this command in home assistant nothing happens.

However if I change the file name to something else the valetudo log says:
`MQTT Error : play_sound : File not specified or doesn't exist.`

**Comment by rand256** [comment]
Default player supports only wav files.

If you want to play mp3 you need to either build firmware yourself and enable sox player in it, or use pre-built image from https://vacuumz.info/download/, where player is enabled in default configuration.

**Comment by Progaros** [comment]
Thanks!

**Comment by kasitoru** [comment]
How do I stop playback?

**Comment by rand256** [comment]
Use "none" as a file value.

**Comment by avdeevsv91** [comment]
But it doesn't work for sox player (location: ...)
