### ISSUE TITLE
valetudo mapper crop RangeError

### ISSUE THREAD

**Issue by adamchengtkc** [rand256/valetudo#279]
Valetudo v0.9.7
valetudo mapper (latest from Docker hub)

I use the example config. Valetudo mapper returns error on: methodName: 'crop'. I have also tried setting all crop parameters to 0
**How to Reproduce**

**Expected behavior**

**Screenshots**

**Vacuum Model:** 
Gen 1 
**Valetudo Version:** 
v0.9.7
**User-Agent** 

**Additional context**

Full log
https://pastebin.com/HFs6FAeL

**Comment by rand256** [comment]
Is the provided log made with default config (no crop values set)? If so I'd guess you have a broken map received from MQTT.

**Comment by rand256** [comment]
Though maybe your Gen 1 has map erased and this breaks the mapper. I'll take a look.

**Comment by adamchengtkc** [comment]
Yes no crop value set. The same error log with and without crop set. I can see from MQTT that the map is sent as binary from the Gen 1

**Comment by rand256** [comment]
Please try running a newer build. Though even the older build should work if you make the vacuum generate some meaningful map data to stop the map image being empty.

**Comment by adamchengtkc** [comment]
The newer build apparently doesn't get any data from the Gen 1. Logs only shows connected to MQTT server. I have checked the Gen 1 is still sending binary data

**Comment by rand256** [comment]
The newer build just shouldn't throw errors when there's no map image packed into binary data the device is sending.

The next question is why you don't seem to have that map image, obviously. Do you actually see the map in valetudo's web interface? Which mqtt broker do you use?

**Comment by adamchengtkc** [comment]
Thanks for clarifying. I can see the map in web interface. Broker is eclipse Mosquitto

**Comment by adamchengtkc** [comment]
My config https://pastebin.com/Fe7X5rJL

**Comment by adamchengtkc** [comment]
Solved. turns out I need to finish a full clean up first or the error keeps popping up
