### ISSUE TITLE
[FR] Hass.io addon for valetudo-mapper

### ISSUE THREAD

**Issue by oechslein** [rand256/valetudo#28]
Any chance that you will create an own Hass.io for valetudo-mapper (like https://github.com/Poeschl/Hassio-Addons/tree/master/ICantBelieveItsNotValetudo)?

**Comment by rand256** [comment]
I'm not using Hass.io and don't know how addons are cooked there. However as I see in the link you've provided it seems to just download icantbelieveitsnotvaletudo and runs it in docker with specified parameters. So, if you'll take that project and replace a github link from icantbelieveitsnotvaletudo's repository to valetudo-mapper's one and check names, then probably you may get what you need.

**Comment by oechslein** [comment]
Thanks, I will create then my own repository.
