### ISSUE TITLE
Gen1: Return to dock in paused state not possible

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#280]
If my robot has reached a target point or if I pause a zoned cleaning, I can't send the robot back to the dock with the button on home tab. 

Here's the output of /api/current_status in these situations:

paused zoned cleaning: `{"msg_ver":8,"state":3,"battery":100,"clean_time":0,"clean_area":240000,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":1,"human_state":"Idle","human_error":"No error","model":"rockrobo.vacuum.v1"}`

robot at target point: `{"msg_ver":8,"state":3,"battery":100,"clean_time":0,"clean_area":240000,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":1,"human_state":"Idle","human_error":"No error","model":"rockrobo.vacuum.v1"}`

**Vacuum Model:** Gen1
**Valetudo Version:** 0.9.7 (4007)

**Comment by rand256** [comment]
Err.. Do you mean it just doesn't react on pressing that button?

Btw I guess paused cleaning should have state=10, so most likely the data from current_status should be different. It doesn't matter much in this exact case, though.

**Comment by pidator** [comment]
> Err.. Do you mean it just doesn't react on pressing that button?

yes, no reaction at all after pressing the return to dock button.
 
> Btw I guess paused cleaning should have state=10, so most likely the data from current_status should be different. 

I think I've stoppped/paused the zoned cleaning on the way to the zone. So the "cleaning" hasen't started yet.

**Comment by rand256** [comment]
Could you please try [this build](https://erinome.net/valetudo-0.9.8beta0.tar.gz)?

**Comment by pidator** [comment]
> Could you please try [this build](https://erinome.net/valetudo-0.9.8beta0.tar.gz)?

It's working! Great, thanks!

**Comment by rand256** [comment]
Glad to hear. I think I'll release this in a next few days as a final 0.9.8 if no more issues appears.

**Comment by pidator** [comment]
I will send you an PR for updated german translations in the next days too, perhaps this could still be integrated in 0.9.8.
I'll close this issue here.
