### ISSUE TITLE
How to safe maps in 0.9.7

### ISSUE THREAD

**Issue by MatttiH** [rand256/valetudo#281]
I am searching for a way to save a map to use it for the experimental map restore feature.
I am not able to find it in the gui 0.9.7 
Could anybody give me a hint how to do it?

Thank you
 Matti

**Comment by pidator** [comment]
Enable the Multi-Map-Buttons in Settings/Web Interface

![map1](https://user-images.githubusercontent.com/59822549/90013353-662a8a80-dca5-11ea-8dc8-3022cdf462fe.jpg)

to have the buttons for saving and loading the maps on home tab

![map2](https://user-images.githubusercontent.com/59822549/90013358-67f44e00-dca5-11ea-8e84-d35543d94092.jpg)

**Comment by MatttiH** [comment]
Thank you, I was just blind.
