### ISSUE TITLE
MQTT No Map data published

### ISSUE THREAD

**Issue by MrSolo570** [rand256/valetudo#283]
Hello,

I successfully installed v.0.9.7 on my gen1 vacuum.
In Home Assistant I can read status and attribute messages when I listen to the topic valetudo/pitbull2/# but I dont see any map_data_parsed.
I enabled it in settings, this is what my config.json looks like:

`  "spots": [],
  "areas": [],
  "ztimers": [],
  "mqtt": {
    "enabled": true,
    "identifier": "pitbull2",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://acc:pass@192.168.188.45",
    "provideMapData": true,
    "caPath": ""
  },
  "dummycloud": {
    "spoofedIP": "203.0.113.1",
    "bindIP": "127.0.0.1"`

I have a second gen1 device with valetudo re running and everything works fine there. So where is my mistake?

**Comment by rand256** [comment]
Probably that's because map_data_parsed is generated by standalone valetudo-mapper?
