### ISSUE TITLE
Web API "Go to spot" does not work

### ISSUE THREAD

**Issue by WonderDoge** [rand256/valetudo#287]
**When clicking on "Go to" in the web API and choosing a predefined spot, the web API switches to map view, but the vacuum doesn't do anything. This happens when on dock, but also when not on dock. "Go to" command works perfectly from Telegram.**

**How to Reproduce**
1. In Web API, Zones: Define spot.
2. In Web API, Home: Click "Go to", choose spot.
3. Web API switches to map.
4. Nothing happens.

**Expected behavior**
The vacuum should announce the action and go to the chosen spot. Both does not happen.

**Vacuum Model:** Gen2 S5

**Valetudo Version:** RE 0.9.8

**User-Agent** Firefox Browser 79.0 AND Safari 13.1.2, both on macOS Catalina 10.15.6

**Additional context**
I just recently discovered your Fork. It's awesome! The telegram integration is wonderful. Thank you for your work!

**A humble suggestion**
It would be great to have the option to send the vacuum to a specific spot on a schedule. No cleaning like on the already implemented schedule, but just go somewhere, e.g. all to weeks or after a specific clean up. The idea behind it is, that the vacuum goes to "the garbage dump" when full - users have to determine the interval themselves; for me it's about every two weeks, but I forget it often and then the cleaning results are quite bad. So every two weeks (or after a specific clean up) the vacuum would go to that spot (preferably next to the garbage) and would wait until the user sees, empties and sends it back to the dock. This way, users would have an obvious reminder to empty their vacuum. Many thanks for your consideration!

**Comment by pidator** [comment]
That's intended to be like this. If you want the action to be performed directly, you'll have to enable it in settings/webinterface:

![settings](https://user-images.githubusercontent.com/59822549/90595304-d0cf4f00-e1ec-11ea-93af-c4ee23cc5c75.jpg)

**Comment by WonderDoge** [comment]
Well, kind Lady or Sir, I'm an idiot. I'm sorry to have wasted your time and will close the issue...
