### ISSUE TITLE
[not an issue] Pre-built firmware with 0.4.0-RE6?

### ISSUE THREAD

**Issue by Ubimo** [rand256/valetudo#29]
Hello rand256
Can you please also provide a pre-built firmware based on v1898 with Valetudo 0.4.0-RE6 preview?
Thanks!
Best wishes

**Comment by rand256** [comment]
Did the previous pre-built image work OK for you? I decided not to build images this time because there were some AP issues reported in #26, so I wasn't completely sure that those images were correct (though there's no reason for them to be broken actually, but still).

**Comment by Ubimo** [comment]
Yes, previous images worked fine, I also flashed it over the "old" firmware. My S5 connected to my wifi without problems. I understand now.
