### ISSUE TITLE
MQTT "go_to" commands not matching spot_id any more

### ISSUE THREAD

**Issue by jdanders** [rand256/valetudo#290]
My MQTT go_to commands from Home Assistant don't work any more after upgrading 0.9.6 to 0.9.8.

**How to Reproduce**
1. Send MQTT command
2. Check response

* For example (snooped by subscribing to topic): 
```
{"command": "go_to", "spot_id": ["Garbage"]}`
{"command":"go_to","message":null,"error":"Invalid spot_id","updated":1598647414072}
```

**Expected behavior**

The robot should have gone where I said.

Other cleaning commands still work:
```
{"command": "segmented_cleanup", "segment_ids": ["Living Room"]}
{"command":"segmented_cleanup","message":["ok"],"error":null,"updated":1598647938428}
```

**Settings info**
My Goto Settings:
![Screenshot_2020-08-28_14-50-20](https://user-images.githubusercontent.com/15146675/91613989-dee44480-e93d-11ea-88a9-fd3d1a192fcb.png)

Start of config.json:
```json
{
  "spots": [
    [
      "Garbage",
      21890,
      15865
    ],
 ```

This spot works when I command it through the self-hosted webpage.

**Vacuum Model:** 
S5

**Valetudo Version:** 
Upgraded from 0.9.6 to 0.9.8

**Comment by rand256** [comment]
That's because you send your "spot_id" value as an array with a single element and it is supposed to receive just a string instead.

**Comment by jdanders** [comment]
That fixed it, thanks! I could have sworn it worked last time I tried it...

**Comment by rand256** [comment]
There were no changes in the corresponding code for at least a year.
