### ISSUE TITLE
Stop button on home tab not working while returning to dock

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#291]
While returning to dock the stop button on home tab is not working. After pushing the button, nothing happens. 

State of robot while trying to push stop:
`{"msg_ver":8,"state":6,"battery":90,"clean_time":884,"clean_area":15217500,"error_code":0,"map_present":1,"in_cleaning":0,"fan_power":60,"dnd_enabled":0,"human_state":"Returning to dock","human_error":"No error","model":"rockrobo.vacuum.v1"}`

**Vacuum Model:** Gen1
**Valetudo Version:** 0.9.8 (4018)

**Comment by pidator** [comment]
hm, I can't start a new zoned cleaning while the robot is returing to dock neither. I had to "pause" the movement first, then start the new zoned cleaning run. Is it intend to be like this?

**Comment by rand256** [comment]
> Is it intend to be like this?

The thing is it works fine without additional "pausing" on Gen2 devices with current 2xxx firmware and I'm not sure about other devices. Could you check [this build](https://gv.erinome.net/valetudo-0.9.8-20200903.tar.gz) for the mentioned above stopping and zone-cleaning while returning to dock? Now it should automatically call pause before in this case.

Also it'd be great if you will check other scenarios that may require additional preliminary actions on the device.

**Comment by pidator** [comment]
> Could you check [this build](https://gv.erinome.net/valetudo-0.9.8-20200903.tar.gz) for the mentioned above stopping and zone-cleaning while returning to dock?

I will do and I will also test this build in daily use.

**Comment by Stramm** [comment]
It's working... 
when on the map I can press the pause button. I hoped for a stop button to pop up but it didn't. After switching to the home screen hitting the stop button ended the way home for the roborock. 
For me it's working as it is. Nevertheless it could be more comfortable like stopping without the need to press pause before or pause and an appearing stop button.
Thanks for the additon,
Thomas

**Comment by pidator** [comment]
> Could you check [this build](https://gv.erinome.net/valetudo-0.9.8-20200903.tar.gz) for the mentioned above stopping and zone-cleaning while returning to dock? Now it should automatically call pause before in this case.

With the test build the two situations are working now!

> Also it'd be great if you will check other scenarios that may require additional preliminary actions on the device.

It seems the queuing is not working for Gen1. E.g. I cannot add a new zone while cleaning an other one. After finishing the current zone, the robot returns to dock with status "cleaning finished". This is one result I can say about my tests so far.

**Edit:** The issue https://github.com/rand256/valetudo/issues/298 is probably related to this one.

**Comment by rand256** [comment]
> Edit: The issue 298 is probably related to this one.

I've replied there since that looks like more appropriate place for enqueuing issue.

**Comment by pidator** [comment]
I didn't notice any further issues with my Gen1 in the daily use so far. I will close this issue as resolved and will open a new one if there's an other issue ;)
