### ISSUE TITLE
Does not resume cleaning after recharging

### ISSUE THREAD

**Issue by xTopher1049** [rand256/valetudo#293]
![Screenshot_20200830-201801](https://user-images.githubusercontent.com/66655530/91680349-edd31e80-eb18-11ea-95fc-136497b66ed8.png)

**Describe the bug**
If the vacuum gets to low battery before finishing cleaning, and returns to dock, it does not auto resume cleaning once recharged.

**How to Reproduce**
1. Have vacuum clean
2. Vacuum reaches <20% soc
3. Vacuum recharges to 100%
4. Vacuum does not resume cleaning

**Expected behavior**

After recharging, vacuum resumes cleaning automatically.

**Vacuum Model:** <gen1

**Valetudo Version:** 0.9.8

**User-Agent** 

**Additional context**
 If I manually resume the vacuum it works

**Comment by rand256** [comment]
Ask roborock since it is their blackbox-like firmware that should do an auto-resume. Though valetudo probably can be programmed to send another "start" command again when device is getting fully charged, but technically it won't be anyway different from you doing it manually. Thus this is roborock's failure.

**Comment by xTopher1049** [comment]
Your comment got me thinking... I had to do a full factory reset to base firmware in order to install valetudo since my vac was on latest roborock/xiaomi firmware which blocked unofficial updates. This older roborock/xiaomi firmware could likely have bugs like this, right?

Is there anyway to update the roborock firmware to a later build which has bug fixes?

I also noticed that it never finishes "charging" to "charged". It stayed on the charger all night and still says "charging". I think this is old vac firmware bug?

![Screenshot_20200831-070226](https://user-images.githubusercontent.com/66655530/91714513-ef710680-eb59-11ea-9ec5-eedf00ac6128.png)

**Comment by rand256** [comment]
> This older roborock/xiaomi firmware could likely have bugs like this, right?

Maybe. Or maybe not. I don't know, really.

> Is there anyway to update the roborock firmware to a later build which has bug fixes?

When you install valetudo in the pre-built image, you get the full firmware specified in that image name installed.

**Comment by rand256** [comment]
> I also noticed that it never finishes "charging" to "charged". It stayed on the charger all night and still says "charging". I think this is old vac firmware bug?

Nope, it's just roborock didn't care to provide a separate state for a completely charged device, so when vacuum is on the dock, it is _always_ charging.

**Comment by Krazy998** [comment]
I had a similar issue. Basically robot started before DND schedules kicked in. DND schedule kicked in during cleaning. This meant that robot was unable to go back and finish the cleaning. Double check you dont have any Do Not Disturb schedules set.

**Comment by pidator** [comment]
>Double check you dont have any Do Not Disturb schedules set.

And afaik a DND Timer is enabled by default!

**Comment by mamartins** [comment]
Here today something even more strange happened.

When the battery reached 20% the robot went to the dock - it took 20 min to reach the dock! When it recharged up to 80% apparently it started a new full clean, when the battery reached 20% it went back to the dock and again and at 80% I believe it went to clean the missing room.

I can only say apparently as the web view only has the map and status from the first clean, but by the notifications I get on the Telegram I am inferring the rest as on the second run the robot clean to the dock after 1 hour again. Is there a way to check a log or the other maps to confirm this?

Thank you!
