### ISSUE TITLE
Firmware update via Web UI overwrite ssh authorized key and password

### ISSUE THREAD

**Issue by Sebclem** [rand256/valetudo#295]
**Describe the bug**

Firmware update via Web UI overwrite ssh authorized key and password

**How to Reproduce**

**Expected behavior**

I don't know if it's possible, but it can be great to keep the ssh authorized key and password as before the update

**Screenshots**

**Vacuum Model:** 
S5
**Valetudo Version:** 
0.9.7 => 0.9.8
**User-Agent** 

**Additional context**

**Comment by rand256** [comment]
Most likely it's impossible. Firmware update via Web UI just launches stock firmware update procedure using the specified image, so to re-add keys or passwords they need to be integrated into it.

**Comment by pidator** [comment]
Firmwareupdate is flashing a whole firmware file, like you've done to root the robot. So if you want to keep this settings, just include them while building the firmware?!

**edit** sry for double answering, @rand256 was a little bit faster ;)

**Comment by Sebclem** [comment]
> Most likely it's impossible. Firmware update via Web UI just launches stock firmware update procedure using the specified image, so to re-add keys or passwords they need to be integrated into it.

I was expecting this. 

Nevermind I will just update the wget + tar method. 

Thanks 😊

**Comment by pidator** [comment]
> Nevermind I will just update the wget + tar method.

You a aware of the fact, that Firmwareupdates (whole roborock software) and Valetudo updates are quite different things?!

**Comment by Sebclem** [comment]
Yes yes of course. 

It was just more easy for me to update it via the webpage this time.
