### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by vertexodessa** [rand256/valetudo#296]
**Describe the bug**

Not able to build, node is not downloaded

**How to Reproduce**

npm run build

**Expected behavior**

builds properly

**Screenshots**

**Vacuum Model:** 
not applicable

**Valetudo Version:** 
master branch

**User-Agent** 

**Additional context**

> valetudo-re@0.9.8 prebuild /opt/build/valetudo
> cp -a client client.b && find client/ -type f \( -iname \*.json -o -iname \*.js -o -iname \*.html -o -iname \*.css \) -exec gzip -9 {} +

> valetudo-re@0.9.8 build /opt/build/valetudo
> pkg --targets node12.16.1-linux-armv7 --no-bytecode --options max-old-space-size=32,optimize_for_size --public-packages=prettycron . --output valetudo || npm run postbuild

> pkg@4.4.9
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v12.16.1-linux-armv7 [                    ] 0%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.16.1-linux-armv7
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.16.1-linux-armv7"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.16.1-linux-armv7"}
> Building base binary from source:
  built-v12.16.1-linux-armv7
> Error! Not able to build for 'armv7' here, only for 'x64'

> valetudo-re@0.9.8 postbuild /opt/build/valetudo
> if [ -d client.b ]; then rm -fr client && mv client.b client; fi

> valetudo-re@0.9.8 postbuild /opt/build/valetudo
> if [ -d client.b ]; then rm -fr client && mv client.b client; fi

**Comment by rand256** [comment]
You need either build patched node binary yourself or download [this one](https://github.com/rand256/valetudo/releases/tag/pkg-12.16.2).
