### ISSUE TITLE
[feature request] Ignore virtual walls for selected zoned cleaning possible?

### ISSUE THREAD

**Issue by jneuhauser** [rand256/valetudo#299]
Hey there,

does anybody know if it's possible to ignore virtual walls for cleaning a specific zone?

I'm right that this isn't implementable in valetudo re as this has to be implemented in the roborock firmware?

My use case is to clean the full flat except the room of my kid, but if i want to clean the kids room the vacuum can pass behind the virtual wall without carrying it manually behind this virtual wall.

I know that this feature isn't currently available in valetudo re.
The real question is if this feature can be implemented in valetodo re or if we need a special firmware support for this.

Greets,
Johann

**Comment by rand256** [comment]
The only way it could be done with current firmware is to make valetudo directly remove specified virtual wall(s) before the cleaning and restore them afterwards. I can hardly imagine which interface should be provided to be able to achieve this conveniently.

So. In theory this is possible. But only as a large set of workarounds.

**Comment by jneuhauser** [comment]
Thanks for your answer.
Seems very hacky and if i have time i will try to understand the code and try to implement it...

**Comment by Pittermaennchen** [comment]
Would have liked this too!
