### ISSUE TITLE
Zoned Cleaning

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#3]
Hey rand256,

I don't know how to at feature requests in github, so I opened an issue :D, sry for that. 

Is it possible for your to add a button on the mainpage where you select the zones to clean for just start the cleaning? It isn't realy intuitive to select the zones and then just click on one of the names to get right into the map and then have to hit the "play" button.
Just one or two simple buttons => 1st one: Start Cleaning | 2nd one: Mapview

Thx in advance :)

**Comment by rand256** [comment]
I think it may be achieved by creating some standalone settings page to contain various only Valetudo-related options. If I'll make one some day, I'd definitely add an option to choose what zone selection button should do: show map with that zone or just blindly start cleaning as it was in origin valetudo.

PS: I also don't know how to put labels or something in issues list when creating a new issue. Probably there's just no way for normal users.

**Comment by rand256** [comment]
Should be implemented in f52960a.
