### ISSUE TITLE
Does release images prevent OTA from Xiaomi?

### ISSUE THREAD

**Issue by jneuhauser** [rand256/valetudo#301]
Hello @rand256 ,

many thanks for your great work on Valetudo RE.

Do I have to be afraid that my robot will automatically update itself so that root access and the possibility for local OTA updates are lost?
Which parameters are used to build the images?
Is "--disable-firmware-updates" also set there or are the domains of the update servers redirected by Valetudo RE?

Greets,
Johann

**Comment by rand256** [comment]
In the pre-built images all the CDN domains are redirected to valetudo itself via local DNS, so it's just no way to update from there.

Also I'm not actually aware of the possibility for the device to autoupdate in general. It may update if receives the command from i.e. "mi Home", but when it's not tied to it I personally doubt there are internal triggers for downloading system updates completely on its own.

**Comment by jneuhauser** [comment]
Thank you for your time to write this down.
