### ISSUE TITLE
Delete cleaning history?

### ISSUE THREAD

**Issue by dominikheinz** [rand256/valetudo#302]
Hello,
Is there a way to delete the cleaning history of the robot? I couldn't find anything like that in the settings of the webui.
If there is no way to do that via the webui yet, I'd say it would be a great addition, especially when you bought your vaccum cleaner second hand, and it still has the maps from the previous owner on it.

**Comment by rand256** [comment]
No, AFAIK there's no such miio command.

If I recall correctly, you may just remove file /mnt/data/rockrobo/robot.db to get rid from all current cleaning history altogether. Besides, there are only 20 records max, so older cleanings will be overwritten soon enough if you use the device regularly.
