### ISSUE TITLE
Feature Request: Clear/reset errors

### ISSUE THREAD

**Issue by mtjoernelund** [rand256/valetudo#307]
Not sure if this is at all possible or if this is baked into the firmware. My question is if it would be possible to reset or clear errors (e.g. cliff sensor reporting the robot as being stuck) through Valetudo? 

My use case is that I have a couple of doorsteps that are tall enough that my vacuum can only just clear them and only by hitting them at the right angle. Sometimes the vacuum will halfway climb the doorstep and then go back and forth a few times to clear the step. Most of the time this works fine, but once in a while it will try a couple of times and then give up and report that it is stuck. It is in these last instances that I would like to be able to just clear the error and "force" the vacuum to try again.

Maybe a very specific issue not worth spending time on? Maybe not at all possible? But if it is it would make great software even better.

**Comment by rand256** [comment]
Have you tried to just issue "stop" command, or maybe some other command like "return to dock" or "goto" while it is in error state? I'm not sure about Gen1 devices, but AFAIK S50 have exactly its state cleared in such case.

**Comment by mtjoernelund** [comment]
Yes did try that, but it does not seem to work. I have a S50 and once it reports e.g. that it is stuck with a cliff sensor alert, I need to physically move the vacuum to reset the error and restart it. While I cannot know for certain, I am pretty sure that being able to clear the error and make it retry would enable it to continue.

**Comment by rand256** [comment]
Maybe cliff sensor alert is a different situation that can't be cleared remotely, but, for example, a stuck brush error definitely could. Unfortunately I was unable to reproduce the cliff alert to check for possible solutions. I've read about black carpets, but my gen2 ignores that and just goes through any black materials I put before it. Maybe this requires some specific kind of a fabric I'm missing.

Is the remote control also blocked when cliff alert error is active? If it is, I'm out of ideas how we could deal with that without some straightforward hardware workarounds like cliff sensor caps.

**Comment by radokristof** [comment]
Usually I can restart after an error and I'm using a Gen1 device. However I think I never tried restarting after a cliff sensor alert, I will try it next time...
