### ISSUE TITLE
Dark Mode Map has no wall outline

### ISSUE THREAD

**Issue by the133448** [rand256/valetudo#310]
**Describe the bug**

When I select dark mode, the map doesnt show the walls outline or objects wheras the default mode does.
![image](https://user-images.githubusercontent.com/7479387/95656176-dcd1f000-0b4f-11eb-9e5d-2a235bbccb5c.png)
![image](https://user-images.githubusercontent.com/7479387/95656184-ea877580-0b4f-11eb-94ee-8218691d9775.png)

**How to Reproduce**

Toggle on Dark Mode
Look at Map

**Expected behavior**

![image](https://user-images.githubusercontent.com/7479387/95656191-f2dfb080-0b4f-11eb-8009-4a993240b52c.png)

**Vacuum Model:** 
 Gen1 

**Valetudo Version:** 
v0.9.8.1

**User-Agent** .Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38

**Comment by rand256** [comment]
Yes, the dark mode seems broken for devices without segments support.
Really surprised it hasn't been noticed for such a long time.

**Comment by rand256** [comment]
It should be fixed in 0.9.8.2 release.

Also I'd suggest to try recreating the map with relocated dock and/or maybe better cleaned wall sensor, since walls on the map should be orthogonal to each other, while the map on your screenshot looks rotated.
