### ISSUE TITLE
play sound from network (http) 

### ISSUE THREAD

**Issue by NisseDILLIGAF** [rand256/valetudo#311]
https://github.com/rand256/valetudo/blob/6d930ca271bfb192bd8b24e9239b4b0d8da4fe73/lib/MqttClient.js#L656

Would be nice to be able to play sounds hosted on local network or web
Allowing http files
at the moment I just skip the _fs.existsSync_
`if (msg.file) { `

edit: And a big thanx to rand256, and all that's contributing to valetudo!! :)

**Comment by rand256** [comment]
I didn't personally tried that, but I think it should be quiet simple to check for file existence only for `uart_test` and allow network locations for `sox`.
