### ISSUE TITLE
Rotate map

### ISSUE THREAD

**Issue by markrennie71** [rand256/valetudo#313]
Hello

Can you add the rotate map option into valetudo-mapper please? it is in the icantbelieveitsnotvaletudo version but that doesn't work with your valetudo.

Cheers
Mark

**Comment by rand256** [comment]
Hopefully [this](https://github.com/rand256/valetudo-mapper/commit/77b581b179ace5d3568cddd112e601bb6f6d9267) will do what you're asking for.

**Comment by markrennie71** [comment]
amazing... thank you so much
