### ISSUE TITLE
Gen 1 constantly getting stuck and just sitting there, spinning its wheels

### ISSUE THREAD

**Issue by flyize** [rand256/valetudo#315]
I have a Gen 1 that seems to get stuck all the time.  More importantly, it doesn't seem to understand that it isn't moving and makes no attempt to try and get itself unstuck.  It will just sit there until I tap the bumper, then it will try to fix itself.

**Vacuum Model: Xiaomi Gen 1** 

**Valetudo Version: 9.8.2** 

**User-Agent** 

**Additional context**

**Comment by pidator** [comment]
I can't imagine this issue is valetudo related. What base firmware is installed? Have you already tried a complete factory reset?
 Furthermore "all the time" is a really general term to describe an error situation. Can you provide more details?

**Comment by flyize** [comment]
4018 is installed.  I had to factory reset it to install Valetudo, but have not since then.  There is almost certainly some ignorance on my part on what exactly Valetudo can provide, but the issue didn't crop up until I made the switch.  Apologies if this is something else.

**Comment by Mdleal** [comment]
I have a gen1 and gen2. The Gen1 gets stuck all the time on the edge of rugs. Gen2 trucks over 1 inch door seals and will try to escape if we leave the front door open.

**Comment by rand256** [comment]
In this case I suppose the only thing I can do is to build firmware images based on 4004 version or whichever one is working better than the latest 4018.

**Comment by ulug79** [comment]
I confirm that Gen1 stuck on moving between floor to carpet. But on only zone cleaning. Is not valetudo related bug.

**Comment by flyize** [comment]
@ulug79 Should I reflash to an older version?

**Comment by ulug79** [comment]
I've seen this since early versions.  now also 4018

**Comment by radokristof** [comment]
Yes this is why the zone cleanup feature is almost unusable on Gen1. I can't leave it there, because it will get stuck on the edge of the carpets or anything else and will not try to escape from it. Running a normal cleanup, it works as it should and won't get stuck on these carpets.

**Comment by flyize** [comment]
I recall zoned cleanup working perfectly with the stock firmware. Am I crazy?

**Comment by radokristof** [comment]
No, same problems on the stock fw as well. Valetudo can't change the robots behaviour.

**Comment by pidator** [comment]
Running my Gen1 only with zoned cleanup, have no issues at all...but I don't have any carpets at all.

**Comment by radokristof** [comment]
@pidator try to leave something on the floor which can't be moved by the robot and around 1 cm high. I'm pretty sure that it will stuck there and won't continue the zoned cleanup

**Comment by ulug79** [comment]
in full mode, the vacuum cleaner when moving to the carpet, if it gets stuck, tries to choose another corner, move back and tries again. When zoned cleanup, it tries all the time until it gives an error.

**Comment by rand256** [comment]
> Valetudo can't change the robots behaviour.

That's true.

I repeat, the only thing I can do is to use a different base firmware version instead of the latest 4018 when building images. So I'm closing this for now. If someone is 146% sure that some other base version works better than the current one, please post about it and I'll rebuild the release then.

**Comment by radokristof** [comment]
@rand256 I think there is no better one, I have this issue since I have the robot and they enabled the zone cleaning feature.
