### ISSUE TITLE
Home Assistant No device integration problem but only entities

### ISSUE THREAD

**Issue by dckiller51** [rand256/valetudo#316]
**Describe the bug**

Automatic integration in Home assistant does not create an additional device but an entities

**How to Reproduce**

**Expected behavior**

![cbdcd8a435bc2bd64afd9fb402196120fd445a1b](https://user-images.githubusercontent.com/53062806/96723998-97af8880-13af-11eb-9693-7d458b322efd.png)

my problem

**Screenshots**

![2ccb2b59211ecf01700941b5b1375bc21d545182](https://user-images.githubusercontent.com/53062806/96723806-561edd80-13af-11eb-9d0e-25eb9d266ec5.png)
![63579e534728ad19b0dfc9a9cd288570075b6a65](https://user-images.githubusercontent.com/53062806/96723829-5e771880-13af-11eb-8120-04fdd7b7bd4a.png)
![669b825387f8e2511dea5d7cb6d9a242db8e7188](https://user-images.githubusercontent.com/53062806/96723847-63d46300-13af-11eb-9a4e-10ad4582ee53.png)
![02a20f48d526f31e7cda1875ab110b045c3b038c_2_1035x690](https://user-images.githubusercontent.com/53062806/96723860-6767ea00-13af-11eb-830d-27ed40ab69b1.png)

**Vacuum Model:** 
GEN2 S50
**Valetudo Version:** 
Valetudo RE V 0.9.8.2
**User-Agent** 

**Additional context**

**Comment by dckiller51** [comment]
Hello,

Can you give me feedback for Home Assistant users? 
Maybe I'm doing a bad integration. Should we add an MQTT Vaccum component? 
Because I left in automatic.

Thank you for your help.

**Comment by rand256** [comment]
I personally have no idea how to use Home Assistant. You may want to consult origin Valetudo instructions about MQTT and HA, they shouldn't differ much from RE in that case (at least they didn't when I followed their changes).

**Comment by dckiller51** [comment]
> Personnellement, je ne sais pas comment utiliser Home Assistant. Vous voudrez peut-être consulter les instructions d'origine Valetudo sur MQTT et HA, elles ne devraient pas différer beaucoup de RE dans ce cas (du moins elles ne l'ont pas fait lorsque j'ai suivi leurs modifications).

Hello,

Here is the difference with Valetudo 0.6.1. I think it's just missing the device part.

Device integration OK

`{
  "name": "rockrobo",
  "unique_id": "rockrobo",
  "device": {
    "manufacturer": "Beijing Roborock Technology Co., Ltd.",
    "model": "S5",
    "name": "rockrobo",
    "identifiers": [
      "rockrobo"
    ],
    "sw_version": "0.6.1"
  },
  "schema": "state",
  "supported_features": [
    "start",
    "pause",
    "stop",
    "return_home",
    "battery",
    "status",
    "locate",
    "clean_spot",
    "fan_speed",
    "send_command"
  ],
  "command_topic": "valetudo/rockrobo/command",
  "state_topic": "valetudo/rockrobo/state",
  "set_fan_speed_topic": "valetudo/rockrobo/set_fan_speed",
  "fan_speed_list": [
    "off",
    "low",
    "medium",
    "high",
    "max"
  ],
  "send_command_topic": "valetudo/rockrobo/custom_command",
  "json_attributes_topic": "valetudo/rockrobo/attributes",
  "availability_topic": "valetudo/rockrobo/status"
}`

NOK

`{
  "name": "xiaomi_vacuum_cleaner",
  "unique_id": "xiaomi_vacuum_cleaner",
  "schema": "state",
  "supported_features": [
    "start",
    "pause",
    "stop",
    "return_home",
    "battery",
    "status",
    "locate",
    "clean_spot",
    "fan_speed",
    "send_command"
  ],
  "command_topic": "valetudo/xiaomi_vacuum_cleaner/command",
  "state_topic": "valetudo/xiaomi_vacuum_cleaner/state",
  "set_fan_speed_topic": "valetudo/xiaomi_vacuum_cleaner/set_fan_speed",
  "fan_speed_list": [
    "min",
    "medium",
    "high",
    "max",
    "mop"
  ],
  "send_command_topic": "valetudo/xiaomi_vacuum_cleaner/custom_command",
  "json_attributes_topic": "valetudo/xiaomi_vacuum_cleaner/attributes"
}`

**Comment by dckiller51** [comment]
@rand256  
To complete my research how to add this to your config.

`lib/miio/Model.js`

`            vacuum: {
                name: this.identifier,
                unique_id: this.identifier,
                device: {
                    manufacturer: this.model.getManufacturerName(),
                    model: this.model.getModelName(),
                    name: this.identifier,
                    identifiers: [this.identifier],
                    sw_version: this.model.getValetudoVersion()
                },`

Thanks

**Comment by rand256** [comment]
> Here is the difference with Valetudo 0.6.1. I think it's just missing the device part.

Well, yeah, then they did reworked that. It's also missing "availability_topic" it seems, but since I never used HA and neither read its docs, I don't know what is obligatory and what is optional there.

> To complete my research how to add this to your config.

Autoconf payload is defined [here](https://github.com/rand256/valetudo/blob/testing/lib/MqttClient.js#L111).

**Comment by dckiller51** [comment]
Do you have the possibility to add it in your future update?

**Comment by rand256** [comment]
Yes, if that will make it work.

**Comment by rand256** [comment]
I've made a [test build](https://gv.erinome.net/valetudo-test-201112.tar.gz) which includes "device" section added to homeassistant autoconf topic.
Please try it and report whether this helps.

How to check:
1. Download and unpack the test app to i.e. _/mnt/data/valetudo_;
2. Stop currently running service by running _/etc/init/S11valetudo stop_ (on 2008+ fw);
3. Run the test app by typing _/mnt/data/valetudo/valetudo_ plus &lt;Enter&gt;;
4. ...
5. Then stop the test app by pressing _Ctrl+C_;
6. Restart the common service by running  _/etc/init/S11valetudo start_ (on 2008+ fw);
7. Remove the test app.

Still, maybe something else is needed to be added, idk

**Comment by dckiller51** [comment]
> I've made a [test build](https://gv.erinome.net/valetudo-test-201112.tar.gz) which includes "device" section added to homeassistant autoconf topic.
> Please try it and report whether this helps.
> 
> How to check:
> 
> 1. Download and unpack the test app to i.e. _/mnt/data/valetudo_;
> 2. Stop currently running service by running _/etc/init/S11valetudo stop_ (on 2008+ fw);
> 3. Run the test app by typing _/mnt/data/valetudo/valetudo_ plus <Enter>;
> 4. ...
> 5. Then stop the test app by pressing _Ctrl+C_;
> 6. Restart the common service by running  _/etc/init/S11valetudo start_ (on 2008+ fw);
> 7. Remove the test app.
> 
> Still, maybe something else is needed to be added, idk

Hello, 


Hello, I have tested on my S50 Firmw 2020. It works fine. Below are screenshots. 

On the other hand, would it be possible to attach valetudo-mapper with.
![device](https://user-images.githubusercontent.com/53062806/98995370-87fc0d80-2531-11eb-9889-7acf47baaa25.png)
![Sans titre](https://user-images.githubusercontent.com/53062806/98995373-8894a400-2531-11eb-8562-8fead4188796.png)
![Sans titre1](https://user-images.githubusercontent.com/53062806/98995374-892d3a80-2531-11eb-9606-6fc587ee4f62.png)


Thank you for starting your testing.
