### ISSUE TITLE
update/version api

### ISSUE THREAD

**Issue by chaimt** [rand256/valetudo#319]
**Describe the bug**

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Vacuum Model:** 

**Valetudo Version:** 

**User-Agent** 

**Additional context**

would be nice to have an api(mqtt) to get the current version, or if there is an upgrade so i can check it with home assistant

**Comment by jacekpaszkowski** [comment]
Yes, i'm also looking formward for this.
Would be good to get payloads in new structure like:
https://github.com/Hypfer/Valetudo/blob/ac86c84c8fa75408b52067306f7e0c4a201e9725/test/lib/RRMapParser/FW2008_with_forbidden_zones_and_virtual_walls_and_currently_cleaned_zones.json

**Comment by rand256** [comment]
Currently running version number is now published in homeassistant autoconf topic in "device" object, "sw_version" field.

I'm not planning to make further changes in this unless something breaks in HA support.
For different payload structures please use origin Valetudo.
