### ISSUE TITLE
feature request: zone by floor and simple access google home assistant

### ISSUE THREAD

**Issue by Soso95190** [rand256/valetudo#32]
Hello, first of all thank you for your work. I am very grateful for the functionality of being able to save several floors, a BIG thank you.

*I would like to know if it would be possible for you to be able to integrate a function that allows you to manage the zones created (kitchen, living room, etc.) by floor, instead of it all getting mixed up like it is right now PLS.
*And finally if it would be possible to directly connect Valetudo google home assistant or has an application that is already recognized by google home assistant or another method?. Because Hassio is complicated to set up, is not the simplest solution and I can’t do it ( It resets my robot, all the time and it's annoying ).

Thank you again.

Ps: Sorry for my mistakes or misinterpretations I am French and not very good at English

**Comment by b2az** [comment]
+1 on the mutliple floor topic.

**Comment by rand256** [comment]
Kind of zones-per-map feature is implemented in 0.9.4:
- when you save a map, its zones and spots are also saved;
- when you restore a map, current zones and spots are overwritten by those stored with that map.

Regarding google assistant I know literally nothing. If someone makes some proper solution, I'd be glad to integrate it.

**Comment by rand256** [comment]
So, zones-per-map is available already, and if anyone would make google assistant support and want to integrate it to RE, feel free to post here. For now this is closed.
