### ISSUE TITLE
After update to 0.9.8.2 "Cannot GET /api/get_config" and no more then 5 zones 

### ISSUE THREAD

**Issue by z7y8hsBP** [rand256/valetudo#321]
I've updated from 0.9.4 to 0.9.8.2 and afterwards the webinterface shows the error  "Cannot GET /api/get_config"  and I (still) cannot add more then 5 zones (tried by selecting pre-configured zones).

The rest is working (thanks!).

* Open Webinterface
* Access mainpage of the webinterface (error is displayed)
* Add multiple zones, an error is shown after selecting more then 5 zones

**Expected behavior**

* No errror displayed
* More then 5 zones addable

**Screenshots**

**Vacuum Model:** 
S55 / Firmware 002008

**Valetudo Version:** 
0.9.8.2

**User-Agent** 
* Tested with Firefox on Linux, Chrome and Firefox on Android

**Additional context**

**Comment by rand256** [comment]
When you update device's firmware, you still keep an old version of web interface open (or cached) in your browser. In most cases this is the main reason for what you've described. You need to drop that cache. Though by default that should happen automatically - I've never experienced that myself.

In details:
1. /api/get_config is no more there in the latest build, so new web interface doesn't use it anymore;
2. 5 zones limit was hardcoded in the web interface, so if you see it, you are using the old web interface's files/scripts.

**Comment by z7y8hsBP** [comment]
Thanks. It actually was the webcache - I didnt think of that because I had the same errors in different browsers and machines.
Sorry for bothering you...
