### ISSUE TITLE
The vacuum cleaner refuses to clean up after the update

### ISSUE THREAD

**Issue by uPagge** [rand256/valetudo#322]
After updating Roborock s5 from version 0.9.8 to 0.9.8.2 (vacuum_2020_valetudo_re_0_9_8.pkg), the vacuum cleaner refuses to perform zone cleaning. When calling zonal cleaning, he drives away from the base, stands a little and says that everything is cleaned. Also refuses to move to the selected points, says that he can't get there

**Comment by rand256** [comment]
This is known roborock issue when the device loses the map upon leaving the dock after certain condition. It can't be fixed.

Usually the workaround is to let the device enter the dock by itself (i.e. not bring it to the dock by hands, not start or restart the device while it stands on the dock), or to make it leave the dock to the point located NEAR it, and then run other commands.

**Comment by uPagge** [comment]
Thanks for the advice, but everything was decided by a discard. Next time I'll try your ways

**Comment by uPagge** [comment]
Thanks for the advice, but everything was decided by a discard. Next time I'll try your ways
