### ISSUE TITLE
RE 0.8.2 / Map not loading

### ISSUE THREAD

**Issue by jcplu** [rand256/valetudo#324]
Map not loading (RE 0.8.2) after time change (winter hour).

**Comment by rand256** [comment]
0.8.2 is not supported for a long time.

Also I'm not sure how the missing map could be connected with local time.

**Comment by jcplu** [comment]
map is present and I have a backup. Map loads successfully but display connecting ... and no map data

**Comment by jcplu** [comment]
when using Telegram bot - zone cleaning is working

**Comment by jcplu** [comment]
and sometimes : Error 500, unable to reach vacuum ...

**Comment by rand256** [comment]
You haven't even specified your device model nor its base firmware version in use.

By the information you provided I could only say that _something_ has definitely broken for you.
Maybe do a factory reset and retry.

And again, 0.8.2 is not supported.

**Comment by jcplu** [comment]
S50 3.3.9 1886 RE 0.8.2

**Comment by jcplu** [comment]
solution : 
service valetudo stop
reboot
