### ISSUE TITLE
[BUG] Home button at start screen does not work. 

### ISSUE THREAD

**Issue by atomphil** [rand256/valetudo#327]
**Describe the bug**

Home button at start screen does not work. 

**How to Reproduce**

Click on the home button on start page in the web interface, nothing happens.

**Expected behavior**

Robo go to docking station.

**Vacuum Model:** Gen1 FW4018

**Valetudo Version:** 0.9.8.2

**Additional context**
After a zone cleaning the robot go back to station.

**Comment by rand256** [comment]
> Click on the home button on start page in the web interface, nothing happens.

When?

**Comment by atomphil** [comment]
Everytime, I can´t send the robo manually back to station using the web interface. Only using the hardware button on top of the device or automaticly after cleaning.

**Comment by pidator** [comment]
Can't confirm this - I haven't found a situation the home button on home tab isn't working on my Gen1 4018 with version 0.9.8.2
* working after sending the robot to a spot
* working while pausing zoned cleaning
* working while stopping zoned cleaning
* working **during** zoned cleaning
* working while robot is idle
* ...

**Comment by pidator** [comment]
> * working **during** zoned cleaning

Hm, just found out that in most cases this action will reset the map of a Gen1. @rand256 I don't know if it's a bug in the code or if it's better to disable the "home" button while in cleaning!? If performing pause or stop before, the map will be still present!

**Comment by atomphil** [comment]
I reinstalled the image and rebooted the robot. Now the Home button is working again. So the issue is not present anymore. I can confirm, that it forgot its map when pressing the home button during cleaning.

**Comment by rand256** [comment]
@pidator 

> Hm, just found out that in most cases this action will reset the map of a Gen1. @rand256 I don't know if it's a bug in the code or if it's better to disable the "home" button while in cleaning!? If performing pause or stop before, the map will be still present!

It's already sending stop command and waits for 0.9 seconds before issuing drive_home command. Maybe it's not enough though. I've made [a build](https://gv.erinome.net/valetudo099b3.tar.gz) with timeout increased to 2 seconds. Could you try will this improve the situation?

**Comment by pidator** [comment]
> Could you try will this improve the situation?

Thanks, just did 3 runs, it was working all the time now! I think the 2 seconds solved the issue of losing the map while returning in cleaning.

**Comment by rand256** [comment]
This is now in 0.9.9 release.
