### ISSUE TITLE
Missing Symbols - only ? as icon

### ISSUE THREAD

**Issue by URBANsUNITED** [rand256/valetudo#33]
Hi!

I am using 0.4.0-RE6 but the error popped up on the last version already.
All my symbols are showing a "?" only except the home icon as seen on the screenshot:
<img width="375" alt="Mi Robot Vacuum" src="https://user-images.githubusercontent.com/6212300/68990621-94358800-0855-11ea-8583-ccff1cfda9d6.png">

<img width="375" alt="Bildschirmfoto 2019-11-16 um 09 46 14" src="https://user-images.githubusercontent.com/6212300/68990663-0a39ef00-0856-11ea-8fe5-68b8c47a9918.png">

I am using an iPhone 7 with ios 13.2.2 tried Safari and Chrome both act equal!
Makes no difference local lan or from outside
Did a reboot and the firmware update didn't help.

BUT it worked before and I didn't change anything. It has happen out of the sudden!
What can it be?

Thanks

URBANsUNITED

**Comment by rand256** [comment]
Is this happening on iphone only? Which was the previous version that worked fine or is it the first you've installed? Could you maybe drop the cache somehow in your browser?

I don't have any apple production in use and can't reproduce this issue.

**Comment by URBANsUNITED** [comment]
Hi! Thanks for getting back to me.
I've just discovered the issue:
My iPhone is jailbroken and has a different system font installed which caused my problem.
So looks like the "icons" are no graphics more fonts. Right?

I close here as the problem has been identified and solved.

Sorry and thanks

URBANsUNITED

**Comment by rand256** [comment]
Those are icons embedded into downloadable font served by valetudo.
Probably your custom system font setting somehow overrode all fonts defined in site's CSS too.
