### ISSUE TITLE
valetudo-mapper update

### ISSUE THREAD

**Issue by dckiller51** [rand256/valetudo#331]
Me again. Sorry to bother you again with my requests but can add this to valetudo-mapper?

device: { manufacturer: "Roborock", name: this.identifier, identifiers: [ this.identifier ] },

[https://github.com/Poeschl/Hassio-Addons/issues/134](url)

Thanks

**Comment by rand256** [comment]
Done.

**Comment by dckiller51** [comment]
Thanks it works. Mr Poeschl also updated his addon. Now we have a device with the 2 entities to attach. https://github.com/Poeschl/Hassio-Addons/tree/master/valetudo-mapper

Have a nice week end.

![Sans titre](https://user-images.githubusercontent.com/53062806/100485332-e44d5880-30ff-11eb-9a36-69068629d96b.png)
