### ISSUE TITLE
Unknown error code

### ISSUE THREAD

**Issue by Hamtar0** [rand256/valetudo#339]
**Describe the bug**
Impossible to do an action on the robot.
It start few seconds then voice says : An internal error has occurred, reboot the system (in french)
So I restart the system : nothing change
So I check updates, and install 0.9.9, restart the system : nothing change

It starting after a cleaning session in my second floor (without base) and then return on ground zero with base.

**Screenshots**
<img width="339" alt="Capture d’écran 2020-12-19 à 13 32 28" src="https://user-images.githubusercontent.com/1239484/102689549-3ebd6e80-41ff-11eb-8309-6d9eb2ba4617.png">

**Vacuum Model:**
Gen 2 Roborock

**Valetudo Version:** 
0.9.9

**Additional context**
Logs in admin 
```
2020-12-19T12:38:42.854Z Probed last id = 1001 using app_get_locale (2 retries)
2020-12-19T12:38:15.021Z Timesync packet received
2020-12-19T12:38:15.016Z Robot connected
2020-12-19T12:37:54.256Z Failed to get handshake for message: get_status [] { retries: 0, retriesHS: 100 }
2020-12-19T12:37:44.690Z tgBot: probeV6 finished with: v4
2020-12-19T12:37:34.276Z Webserver is running on port 80 (http)
2020-12-19T12:37:34.272Z Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
2020-12-19T12:37:34.201Z No ssl key found. Expected path: /mnt/data/valetudo/key.pem
2020-12-19T12:37:34.200Z No ssl cert found. Expected path: /mnt/data/valetudo/cert.pem
2020-12-19T12:37:34.034Z Loading configuration file: /mnt/data/valetudo/config.json

```

**Comment by pidator** [comment]
Perhaps map files corrupt? Have you tried deleting the current map in settings / persistent data and start a new full clean run?

**Comment by Hamtar0** [comment]
Tried just after seeing your message, deleting map and a restart : nothing change.

**Comment by Hamtar0** [comment]
If the wacuum are not on the base, the voice continue to alert, peridocally.
But on charge, no alerts.

**Comment by rand256** [comment]
Please post what's printed at `http://vacuum's_ip_addr/api/current_status` when you see the unknown error code, maybe that would guide us on the actual error codes.

**Comment by Hamtar0** [comment]
`{"msg_ver":3,"state":12,"battery":100,"clean_time":0,"clean_area":0,"error_code":106,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_status":1,"water_box_status":0,"fan_power":101,"dnd_enabled":0,"map_status":1,"lock_status":0,"human_state":"Error","human_error":"UNKNOWN ERROR CODE","model":"roborock.vacuum.s5"}`

**Comment by Hamtar0** [comment]
Ok...

So i found this 
https://www.reddit.com/r/Xiaomi/comments/f1vqu2/roborock_s5_error_106/

So I have checked wheels (front, and both side), cleaning them (without removing), and force wheeling on both side.
Started cleaning and voila !

So strange...

**Comment by rand256** [comment]
So we have a number of error codes missing in RE for 2008+ fw, and that's a shame.
Thank you for helping to find it out, I'll add them soon.

Regarding the error itself, this goes to the manufacturer, as valetudo can't do anything with it.
