### ISSUE TITLE
REST api curl PUT request start_cleaning_zone_by_name

### ISSUE THREAD

**Issue by markusdahlberg** [rand256/valetudo#345]
Hi and thanks for a great software.

I am trying to request zoned cleanup by curl. 

I am using this string

curl -X PUT -H "Content-Type: application/json" -d '[{"Zone1"}]' http://192.168.1.118/api/start_cleaning_zone_by_name

This error occurs .

Am I doing this wrong or is it a bug?

`!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token } in JSON at position 9<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/snapshot/valetudo/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /snapshot/valetudo/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/snapshot/valetudo/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/snapshot/valetudo/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/snapshot/valetudo/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:327:22)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1221:12)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:84:21)</pre>
</body>
</html>
`

**Comment by rand256** [comment]
As for me, it tries to say that your json is wrong. You need to put an array of strings, while you're writing an array of invalid objects.
Try just `'["zone1"]'` or `'["zone1","zone2"]'` etc.

**Comment by markusdahlberg** [comment]
> As for me, it tries to say that your json is wrong. You need to put an array of strings, while you're writing an array of invalid objects.
> Try just `'["zone1"]'` or `'["zone1","zone2"]'` etc.

root@rockrobo:~# curl -X PUT -H "Content-Type: application/json" -d '["Hall"]' http://192.168.1.118/api/start_cleaning_zone_by_name;echo
Error: Zones must be array of at most 5 zones.

**Comment by rand256** [comment]
And this is really a bug. Probably nobody used this route for years. :(

Just fixed that, please try running [this test build](https://gv.erinome.net/valetudo-test-201226.tar.gz). See installation instructions [in wiki](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) (if you have a gen1 device, it's still applicable, just replace `/etc/init/S11valetudo stop` with `stop valetudo` and, `/etc/init/S11valetudo start` with `start valetudo`).
Sorry for the inconvenience.

**Comment by markusdahlberg** [comment]
It works! thanks
