### ISSUE TITLE
Volume control does not work

### ISSUE THREAD

**Issue by Phoenixxx3** [rand256/valetudo#347]
Hi,

my volume control stopped working. Changes in the webinterface are saved in RoboController.cfg, but do not effect the volume. I am on v0.10.0 (002034, Gen2).
I did not find any similar issues, maybe it's just me.

Best regards,
Michael

**Comment by pidator** [comment]
RoboController binary changed from 2020 to 2034 - perhaps the volume handling has changed too?
On `2020` and RE `0.10.0` it's still possible for me to change and save the volume.

**Comment by rand256** [comment]
Can't confirm this. Checked on 2034 right now and the volume definitely changes.
Do you mean you hear no difference when you move the volume bar and press "test sound volume" button in the web UI?

**Comment by Phoenixxx3** [comment]
I did not change anything, but it seems to work again. Don't know what the problem was.
