### ISSUE TITLE
Telegram-bot of RE 0.10.0 cannot send map picture

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#349]
With `RE 0.10.0` the telegram bot can't send the picture of the current map anymore.
Instead there's this errormessage in the log:
`2020-12-29T12:30:51.483Z tgBot polling: Cannot read property 'image' of undefined`

A Reboot didn't help either.

**Vacuum Model:** S5
**Valetudo Version:** 0.10.0 (2020)

**Comment by rand256** [comment]
Yeah, that's true, it's broken. :( 
Thanks for info.

I'll try to release a new point version soon with fixes of already found issues.

**Comment by pidator** [comment]
Map over Telegram is working again with *0.10.1*, great - thanks!
