### ISSUE TITLE
Two instances of Valetudo-Mapper?

### ISSUE THREAD

**Issue by ThrashinVictim** [rand256/valetudo#352]
**Describe the bug**

Is there a way to have two instances of valetudo mapper running on Hassio?
**How to Reproduce**

I installed valetudo mapper via hassio addons but I have two vacuums running Valetudo RE and need two maps. Is there a way to get another instance of valetudo mapper running?
**Expected behavior**

**Screenshots**

**Vacuum Model:** 
Vacuum Model S5
**Valetudo Version:** 
Valetudo Version 10.0
**User-Agent** 

**Additional context**

**Comment by rand256** [comment]
Try asking hassio addon author maybe as I personally simply don't know.

If you run mappers unrelated to hassio, you just run 2 different copies simultaneously (i.e. from 2 directories) having different prefixes in their configuration matching those in valetudo config.

**Comment by rand256** [comment]
I've added the ability to run multiple instances of one valetudo mapper with different configuration files in its latest build.

**Comment by ThrashinVictim** [comment]
Great! Is there a how to? Thanks for your work.

**Comment by pidator** [comment]
Just have a look at the readme file...
> For this start the instance with ./node app.js -f /path/to/config.json. You may also need to add the -c key to generate a new custom config file if it doesn't exist.
