### ISSUE TITLE
Auto Map Restore has no map to select

### ISSUE THREAD

**Issue by florie1706** [rand256/valetudo#353]
**Describe the bug**

When I go to Settings and want to select a map for Auto Map Restore, there is just a message that there is no saved map. How to save it? In the map tab there ist my map (which I would like to have autorestored).

**How to Reproduce**

**Expected behavior**

SHould be at least my current map form the map tab.

**Screenshots**

**Vacuum Model:** 
Gen2 S5

**Valetudo Version:** 
always current, so now it is 0.10.0

**User-Agent** 

**Additional context**

**Comment by pidator** [comment]
Goto settings / webinterface and enable the multimap buttons. then you'll be able to save (and load) a map on home tab. For auto restore you'll first have to "save" your current map.

**Comment by florie1706** [comment]
Oh thank you very much. I was searching for ages :) Solution is so easy and close. Thx, you made my day :)
