### ISSUE TITLE
If it doesn't automatically integrate into Home Assistant \ Если пылесос автоматически не интегрируется в Home Assistant

### ISSUE THREAD

**Issue by DivanX10** [rand256/valetudo#355]
Об этом нигде не написано и поэтому решил написать. После загрузки прошивки Valetudo, в настройках MQTT, а именно префиксы: префикс и префикс автонастройки. В них по умолчанию прописаны homeassistant. Если ранее использовали подключение к другой платформе и переименовали префикс homeassistant на свое и потом решили переподключить к home assistant, то необходимо указать префикс homeassistant. В противном случае home assistant не увидит пылесос.

This is not written anywhere and so I decided to write. After downloading the Valetudo firmware, in the MQTT settings, namely prefixes: prefix and auto-tuning prefix. They are set to homeassistant by default. If you previously used a connection to another platform and renamed the homeassistant prefix to your own and then decided to reconnect to home assistant, then you must specify the homeassistant prefix. Otherwise, the home assistant will not see the vacuum cleaner.

![img01](https://user-images.githubusercontent.com/64090632/103444182-2aee1f80-4c77-11eb-9358-657029ae5b97.jpg)

**Comment by rand256** [comment]
Is it actually an issue?
I'd suggest to re-post it to [Show & Tell](https://github.com/rand256/valetudo/discussions/categories/show-and-tell) section of the Discussions.
