### ISSUE TITLE
Missing room colors

### ISSUE THREAD

**Issue by xav4nte** [rand256/valetudo#363]
Rooms are not colored even though they get a segment number.

**How to Reproduce**

1. Installed firmware from vacuumz.info: vacuum_2034_valetudo_re_0_10_0.pkg
2. Let the robot clean the house
3. Let the robot dock, to save the map

Installed 

**Expected behavior**

Each room in a different color
**Screenshots**

<img width="1274" alt="Skärmavbild 2021-01-02 kl  17 39 58" src="https://user-images.githubusercontent.com/12793260/103461869-ba500d00-4d21-11eb-9d8b-c91059f3a973.png">
<img width="823" alt="Skärmavbild 2021-01-02 kl  17 40 18" src="https://user-images.githubusercontent.com/12793260/103461870-be7c2a80-4d21-11eb-8d1c-7abbb87582ca.png">

**Vacuum Model:** 
S5

**Valetudo Version:** 
0.10

**User-Agent** 

**Additional context**

Running firmware 2034

**Comment by pidator** [comment]
It's more a feature request than an issue, isn't it? 
I personally like the "plain" map style without the colours...

**Comment by xav4nte** [comment]
Oh... I just thought it was an existing feature since I first installed the "original" Valetudo which had this, but you might be right, in that case, just close this. :)

**Comment by rand256** [comment]
@pidator is right (as always :)), RE doesn't have a bright multicolored segments looking like a christmas garland, and for now I'm not planning to implement it. Maybe it could be added as an option at some point in the future if it will be highly demanded though.

**Comment by xav4nte** [comment]
Thanks for the clarification and sorry for creating an issue about it.
