### ISSUE TITLE
/etc/rc.local is not executed automatically

### ISSUE THREAD

**Issue by dg-0** [rand256/valetudo#364]
**Describe the bug**

The /etc/rc.local script is not executed automatically at boot. Consequently the map is not shown in the webif.

After executing the script manually (bash /etc/rc.local via ssh), the map is show. However, after reboot its broken again.

While executing the script, error „ip6tables not found“ is displayed.

**Vacuum Model:** 
S5
**Valetudo Version:** 
0.10.0
Firmware 2020
Built via DustBuildee

**Comment by rand256** [comment]
This means the dustbuilder simply doesn't have the ipv6 modules for iptables enabled. I'd suggest to rebuild your image with the [vacuumz builder](https://github.com/zvldz/vacuum) as that is the builder I use for testing RE versions.

Though I'll add checks into rc.local so it won't try using ip6tables when it's not available. Thanks for reporting that.

**Comment by dg-0** [comment]
Thank you for your feedback. I re-flashed as suggested and the problem does not exist any longer.

Nevertheless, I'm not sure if you got my real issue: the error according ip6tables did not lead to problems (I just mentioned it as an information). The problem was that the script was not executed at a reboot. -> iptables-rules were missing -> traffic to 203.0.113.1 was not rerouted -> map was not shown.
