### ISSUE TITLE
[Enhancement] [MQTT] Add battery level and power mode

### ISSUE THREAD

**Issue by goodwin** [rand256/valetudo#366]
Could you please add these two attributes to the MQTT published data? Just found that those values are missing, however, they are available in the Valetudo RE own WebUI

**Comment by rand256** [comment]
This data is available in the [state topic](https://github.com/rand256/valetudo/wiki/MQTT-API#Topic_valetudorockrobostate).

**Comment by Sebclem** [comment]
@rand256 I think this can be useful if you publish the batery level to a separate topic, you can use [battery_level_topic ](https://www.home-assistant.io/integrations/vacuum.mqtt/#battery_level_topic) in home assistant discovery, this will add the battery level to the device like with mobile app integration: 
![image](https://user-images.githubusercontent.com/23737709/104459911-b045ce00-55ad-11eb-8a21-30c9c4240f10.png)
 I'm also thinking about `cloning` the attributes values to a specific topic, in Home assistant this can useful, currently, we need to create template entity and this is not very user friendly.

**Comment by rand256** [comment]
Feel free to edit MqttClient.js to fit your needs and create a PR.
I'm not using any Home assistant or other integration so I effectively don't know what and where is needed.
