### ISSUE TITLE
How to set up segment cleaning from Home Assistant

### ISSUE THREAD

**Issue by uPagge** [rand256/valetudo#368]
I tried to set up using the official documentation

https://valetudo.cloud/pages/integrations/home-assistant-integration.html

![изображение](https://user-images.githubusercontent.com/40397740/103891072-3f5c6d00-50fa-11eb-998a-a362b67acd6c.png)

I took the segment identifiers from here

![изображение](https://user-images.githubusercontent.com/40397740/103891115-4e431f80-50fa-11eb-996f-9e64e46e4d68.png)

![изображение](https://user-images.githubusercontent.com/40397740/103891152-6024c280-50fa-11eb-8702-c269c9c0af5f.png)

But when I run this script nothing happens

Perhaps the documentation is outdated, can you tell me

**Comment by rand256** [comment]
You should use the ["official" documentation](https://github.com/rand256/valetudo/wiki/MQTT-API#Topic_valetudorockrobocustom_command) for RE.

**Comment by uPagge** [comment]
Thank you very much
