### ISSUE TITLE
Feature Request: Disable PowerLED when docked

### ISSUE THREAD

**Issue by V4n1X** [rand256/valetudo#369]
Can you built this into the webui?

Controlled by miio command set_led_status and fetched with get_led_status, a value of 0 means that the indicator LEDs will be disabled if the robot is docked and fully charged.

This is represented by roborock feature flag 119

Official App screenshot:
![image](https://user-images.githubusercontent.com/23241347/103938107-063bf100-512a-11eb-8ce1-a663fd31e25b.png)

**Comment by Hypfer** [comment]
If you quote me, you could at least give some credit, y'know?

**Comment by V4n1X** [comment]
> If you quote me, you could at least give some credit, y'know?

sorry for that, i forgot it in my hurry. a big thank you goes out to you for your great work and development of your project as well!

**Comment by 10bn** [comment]
Also from my side thanks for the amazing work that has been done with valetudo re! 

1+ for a dark power button :)

**Comment by rand256** [comment]
I've suddenly decided to check this one (I know I'm _a bit_ late), but appears it doesn't work on my S5 with latest firmware. Yes, it claims it has feature flag 119, it accepts set_led_status command, it changes current value as can be checked by get_led_status - but LEDs brightness doesn't change at all when the device is fully charged resting on a dock.

Sadly.
