### ISSUE TITLE
Power level is not saved

### ISSUE THREAD

**Issue by truresma** [rand256/valetudo#370]
Hello,

Power level is not saving anymore.
in the saved time control i have selected "maximum" but the robot is starting everytime at "balanced"

S50 newest version

**Comment by rand256** [comment]
Do you have fanpower setting errors in the system log?

**Comment by rand256** [comment]
Anyway I just tried running zoned cleaning and the fan mode automatically switches to level set on Settings->Timers page.
Same should happen for global cleaning (though it is controlled directly by firmware, not affected by valetudo).

Do you use map save/restore feature maybe? Then it could be that you've changed fanpower from "balanced" to "max" in timers settings and then restored the map where fanpower was "balanced". You need to re-save (overwrite) the map again to keep your changes in timers in this case.

PS: It is suggested to not to use "max" power setting very often, it is known it can damage the engine, particularly when the dustbin is nearly full.

**Comment by truresma** [comment]
hello,

no i don't have any fanpower error in the log.

i don't have a presaved map, and by the timed cleaning i changed it now to "turbo"  i´m using timed cleaning, not zoned cleaning.

really? i always had it on maximum ^^ i use it now on turbo, thanks

**Comment by rand256** [comment]
Found an error in the code, the fix will be available soon in 0.10.2.
Thanks for mentioning this!
