### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Schattenruf** [rand256/valetudo#371]
Hey :)

I need your help.
I have an old Roborock S5 and I updated my Valetudo to 10.1. That worked well. After that I wanted to do the firmware package install. I just took the original 2034.pkg one from vacuumz (not with valetudo or something in the name).

It installed successfully and now my valetudo site does not load. I do not have any s11valetudo file in /etc/init. The other ones are there:
![image](https://user-images.githubusercontent.com/12720317/104190112-e0f5fe00-541b-11eb-9e24-b048612dd59a.png)

Valetudo is there as well:
![image](https://user-images.githubusercontent.com/12720317/104190151-f23f0a80-541b-11eb-9e41-f3c3c983724b.png)

How can I startup that site again?

Thank you!

**Comment by rand256** [comment]
You can take missing files [from here](https://github.com/zvldz/vacuum/tree/master/custom-script/files) and put it to corresponding locations. You'll need the aforementioned `s11valetudo` and `valetudo-daemon.sh`.

**Comment by Schattenruf** [comment]
Hi, thanks for the files. Sadly the error persists...

**Comment by pidator** [comment]
You've installed only a "rooted" firmware file. Why not using the complete prebuild image with containing valetdo (if you don't want to build the firmware by yourself)?

**Comment by Schattenruf** [comment]
I had valetudo up and running. That's why I thought I could make an update from that... Well wrong thought I guess.

@rand256 and @pidator Is there any command where I can update the firmware again with the valetudo img from shell?
The shell with root privileges is working.

**Comment by Schattenruf** [comment]
Ah got it working again. The daemon needed to be under /usr/local/bin :)

**Comment by rand256** [comment]
Actually you'll need to "install" (unpack) at least [dns catcher](https://github.com/zvldz/vacuum/blob/master/custom-script/files/dns.tgz) and put contents of [rc.local](https://github.com/rand256/valetudo/blob/testing/deployment/etc/rc.local) to /etc/rc.local to get local "cloud" connection working, otherwise you'll get no map and no chance to install other image using valetudo's Web UI.

**Comment by Schattenruf** [comment]
@rand256 
ok where do I need to put the dns catcher?

**Comment by rand256** [comment]
Simply unpack that tgz to root, there are already correct paths exist inside the archive.

And I forgot to mention [these two lines](https://github.com/zvldz/vacuum/blob/master/custom-script/custom_dns_catcher.sh#L50-L51) to put into rc.local (after those of valetudo) for it to work.

**Comment by Schattenruf** [comment]
@rand256 
After I did that it now states: 
![image](https://user-images.githubusercontent.com/12720317/104194511-b9099900-5421-11eb-9c2a-b88b80f0b3d3.png)

**Comment by pidator** [comment]
Alternatively if you've installed miio python tools on your laptop/pc you could flash a whole new firmware file with the command
`mirobo --ip <ROBOT-IP> --token <TOKEN> update-firmware <FILENAME>`

**Comment by rand256** [comment]
@pidator I guess original 2034 image won't allow local OTA updates.

@Schattenruf well, really probably the easiest way in this case could be to do a factory reset and start from scratch.

**Comment by pidator** [comment]
> @pidator I guess original 2034 image won't allow local OTA updates.

Since root access is still possible, I think it was installed `vacuum_2034.pkg` and following `vacuum_2034.pkg.diff` miio client should be replaced in this firmwarefile too:

`Binary files /image.org/opt/rockrobo/miio/miio_client and /image/opt/rockrobo/miio/miio_client differ`

so, mirobo update could be successfull ;)

**Comment by Schattenruf** [comment]
@pidator 
Sadly it is not... "No respone from device"

**Comment by Schattenruf** [comment]
I gonna start from scratch then. Thank you all for your time!
