### ISSUE TITLE
S55 does not find home after cleaning

### ISSUE THREAD

**Issue by eflavio** [rand256/valetudo#372]
Hi,
My robot does not find home after cleaning a room. My rooms have high door steps so the robot can not reach the home by itself after entering a room. I always carry the robot to the level where also the beacon sits and press the home button. Then the robot spins around every few meters and looks like it's scanning for the home beacon. I'm confused because I would expect it to go to the home position directly since it stored a map of my flat successfully. Does anyone have an idea? I have no clue where to start troubleshooting this.

**Comment by thekarinka** [comment]
Do you have enough space around dock charger? See [this page and image with distances](https://m.gearbest.com/blog/how-to/my-robot-vacuum-cleaner-gets-lost-479)

**Comment by eflavio** [comment]
Thanks for the hint. The robot is placed under the sofa. So this might be the problem according to your link. But why is this a problem? Isn't the robot using SLAM algorithms to navigate?

**Comment by rand256** [comment]
Roborock has a huge lot of issues with navigation. Remember at least its inability to detect a way through an open door that it once saw closed or how it tries to avoid obstacles it remembered that are actually gone long ago. Only the manufacturer (or their driver developer maybe?) can do something with that, but they clearly decided to leave everything as is. And valetudo is only a Web UI.
