### ISSUE TITLE
No Map Data

### ISSUE THREAD

**Issue by r7l** [rand256/valetudo#375]
Hello, i've rooted my S5 and installed a firmware with the Dustcloud image builder (from web), which added 10.0.0 of Valetudo but i've updated it to 10.0.3 by replacing the `valetudo` file in /usr/local/bin as it is shown in the script in [this issue](https://github.com/rand256/valetudo/issues/153). The issue with the map was there with 10.0.0 and remained with 10.0.3.

I can connect to the robot from browser and it seems to work fine, except for the map. In [this issue](https://github.com/rand256/valetudo/issues/196) it is mentioned that it would need miio 3.3.9 to make the map work and my info page shows this version.

So how to make the map work?

**How to Reproduce**

1. Go to 'the ip of the xiaomi vacuum with a browser'
2. Click on 'map button'
3. See "no map data" and a box reading "Status: Connecting ... Battery: 0%"

**Vacuum Model:** 

Gen2/S5

**Valetudo Version:** 

10.0.3

**User-Agent**

Any Chrome / Firefox

**Additional context**

It does not matter how much the robot cleans. It is still not showing any map.

**Comment by pidator** [comment]
I don't know if dustbuilder includes the dns catcher that is necessary for the map/dustcloud-connection to work (in firmwares 2008+). I would recommend to use the [zvldz-builder](https://github.com/zvldz/vacuum/) for building the firmware by yourself. Or check the installation steps for the dns catcher manually [here](https://github.com/zvldz/vacuum/blob/master/custom-script/custom_dns_catcher.sh).

**Comment by r7l** [comment]
Thanks for the link to the builder. It looks awesome. I am going to give it a try.

**Comment by r7l** [comment]
@pidator I've build a new firmware with this builder and included the dns-catcher but somehow it still doesn't work. But i might open up an issue over there. Thanks again for pointing me to this builder.
