### ISSUE TITLE
AppProxy doesnt get patched with FW 2034

### ISSUE THREAD

**Issue by nob0dy80** [rand256/valetudo#376]
Dont know if that is important, but AppProxy doesnt seem to get a patch when using fw 2034 to build for a Gen2 device.

++ Trying to patch AppProxy
-- AppProxy is NOT patched

When using firmware 2020, the patch is OK:

++ Trying to patch AppProxy
++ AppProxy is patched

**Comment by rand256** [comment]
Please see [this changeset](https://github.com/zvldz/vacuum/commit/fb184eda5930b06f7fb71055ac14d0932fc1684c) in upstream.
My copy of vacuum image builder published here is a bit outdated (and archived), and I'm not using it for building images here.

**Comment by nob0dy80** [comment]
@rand256 
ok changing that lines did it. at least no errors.

i still use the zvldz version for building the images. are there any reasons using your fork or is the original from zvldz as good as ?

**Comment by rand256** [comment]
I'll repeat, it is my fork of the builder that is outdated and thus archived, please always use the upstream zvldz/vacuum for creating images.

**Comment by nob0dy80** [comment]
thanks for your help
