### ISSUE TITLE
gen1 fw file on gen2 device plz help me

### ISSUE THREAD

**Issue by prinz3nroll3** [rand256/valetudo#380]
Hello,
i need some help, please.
I flashed the wrong file :-( i have an roborock gen2, but i idiot flashed the gen1 file.
i copy the wrong link from the website :-(

whats working:
restore factory settings
connect to the roborock wifi
ping 192.168.8.1

whats not working:
webinterface @192.168.8.1
ssh @192.168.8.1:22

i have no idea howto flash the right firmware.
plz i dant want to have an brick

i m such a idiot

**Comment by rand256** [comment]
You've already "unbricked" the device with a factory reset. Now you need to flash the correct firmware image with pre-installed valetudo using i.e. XVacuum android app or flasher python script.

**Comment by prinz3nroll3** [comment]
Hello,
wow thanks for the fast answer.
XVacumm only try to send the firmware
and win-mirobo write:
 WIN-MIROBO INITIALIZATION ERROR
 Can not connect to device: Method 'miIO.info' error on socket receive...
 Press any key for exit...

**Comment by rand256** [comment]
Are you sure you actually did a full factory reset and not just a wifi reset?

Also in both cases you need to be connected to a roborock wifi, and for win-mirobo it's better to temporarily disable windows firewall (or allow the application to accept incoming connections).

**Comment by prinz3nroll3** [comment]
Hi,
i think it was an hard reset.
1) press and hold dock/power
2) press reset
3) after reset voice release dock button
but this is the procedure for the s5

i flash the gen1 file, how did i reset the gen2 file with the gen1 firmware, the same way?
thanks

**Comment by prinz3nroll3** [comment]
WOW thanks a lot rand256.
he is back alive! after an real factory reset it was possible to update the firmware.
THANKS
