### ISSUE TITLE
home assistant xiaomi clean zone

### ISSUE THREAD

**Issue by qvqn** [rand256/valetudo#39]
when using home assistant to send clean zone or goto place the co-ordinates are off on the y axis

co-ordinates don't seem to match up when using the vacuum call service in home assistance
**How to Reproduce**

the co-ordinates was achieved by creating zones 
then extracting them from api/get_config
calling vacuum.send_command
app_zoned_clean [[3540,20630,7229,25852,1]]]

the zone is shifted down but when calling the zone from valetudo web interface it works correctly

**Expected behavior**

**Screenshots**
https://imgur.com/a/bX46BMP

**Vacuum Model:**  gen2 S5

**Valetudo Version:** 4.0 R5 

**User-Agent** 

**Additional context**

**Comment by rand256** [comment]
It is not supposed to work this way.

If you wish to extract coordinates from valetudo configuration and sent them into the vacuum not using valetudo, you need to pre-process them [like this](https://github.com/rand256/valetudo/blob/testing/lib/miio/Vacuum.js#L611).

**Comment by qvqn** [comment]
ok thanks i see it now y co-ordinates needs to be subtracted by 

tools.DIMENSION_MM which is 50 * 1024

also another quick question is there a distance limitation in the vacuum itself? mine can go a max of 31 meters from the chargin station, it then stops drawing map and gets lost.

https://imgur.com/a/bGLgWDM

**Comment by rand256** [comment]
Yes, that's a limitation in firmware, it can't be changed.

**Comment by qvqn** [comment]
ok thank you
