### ISSUE TITLE
no map data after upgrade

### ISSUE THREAD

**Issue by AlexOnFOSS** [rand256/valetudo#392]
Hello,

yesterday I installed firmware version 2020 included with valetudo-re from dusctloud.
Previously I had an old firmware (prior 20) with an old version of valetudo-re in use.

After installing the new firmware (incl. with valetudo-re) I did a reboot. 
After logging into valetudo-re I switched to the Map-Tab and had to see that no map was loaded - which I did expect. 
At the Startpage of Valetudo I was able to select my previously saved maps - which did surprise me. 
I did select one of my saved maps to load, but they never appeared in the Map-Tab.
Then I tried to go to the Settings-Tab and delete / reset the Map-Data. Rebooted the device, started a clean, stopped the clean, drove back to station and so on, but the Map-Tab remains clear "no map data".

Finally I did log in via ssh, deleted my old Maps in the /mnt/data/valetudo/maps/* folder and restarted /etc/init/valetudo restart, but still the Map Tab remained empty.

Than i took a look at the /mnt/data/valetudo/config.json file. 
The last few lines really surprised me, because they do still reference to my deleted maps:
```
  },
  "allowSSHKeyUpload": true,
  "map_upload_host": "http://127.0.0.1",
  "lastLoadedMap": {
    "name": "EG-Alex",
    "date": 5759972
  }
}
```

So my question is, can it be that my config file is messed up?
Why am I not able to create a new map from scratch or load an old map?

Any tips on, how to resolve this issue and be able to at least create a new map?

```
[root@rockrobo data]# ls valetudo/
config.json      maps             uploads
[root@rockrobo data]# ls valetudo/maps

[root@rockrobo data]# ls valetudo/uploads/


```

[config.json.txt](https://github.com/rand256/valetudo/files/6008577/config.json.txt)

**Comment by rand256** [comment]
I guess dustcloud images are broken in one or other way for RE - there were a number of other reports like yours.

I'd suggest either of the following options:
a. Install vanilla valetudo image from dustcloud, then replace valetudo binary on device with RE version downloaded separately from Releases section of this repository;
b. Install image built with [vacuumz image builder](https://github.com/zvldz/vacuum);
c. Install pre-built image from Releases section of this repository.

While I'm not fully sure about a.), but b.) and c.) will definitely help.

**Comment by AlexOnFOSS** [comment]
thx, I will give it a try

**Comment by AlexOnFOSS** [comment]
Okay I have tried different prebuild images from b) and c). All got installed without issues. The only problem, no map data.
Now I have reinstalled my old image that was working fine for the whole last year and also here now: no map data

At the Map tab the following is written in the upper left corner: 
Status: Connecting...
Battery: 0% 


The problem must be somewhere else, I guess, but I have no clue where to look at.
Apart from that, i have read other issues related to "no map data" that the dummy cloud might not be talking to the robot? Is there a workaround to that: For example use an external app to host the map / cloud?

```
root@rockrobo:/mnt/data/rockrobo/rrlog# uname -a
Linux rockrobo 3.4.39 #1 SMP PREEMPT Thu Aug 1 10:34:01 CST 2019 armv7l armv7l armv7l GNU/Linux
```

Roborock S5
Firmware Versino: 3.3.9
Build 1898
Valetudo RE 0.8.9

**Comment by rand256** [comment]
> Apart from that, i have read other issues related to "no map data" that the dummy cloud might not be talking to the robot? 

It would be more correct to say "robot isn't talking with dummy cloud", since it is robot who initiates connection, not valetudo... And yeah, if you don't see a "Robot connected" message in valetudo's log, it means that firmware haven't tried to connect with dummycloud. Note that after device boot it will connect almost immediately, but if you manually stop/start valetudo it may take even up to 20-30 minutes to connect. Though in most cases it should happen much quicker.

Files you've pasted look more or less correct for an old 1898 image, so, as you said, the issue is somewhere else.
Have you tried performing a full factory reset and start from scratch?

**Comment by AlexOnFOSS** [comment]
### **Suddenly , one day later, after connecting the robot to my wifi the map appeared while using my old 1898 img with preinstalled Valetudo RE 0.8.9 .**
Before connecting the robot to my wifi there was no map still. Immediately after connecting to my wifi the map appeared. 

**Can it be, that the robot has to be connected to my wifi for the map to work?**

Yes, I did a fully factory reset prior installing the different images beforehand. 

PS: big thank you for investing your time in all this.

**Comment by rand256** [comment]
> Can it be, that the robot has to be connected to my wifi for the map to work?

[Definitely](https://github.com/rand256/valetudo/issues/201).

The device firmware supposes that if the device cannot be connected to the Internet (and without Wifi it surely can't), then there's completely no reason for it to try uploading the map, cause it believes that the cloud can be only located at some remote host.

**Comment by AlexOnFOSS** [comment]
Thank you. I feel stupid now °°

In the next days, i will try the different images again, to see if the problem persists with them.
I will give an update than.

**Comment by AlexOnFOSS** [comment]
Okay, I have tested three image-files now and you r right. The only img that does not work, is the one from dusctloud v11_002008.pkg with valetudo-re 10 preinstalled.
