### ISSUE TITLE
Telegram error

### ISSUE THREAD

**Issue by dreamkiller52** [rand256/valetudo#399]
Hi I don't know why but after a few day working I didn't have anything on the telegram bot now.
I have the foàllowing error in my log 

2021-02-25T21:06:15.683Z tgBot polling: Error: connect ENETUNREACH 2001:67c:4e8:f004::9:443 - Local (:::0)
{"ok":false,"error_code":409,"description":"Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"}
2021-02-25T21:06:10.648Z tgBot polling: 409:

Valetudo V0.10.5

Did you know how to clean this webhook?

**Comment by rand256** [comment]
A quick google search lead me to a suggestion to visit the following URL: `https://api.telegram.org/bot<YOUR_BOT_TOKEN>/deleteWebhook`

Telegrambot in valetudo never used webhooks, so somebody called a setWebhook method of telegram API using your bot token.

**Comment by dreamkiller52** [comment]
Ho thanks, i didn't found that answer during my search.
It's probably occur when i try to set the valetudo telegram bot inside my domotic system.

Thanks for your help and your great work on this project
