### ISSUE TITLE
Timed Zone Cleaning

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#4]
Hey rand256 :D Here I'm again! Thx first for support! Realy good job so far.

Today I added 2 testtimers for zoned cleaning.

![image](https://user-images.githubusercontent.com/17103076/60919360-ca567000-a295-11e9-8f78-d171fccd0e37.png)

And here is the result:

![image](https://user-images.githubusercontent.com/17103076/60919415-ec4ff280-a295-11e9-915b-7d453961d8e5.png)

Is it even possible to change the time on this page as well? 
The Timezonesetting doesn't help at all because it still uses GMT instead of GMT+1?

**Comment by rand256** [comment]
With 0b72a9ce177843e27e5dd8d7be806909aa6655ef it should show cleaning time using timezone selected in the vacuum's settings.

**Comment by nicedevil007** [comment]
I will test it. The time in CLI is correct on my S50.
But I think valetudo is using an other time. Will report back :)

**Comment by nicedevil007** [comment]
Ok tested. Set the robot to clean a test area at 17:35, it doesn't start. 
I think it will start at 18:35 now.

![image](https://user-images.githubusercontent.com/17103076/61064932-03602300-a403-11e9-8699-840c9ab36b31.png)

Oh and an enhancement :D
What about an Edit button as you did for the Zones to change the timersettings or days etc, or even the name?

**Comment by rand256** [comment]
Please make sure you have correct timezone set in vacuum's firmware (that is used for normal clean timers as well). It's may be different from the timezone at onboard linux system.
It is set at "settings" -> "timers" -> "gear icon".

Editing zoned timers isn't nearly as easy as editing zones. I agree though it should be done some day.

**Comment by nicedevil007** [comment]
I double checked it again. The timezone is set to Europe/Berlin what's correct for me :)

![image](https://user-images.githubusercontent.com/17103076/61067881-f5150580-a408-11e9-9e48-6b4c6b0366e9.png)

and here CLI:

![image](https://user-images.githubusercontent.com/17103076/61067968-22fa4a00-a409-11e9-9c12-2d1fe45c98f4.png)

**Comment by nicedevil007** [comment]
Ok, now it is 18:35 => S50 started Testzone cleaning...

**Comment by nicedevil007** [comment]
Maybe it is a problem with summer/winter time?

**Comment by rand256** [comment]
Yes, node-cron module seems doesn't support Daylight Saving Time at all.

**Comment by nicedevil007** [comment]
Ok, then we don't have a chance at all to fix that right? Isn't it possible to determine which time is set right now and substract 1 hour from that?

**Comment by rand256** [comment]
No it isn't since there's huge amount of timezones in the world and you won't be able to track them all.
So in cf158076fd4fd468de29a4168ba3f2f9940425f4 I've replaced cron module with the one supporting Daylight Saving Time. Probably should get better. In my country there's no DST now, though.

**Comment by nicedevil007** [comment]
The Winter/Summertime will be abandoned in europe in the near future :)
But isn't it easy to compare the time of the linux system with the setup timer for zoned cleaning?
The time in ubuntu should be always the right one, using my Sophos UTM as NTP server :)

oh forgot: will test the new release as always :) you can't imagine how much we (my girlfriend as well) like your version of valetudo!

**Comment by nicedevil007** [comment]
Ok Rand256, my test was setup for 19:00... the robot started at exact 19:00 :)
My girlfriend is lucky now hehe.

One little improvement... a button to enable autorefresh of the map while the robot is running around the flat?

**Comment by rand256** [comment]
The thing is not everyone can setup required timezone in linux console. Setting it via the website is much easier.

Regarding refreshing the map, it should be refreshing automatically during the cleaning (and for me it surely does work fine). If it doesn't for you, please open another ticket.
