### ISSUE TITLE
Viomi v7 support

### ISSUE THREAD

**Issue by 8times4** [rand256/valetudo#400]
Hey @rand256 

Is it possible to get this to work on a Viomi v7?
Regular Valetudo from Hypfer works, but just replacing the binary does not.
The conf file does not really work since it's probably meant to be for debian based robots, but I'm just wondering if I'm doing anything wrong?

Thanks,
Mark

**Comment by rand256** [comment]
> Is it possible to get this to work on a Viomi v7?

It will be possible only if someone writes the new code. For now it is missing - RE supports only roborock devices.

**Comment by 8times4** [comment]
Oh, so RE was forked when Valetudo only supported roborock, got it thank you, appreciate the answer.
