### ISSUE TITLE
WiFi not working after installing latest valetudo re version

### ISSUE THREAD

**Issue by dwainscheeren** [rand256/valetudo#413]
**Describe the bug**
WiFi not working after installing latest valetudo re version

**How to Reproduce**

Install latest Valetudo RE version 0.10.5

**Expected behavior**

Flashing or solid wifi light and wifi connection

**Vacuum Model:** 
Gen2 S55

**Valetudo Version:** 
0.10.5

**Additional context**

I flashed my S55 to the latest Valetudo RE version yesterday and now it won't connect to the WiFi anymore. The wifi indicator light is fully of and at no position turning on or flashing.

I tried holding the wifi reset buttons (dock and spot clean) for 5 seconds but it only wants to start a spot cleaning. I also did a paperclip in the reset button but it only does a reboot no factory reset anymore. I already tried turning it on and off again for more then 20x. There is also no fallback hotspot generated on the roborock.

I don't find anyone with this problem online.

**Comment by pidator** [comment]
What base firmware did you install?
Concerning factory reset: did you follow [these instructions](https://support.roborock.com/hc/en-us/articles/360035072251-How-do-I-factory-reset-my-Roborock-S5-)?

**Comment by NovalisVonHardenberg** [comment]
Did you choose the right version?
Generation 1: version 4028
Generation 2 (Roborock S5): version 2034

**Comment by dwainscheeren** [comment]
This can be closed. I did a complete factory reset as @pidator told me (didnt found that one before) then reinstalled valetudo
