### ISSUE TITLE
Support for Valeronoi

### ISSUE THREAD

**Issue by atomphil** [rand256/valetudo#414]
Is there a way to use [Valeronoi](https://github.com/ccoors/Valeronoi) with this firmware?

**Comment by pidator** [comment]
You're asking in the wrong project: Valeronoi uses endpoints provided by valetudo to work. So if you want Valeronoi to work with RE, the change will have to be in Valeronoi to support the RE endpoints too. There's nothing to be done in RE.

**Comment by atomphil** [comment]
Oh I didn´t see this: [https://github.com/ccoors/Valeronoi/issues/9](https://github.com/ccoors/Valeronoi/issues/9) ... so no way :-/

**Comment by doemEINS** [comment]
You could [try this](https://github.com/rand256/valetudo/issues/405#issuecomment-804878999), if you want to create a wifi heatmap with Valeronoi only once.

**Comment by doemEINS** [comment]
Can we close the issue?

**Comment by rand256** [comment]
Sure.
