### ISSUE TITLE
 entity “sensor.map_segments” not visible in Home Assistant

### ISSUE THREAD

**Issue by Trufax** [rand256/valetudo#421]
**Describe the bug**

i added the Roborock to Home Assistant via MQTT however i cannot find the entity: ´“sensor.map_segments”  to list rooms. Only one entity is published which is "vaccum.roborock" which gives me basic features like start, stop etc but does not show rooms. 

**How to Reproduce**

Add Roborock to Home Assistant via MQTT and search for the entity:  ´“sensor.map_segments” 

**Expected behavior**

I should be able to find the entity  ´“sensor.map_segments”  in my entity list to figure out the IDs for rooms

**Screenshots**

**Vacuum Model:** 
v0.10.5
**User-Agent** 

**Additional context**

**Comment by labaland** [comment]
> **Describe the bug**
> 
> i added the Roborock to Home Assistant via MQTT however i cannot find the entity: ´“sensor.map_segments” to list rooms. Only one entity is published which is "vaccum.roborock" which gives me basic features like start, stop etc but does not show rooms.
> 
> **How to Reproduce**
> 
> Add Roborock to Home Assistant via MQTT and search for the entity: ´“sensor.map_segments”
> 
> **Expected behavior**
> 
> I should be able to find the entity ´“sensor.map_segments” in my entity list to figure out the IDs for rooms
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Vacuum Model:** <!-- e.g. Gen2->
> Roborock S5 (Gen2)
> 
> **Valetudo Version:**
> v0.10.5
> **User-Agent**
> 
> **Additional context**



I have the same issue. Did you fix it ?

**Comment by labaland** [comment]
edit: found this page: 
https://github.com/rand256/valetudo/wiki/REST-API
