### ISSUE TITLE
MQTT doesn't work after updating

### ISSUE THREAD

**Issue by jensimbenz** [rand256/valetudo#424]
Describe the bug
MQTT does not work after the latest update to Valetudo RE 0.10.6

How to Reproduce

Install latest Valetudo RE version 0.10.6

Expected behavior

MQTT working, seamless connection to MQTT Broker in Home Asistant

Vacuum Model:
Gen2 S5

Valetudo Version:
0.10.6

Additional context

I flashed Valutudo RE to 0.10.6 but afterwards, connection to Home Assistant was lost. Tried to reset MQTT in Valuetudo, HA, restarted the robot and flashed the FW again. Nothing helped.

**Comment by LEJOUI** [comment]
Same here. Download the latest .deb file from the releases. Could it be that the new binaries aren’t available yet?
It still produces the same error as mentioned in #423

**Comment by rand256** [comment]
Please try again.

Also it is not the whole MQTT stopped working but HA autodiscovery didn't like water-related options.

**Comment by LEJOUI** [comment]
Thanks! Got it working by downloading the new .deb!
