### ISSUE TITLE
How to install official language packs?

### ISSUE THREAD

**Issue by mayonezo** [rand256/valetudo#428]
I want to install the official German language pack by roborock, but I don't know where to get it from. I had it working before, but I don't know how. After a switch to the original Valetudo and back to RE, my roborock now only speaks English.

**Comment by pidator** [comment]
You can use [this site](https://vacuumz.info/download/voice/) to download different language packs.

Edit:
This is not an issue, it's more a discussion topic.

**Comment by mayonezo** [comment]
I am aware but I did not know where to discuss this. Thanks for the link, but as far as I understood these are tts language packs created by the community? I am looking for the official ones by roborock.

**Comment by mayonezo** [comment]
Ah sorry, I overlooked the 2008 folder, my bad!

**Comment by mayonezo** [comment]
Thanks for the help!

**Comment by pidator** [comment]
> I am aware but I did not know where to discuss this. 

Look at the top of the github page, there's an [discussion tab](https://github.com/rand256/valetudo/discussions).

> Thanks for the link, but as far as I understood these are tts language packs created by the community? I am looking for the official ones by roborock.

There are no "official" soundpacks provided by roborock, all packs you'll find are created by users of the community by providing the sound files of rooted devices.

> Thanks for the help!

yw
