### ISSUE TITLE
How to install sox

### ISSUE THREAD

**Issue by githluapb** [rand256/valetudo#429]
I update via [this method](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) and do not have sox installed. Can anybody please instruct me how to install sox via cli, since pkgs or apt-get are not present?
Thanks from a linux newbie.

**Comment by pidator** [comment]
hi,
(unfortunately again) this is no issue of valetudo re, it's more a [discussion](https://github.com/rand256/valetudo/discussions) topic about the fimware building process.

if you just upgraded by replacing the binary, sox wasn't installed before either. the easiest way is to to create your own image by using e.g. [this builder](https://github.com/zvldz/vacuum) with including sox installation.

**Comment by githluapb** [comment]
Thx for pointing me to discussions. Learned the difference.
