### ISSUE TITLE
Gen1 EU prebuilt firmware

### ISSUE THREAD

**Issue by joasag** [rand256/valetudo#43]
Hi,

I installed the standard Valetudo before finding this which is much more up to date. I have two questions, on the regular Valetudo version 4004 is not recommended. Is it safe to use on Valetudo RE?

Next question, is the vacuum_2eu_4004.pkg from https://vacuumz.info/download/gen1/ a prebuilt firmware with Valetudo RE with EU version? Or is this stock firmware? Or stock Valetudo?

Thank you!

**Comment by zvldz** [comment]
> Next question, is the vacuum_2eu_4004.pkg from https://vacuumz.info/download/gen1/ a prebuilt firmware with Valetudo RE with EU version? Or is this stock firmware? Or stock Valetudo?
> 
> Thank you!

Firmware containing Valetudo in the file name contains valetudo (ex: vacuum_valetudo_re_4004.pkg)
For more information about filenames, see here - https://vacuumz.info/download/changes.txt

**Comment by joasag** [comment]
@zvldz Great! What about firmware versions? Is 4004 the recommended one?

**Comment by zvldz** [comment]
> Great! What about firmware versions? Is 4004 the recommended one?

Modified firmware contains the miio-client version 3.3.9(with local ota). Original firmware versions without local ota.
