### ISSUE TITLE
Cant see vacuum/charger on map (InvalidStateError: CanvasRenderingContext2D.drawImage)

### ISSUE THREAD

**Issue by nortuzar** [rand256/valetudo#452]
**Describe the bug**
Suddenly the vacuum disappear from the map, also the dock station. When I click the map page, the following message appear
`InvalidStateError: CanvasRenderingContext2D.drawImage: Passed-in canvas is empty`

**How to Reproduce**

1. Go to web
2. Press MAP page

**Expected behavior**

See the charger and vacuum on the map

**Screenshots**

![image](https://user-images.githubusercontent.com/55258023/124005292-e386e880-d9a6-11eb-8f80-c5d2aa3e6f39.png)
![image](https://user-images.githubusercontent.com/55258023/124005401-06190180-d9a7-11eb-90b4-1633691cfa03.png)
**Vacuum Model:** 
Gen1

**Valetudo Version:** 
0.10.7

**User-Agent** 
Firefox 89.0.2 (64-bit)

**Additional context**

It was working great, I didn't change anything or did an update

**Comment by pidator** [comment]
Do you already tried a reboot of the robot (e.g. via settings - persistent data & system settings - reboot device)?

**Comment by nortuzar** [comment]
Rebooted like 3 times previous to this post but nothing. I don't know why but suddenly all start working as usual

Think the reboot process help. 

Thanks for your quick reply, will close the thread
