### ISSUE TITLE
Telegram Bot settings Password only allow 20 characters

### ISSUE THREAD

**Issue by 6490dk** [rand256/valetudo#456]
A New telegram Bot Set a 38 characters Password. Please allow more than 20 char.

**Comment by rand256** [comment]
Don't you confuse a password with the telegram API token? A password is what you think up yourself as a measure to prevent other people using your bot, and a token is what you get from telegram so the bot could authenticate in telegram's API. The password doesn't need to be that long.

Anyway if you really need it by some reason, you can manually edit `/mnt/data/valetudo/config.json` when valetudo is turned off and specify the password of any length there.

**Comment by 6490dk** [comment]
Oh yes. Sorry my mistake
