### ISSUE TITLE
Roborock not sending map data via MQTT

### ISSUE THREAD

**Issue by jszust** [rand256/valetudo#459]
I have gone back and forth with a 2nd roborock and I cannot get it to send map data via MQTT. The config file is set to "true" to send map data, but it is not being sent despite being connected to the MQTT server and sharing attributes and other messages. Is there any way to ping the roborock to try and force-send map data? Is the only option here a full reset and clean install?

**Comment by DivanX10** [comment]
I am trying to add a map to the Home Assistant through this integration, but the map is not displayed. How can I display the card in the Home Assistant?
https://github.com/TheLastProject/lovelace-valetudo-map-card

Vacuum cleaner Model Gen1 SDJQR01RR
ValetudoRE v 0.10.7
Home Assistant 2021.8.8

In the file config.json
`
  "timers": [],
  "ztimers": [],
  "mqtt": {
    "enabled": true,
    "identifier": "rockrobo",
    "topicPrefix": "homeassistant",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://XXXXXXX:XXXXXXXXX@192.168.1.47:3489",
    "provideMapData": true,
    "caPath": "",
    "qos": 0

`
I can see the map through MQTT Explorer
![image](https://user-images.githubusercontent.com/64090632/131522048-e3f243ee-a611-4c99-b1ac-e4b2a84b3c29.png)

In HomeAssistant, I subscribed to the topic homeassistant/rockorbo/map_data and no data is received in HomeAssistant
![image](https://user-images.githubusercontent.com/64090632/131522192-69c94c19-dd3f-4093-9492-866b552715d4.png)

In the integration itself, I have only one vacuum cleaner visible and no map
![image](https://user-images.githubusercontent.com/64090632/131522677-3f066be5-d891-4f55-a636-1ddefdd45845.png)

**Comment by rand256** [comment]
> I can see the map through MQTT Explorer

This isn't a map itself, it is a binary packed map data.
You can create an image from that data using valetudo-mapper companion app.

**Comment by jszust** [comment]
> > I can see the map through MQTT Explorer
> 
> This isn't a map itself, it is a binary packed map data.
> You can create an image from that data using valetudo-mapper companion app.

Yes this was the issue, and I figured it out shortly after creating the issue which is why I closed it soon thereafter. Thanks for your great work and constant support on the project!

**Comment by DivanX10** [comment]
I installed the [Valetudo RE Mapper addon](https://github.com/Poeschl/Hassio-Addons/tree/master/valetudo-mapper), the map camera appeared. I added the camera via picture-glance. Do I understand correctly that [this integration](https://github.com/TheLastProject/lovelace-valetudo-map-card) is not suitable for Valetudo RE Mapper?



```
type: picture-glance
title: Vacuum
entities:
  - entity: vacuum.rockrobo
camera_image: camera.rockrobo_map
camera_view: live
entity: vacuum.rockrobo
```
And do I understand correctly that these are two integrations for different versions of Valetudo?
ICantBelieveItsNotValetudo for Valetudo без RE
Valetudo RE Mapper for Valetudo RE

**Comment by pidator** [comment]
> And do I understand correctly that these are two integrations for different versions of Valetudo?
ICantBelieveItsNotValetudo for Valetudo без RE
Valetudo RE Mapper for Valetudo RE

`valetudo` and `valetudo RE` are two different projects and every project has it's own companion services, yes.
