### ISSUE TITLE
[Feature Request] Allow Multiple Vacuum cleaner with one instance of Valetudo Mapper

### ISSUE THREAD

**Issue by thundergreen** [rand256/valetudo#465]
Hello,

I just got my second Xiaomi Rickrobo Cleaner and now i am facing the issue that i cannot get the map through the addon but firectly from the robot. Is there any way to manage two Robots in the same time?

**Comment by pidator** [comment]
why not running a second instance of valetudo mapper for your second robot?

_Edit:_
like it is described at the [valetudo mapper readme page](https://github.com/rand256/valetudo-mapper/blob/master/README.md):
> You can also run a multiple instances of a single valetudo mapper with different configuration files. For this start the instance with ./node app.js -f /path/to/config.json. You may also need to add the -c key to generate a new custom config file if it doesn't exist.

**Comment by thundergreen** [comment]
OK. got it working thanks.
