### ISSUE TITLE
[Question] Compatibility with Dreame F9 ?

### ISSUE THREAD

**Issue by Mickey016** [rand256/valetudo#467]
Hi,

 Now that valetudo runs on new brands / models like Dreame D9 and F9, should we expect the same type of compatibility for an upcoming update of Valetudo RE ?

Anyway, huge thanks for your work 👍🏻

**Comment by rand256** [comment]
Probably not.
I have the only Roborock S50 and see no way how could I support other devices from other manufacturers.

**Comment by Mickey016** [comment]
I understand.
I will keep on using Valetudo RE on my S50 and stay with classic Valetudo on my Dreame.

Keep up the good work mate !

**Comment by teras** [comment]
A similar question, a year or so later :)
I have a Dreame Z10 Pro which is an awesome vacuum cleaner, especially with valetudo firmware. 

Are there any plans and/or any way I can help to use Valetudo RE (which seems to be more wanted than original firmware) with this device?

Thank you dor your work anyway :smile:

**Comment by Ulrar** [comment]
Overall the doc says gen2 devices and gen3 devices, with a few examples but how to figure out if a given device is gen2 or 3 is not clear to me.
Is the D9 just not even falling in either category ?

**Comment by rand256** [comment]
Again, valetudo RE supports a number of (rather old) Roborock devices, and D9 or Z10 or anything are devices from even a different manufacturer, not Roborock. So nope, it's falling in neither category.
