### ISSUE TITLE
Can't flash firmware

### ISSUE THREAD

**Issue by tarteAuxPommes** [rand256/valetudo#471]
Hello,

I tried to flash my Roborock S50 but it doesn't work.
I can choose the firmware but in mirobo.php, the following line return false in flash_firmware function.
`if($result=$this->device->firmware_install("{$this->webserver->url}/firmwares/$name",md5_file($firmware))) {`

But the in the following line, the "error" property is NULL. So i'm stuck without knowing what's the issue.
`$this->write("Sending firmware Err: <c:red>{$this->device->error}</c>", true);`

I tried to flash voice package and it worked.

Can you help me ?

**Vacuum Model:** 
Roborock S50
**Valetudo Version:** 
None

**Comment by rand256** [comment]
Device with original unpatched fw version higher than 1910 can't be flashed via the traditional ways. You need to downgrade fw to 18xx via factory reset and try again. If you flash patched fw then, you will be able to use mirobo in newer versions too. Installed Valetudo RE provides another way to flash a new firmware via its Web UI.
