### ISSUE TITLE
Update to the new Valetudo base? 

### ISSUE THREAD

**Issue by MaluNoPeleke** [rand256/valetudo#475]
**Describe the bug**

Is there a plan to use the new Valetudo 2021 build as a base? 

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Vacuum Model:** 

**Valetudo Version:** 

**User-Agent** 

**Additional context**

**Comment by pidator** [comment]
See comment https://github.com/rand256/valetudo/discussions/469#discussioncomment-1594934

**Comment by MaluNoPeleke** [comment]
Thanks
