### ISSUE TITLE
Trouble connecting to wifi S50 G2

### ISSUE THREAD

**Issue by torsteinelv** [rand256/valetudo#479]
Hello,

It not possible to connect my device to wifi. Im running vacuum_2034_valetudo_re_0_10_7.pkg
After setting wifi it does not connect. tried turning 5ghz off but does not help,

**Comment by pidator** [comment]
Any special characters in your SSID?

**Comment by torsteinelv** [comment]
No. And not in the password also.

**Comment by torsteinelv** [comment]
Is there anything that i can test here? My wifi setup is Ubiquiti UniFi 6 Lite with default setup.

**Comment by pidator** [comment]
Do you have a long password (iirc there's a limit between 40 and 50 chars)?

_edit:_
The S50 only supports 2.4ghz by the way.

**Comment by torsteinelv** [comment]
8 letters long password 3 long ssid. 

Yes i have tried to disable 5ghz

**Comment by torsteinelv** [comment]
No one knows what this is?

**Comment by pidator** [comment]
I can't explain why the wifi settings via valetudo re webgui aren't applied at your robot.

You can try to use [mirobo tools](https://python-miio.readthedocs.io/en/latest/api/miio.integrations.vacuum.roborock.vacuum.html?highlight=Wifi) directly  to set the wifi credentials while connected to the robot ap. So you'll bypass all valetudo re logic...

**Comment by torsteinelv** [comment]
Is the usb under the cover a serial console? Or do i need to connect with ssh over the wifi hotspot?

**Comment by torsteinelv** [comment]
btw it looks like this.:
https://www.google.com/url?sa=i&url=https%3A%2F%2Fprisguiden.no%2Fprodukt%2Fxiaomi-mi-robot-vacuum-2-roborock-mi-s5-s50-s55-321019&psig=AOvVaw3YvXXgp8kd7ZmHJXrti47k&ust=1643203526329000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPiE34WAzfUCFQAAAAAdAAAAABAE

This is gen2 right?

**Comment by pidator** [comment]
> This is gen2 right?

> Im running vacuum_2034_valetudo_re_0_10_7.pkg

Yes, should be Gen2 and if your successfully running 2034, it is definitely Gen2 :)

> Or do i need to connect with ssh over the wifi hotspot?

You need to connect to the wifi hotspot and run python miiotools from your laptop/pc. See [wiki section](https://github.com/rand256/valetudo/wiki/Installation-process#flashing-from-macos-or-linux) about the flashing. Setting the wifi credentials is another miio command...

**Comment by torsteinelv** [comment]
I tried command mirobo --ip 192.168.8.1 --token mytoken configure-wifi ssid password.

But I cant see my roborock on the  wifi still

**Comment by torsteinelv** [comment]
Tried to SSH into the roborock. and I can find the updated wifi settings. Is there any way to find any log here or do some troublesooting here?

Also i wanted to try to reinstall the valtudo re file as explained here but dpkg command is not found:
https://github.com/rand256/valetudo/wiki/Installation-process#flashing-from-macos-or-linux

**Comment by torsteinelv** [comment]
Thats wierd. Managed to connect my vacuum cleaner to a different network. So it has to be something with my network then. What i think i wierd is that this cleaner was connected to this network before the firmware upgrade. Anyone know the requirements for the network?

**Comment by pidator** [comment]
> Anyone know the requirements for the network?

All requirements are already stated in this threat. So I suspect something is wrong with your firmware installation. Do you already consider a [factory reset](https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Robots-Factory-Reset) to have a "clean system" again and then flash the new image again?

**Comment by torsteinelv** [comment]
I have loaded the firmware several times now and now it works suddently. Have no Idea why.

**Comment by torsteinelv** [comment]
This case can be closed.
