### ISSUE TITLE
Feature request: Safe zones

### ISSUE THREAD

**Issue by Twsts** [rand256/valetudo#48]
Hi! 

Thank you for your effort and continuous updates to this project!

I have a carpet with black spots wich the vacuum get stuck on. Figured out to be the cliff sensors triggering keeping the robo from going onto the black area.

Would it be possible to have Valetudo temporarily disable the cliff sensors inside a specific zone, much like the forbidden zones but making them "safe" instead?

**Comment by rand256** [comment]
Unfortunately Valetudo only works with standard functionality of the device (in example: goto _there_, start zoned cleaning _here_, return to base _now_). In fact it just sends known commands to the blackbox of origin software.

AFAIK still nobody tried (or succeeded in) hacking into that blackbox to change something in it, so right now there's no way to turn off cliff sensors programmatically.
