### ISSUE TITLE
Enhancement: Charge limit

### ISSUE THREAD

**Issue by astrakid** [rand256/valetudo#497]
hi,
just a general question: is it possible toconfigure a charge limit? i have two reasons for this:
1. general battery health improvement: charging over 80% or 90% is not optimal for LiIon batteries
2. in my special case i have an issue with my battery: when about 80% is reached i got error 13 and my vaccum is leaving the charger after some unsuccessful retries. i guess a kapacitor is defect on the mainboard, but i don't want to change it (i am afraid i will damage my vacuum)

kind regards,
andre

**Comment by pidator** [comment]
See https://github.com/rand256/valetudo/issues/393

**Comment by astrakid** [comment]
oh cool, thanks for the link. didn't find it before, i guess i searched like a novice...
