### ISSUE TITLE
[Feature Request] Overriding Errors

### ISSUE THREAD

**Issue by alexb4a** [rand256/valetudo#500]
My old Roborock S5 with Valetudo started giving the 106 Error: Left Wheel Open Circuit.
I bought a new set of wheels and replaced both with no luck. I know for a fact that the new wheels are working as I tested those in another unit, so it seems something else.
Can Valetudo implement something in order to ignore such errors and keep on cleaning even the infamous 106 Error shows up, when you are positively sure the wheels are working? Perhaps a "Ignore error 106" switch somewhere in the configs?

**Comment by rand256** [comment]
There's no such switch in available configs I'd be aware of.
In fact there's very little we can do with all the default parameters at all.
