### ISSUE TITLE
Cannot select room if an object is in center

### ISSUE THREAD

**Issue by oddomatik** [rand256/valetudo#503]
**Describe the bug**
If a room has an object (blank spot on map) in its center, I can't select the marker for the room

**How to Reproduce**
A permanent object in the center of the room renders the room selection marker useless. It displays, but will not allow selection.

**Expected behavior**
I would expect to be able to select a room regardless of the location of a bedside chest, in this example.

**Screenshots**
<img width="681" alt="Screen Shot 2023-07-14 at 10 58 14 AM" src="https://github.com/rand256/valetudo/assets/1700712/674b3429-6447-4e3a-b250-73561401c3b2">

**Vacuum Model:** 
 Roborock S7

**Valetudo Version:** 
 2023.04.0

**Browsers tried:**
 Firefox and Brave (Chrome-based), latest versions

**Comment by rand256** [comment]
You're in the wrong repository, this one is for an old Valetudo RE fork, which looks different from your screenshot, has different version numbering and (most likely) doesn't have this issue.

**Comment by oddomatik** [comment]
Apologies for not paying attention!
