### ISSUE TITLE
How to change the Web UI to Traditional Chinese language?

### ISSUE THREAD

**Issue by nnttd** [rand256/valetudo#509]
First of all, thank you for providing such a perfect program. I am currently enjoying using it! I am located in Taiwan, and Traditional Chinese is my native language. I would like to change the Web UI to Traditional Chinese. I have already translated en.json into tw.json. However, I am not a software developer and not familiar with Linux system operations, so I don't know what to do next to apply the file to the Web UI of my current robot vacuum. I can provide the translated tw.json file. Could you please help me add it to the language support? Or can you tell me what to do next? Attached is the tw.json file I have translated. Thank you for your assistance!"
[tw_json.zip](https://github.com/rand256/valetudo/files/12642198/tw_json.zip)

**Comment by rand256** [comment]
well, i guess the easiest way in this case would be if i'll add your translation into the next build myself.
i'll try to release it soon then. thanks for your efforts!

**Comment by rand256** [comment]
i have just released version 0.10.10 which includes your translation.

**Comment by nnttd** [comment]
Thank you very much for your assistance. I am happily enjoying this user interface with Traditional Chinese language support!
