### ISSUE TITLE
WPA3 Wi-Fi Network Fails to Connect Successfully

### ISSUE THREAD

**Issue by NathanMott** [rand256/valetudo#521]
**Describe the bug**
Using a WPA3 only Wi-Fi network the Valetudo initial network setup wizard mentions it completes successfully and you hear the robot say wifi network connected. Sadly, the device never connects to the network.

**How to Reproduce**
1) Setup an SSID on your wireless access point with WPA3 only
2) Power on the robot vacuum
3) Connect your laptop/device to the temporary SSID that is used for Valetudo network setup wizard
4) Enter the WPA3 only SSID information into the wizard and press "apply"
5) After a little while you will hear the robot vac mention it has successfully connected to the WiFi network but you will no longer be able to access the robot. No robot vacuum device will end up connecting to the WiFi network.

**Expected behavior**
The robot vacuum should connect to the WPA3 WiFi network.

**Screenshots**
N/A

**Vacuum Model:** 
Dreame L10S Ultra

**Valetudo Version:** 
Release 2024.02.0

**User-Agent** 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

**Additional context**

Based on some of my own investigation it seems “/data/config/wifi/wpa_supplicant.conf” key_mgmt is configured to only “WPA-PSK”. This is incorrect for WPA3 only SSIDs as per the below documentation and should be “key_mgmt=SAE”

https://wiki.archlinux.org/title/wpa_supplicant#Connections_to_pure_WPA3-SAE_access_points

Manually changing the wpa_supplicant.conf config file for WPA3 and running “wpa_cli reconfigure” displays “fail”. Following this logic it seems the wpa_supplicant binary might not have been complied with “CONFIG_SAE=y” flag. Guessing some testing should be done and a new release build created. 
https://superuser.com/questions/1742672/getting-error-while-configuring-wpa-spplicant-in-wpa3-sae-mode

**Comment by pidator** [comment]
You're asking in the wrong repo, this fork of valetudo doesn't support Dreame robots.
