### ISSUE TITLE
Fresh Build by myself won't work anymore

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#54]
Hey Rand,

I build a script to  compile valetudo each evening from your git repo. Worked realy well for the last few month. Since some days I get this error and I don't know how to fix, is there anything I missed for compiling by myself?

![image](https://user-images.githubusercontent.com/17103076/70944382-3f9f4b80-2053-11ea-93a8-e1f94c43940e.png)

**Comment by rand256** [comment]
Looks like a bug in pkg package, its author has forgotten to upload or even build arm binaries. For now you should be able to workaround it changing pkg dependency in package.json from `^4.4.0` to just `4.4.0`, it will downgrade then back to correctly working version.

**Comment by nicedevil007** [comment]
@rand256 
![image](https://user-images.githubusercontent.com/17103076/71306927-6230bc00-23e7-11ea-9f51-714f078c972e.png)

this is what the original package.json looks like :/
so pkg is on 4.4.0

what should this line looks like if I compile everything on my x86 server? 

`pkg --targets node10-linux-armv7`

**Comment by rand256** [comment]
> so pkg is on 4.4.0

Now it is, I've changed **^4.4.0** to **4.4.0** in package.json after I wrote my previous reply.

> what should this line looks like if I compile everything on my x86 server?

It should look the same. The thing is you can either compile it on armv7 system using build scripts included with pkg, or use some third party cross-compiling tools on x86_64, which aren't a part of pkg package.

**Comment by nicedevil007** [comment]
So I tryed again :/

![image](https://user-images.githubusercontent.com/17103076/71323646-a306fe80-24d5-11ea-833b-f841b6c0de23.png)

**Comment by nicedevil007** [comment]
maybe it is because there is no armv7 version of v10.17.0 ?

![image](https://user-images.githubusercontent.com/17103076/71323986-c469e980-24d9-11ea-9a44-71b45d31629e.png)

**Comment by rand256** [comment]
I've wrote that [5 days ago](https://github.com/rand256/valetudo/issues/54#issuecomment-566528755). Though I don't know why you can't rollback to pkg v4.4.0 with node v10.15.3, it should work like it used to for months before.

**Comment by nicedevil007** [comment]
I also got rid of the 2 missing dependencys by adding utf-8-validate and bufferutil

![image](https://user-images.githubusercontent.com/17103076/71324077-c5e7e180-24da-11ea-96ac-a865b2015f59.png)

**Comment by nicedevil007** [comment]
> I've wrote that [5 days ago](https://github.com/rand256/valetudo/issues/54#issuecomment-566528755). Though I don't know why you can't rollback to pkg v4.4.0 with node v10.15.3, it should work like it used to for months before.

Ah nodejs v10 should be installed so :)

![image](https://user-images.githubusercontent.com/17103076/71324090-ea43be00-24da-11ea-9f4b-3197edff1d35.png)

Dunno, ubuntu repos still got version 8 in it :/

sry for missunderstanding :(

**Comment by rand256** [comment]
No it shouldn't! You don't need to have any node.js for packaging. 

The issue is that you still have pkg 4.4.2 and it tries to use 10.17.0 which doesn't exist for armv7. You need to remove that version of pkg and return back to 4.4.0.

**Comment by rand256** [comment]
Probably you actually need to downgrade pkg-fetch which is a dependency of pkg.

**Comment by nicedevil007** [comment]
I'm not that familiar with npm :/ And npm help npm can't help me out for finding a solution to even see all my installed packages and their versions or even a way to install older verions over the latest one.

So I will stop compiling valetudo by myself. Don't want to stress you than I did right now :)
It Xmas.
