### ISSUE TITLE
Feature Request: Option to start a fresh map

### ISSUE THREAD

**Issue by Duncank** [rand256/valetudo#57]
With the ability to save and load multiple maps I'd like to create a new map for each floor of my house. However, there is no way to clear the currently loaded map and start creating a new one. I feel like the vacuum isn't vacuuming the entire floor now if it isn't on the ground floor.

**Comment by rand256** [comment]
>  there is no way to clear the currently loaded map and start creating a new one

Settings -> Persistent Data -> Reset map.

**Comment by Duncank** [comment]
I feel stupid now; I didn't see that option, but it works perfectly! The forbidden zones etc are all saved in a previously saved map, so now I can switch to the newly created map.
