### ISSUE TITLE
Feature request: dark mode

### ISSUE THREAD

**Issue by CodeFinder2** [rand256/valetudo#58]
A dark mode (toggle button in menu) would be nice, like in pure valetudo, see https://github.com/Hypfer/Valetudo/pull/374

Maybe this can simply be migrated to this repo?

Thank you!

**Comment by rimrul** [comment]
Probably needs some changes to the CSS, since Valetudo and Valetudo-RE use different OnsenUI versions as of 9647c626. All commits appart from Hypfer/Valetudo@0665991f could probably be cherry-picked.

**Comment by CodeFinder2** [comment]
Seems to be implement / working fine for me, see also https://github.com/rand256/valetudo/commit/0e2d863c50057eb12a22ff58dcc3465293789e3c . Will close this issue. 

Thank you very much! 🙂
