### ISSUE TITLE
Can't get out of Cleaning History

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#6]
Hey rand256,

I saw u made an update for the cleaning history. 
I made a new valetudo file from your source and just want to test a bit. 

Found out, that you are not able to get out of the Cleaning History after clicking on one Cleaning Run. Maybe thats because there is actual no map associated to this entry (there was no cleaning since this update).

**Comment by rand256** [comment]
Sorry, it was a bug, there was a file missing in the commit. It was reuploaded now.

The worst thing which may actually happen with cleaning history maps is it could in some cases not be able to load the map fast enough and will show just normal map instead of it.

**Comment by nicedevil007** [comment]
I can confirm, after recompiling it runs like a charm... just in some rare situations the map isn't loaded.
