### ISSUE TITLE
Accidentally overwrote rc.local

### ISSUE THREAD

**Issue by fillilutten** [rand256/valetudo#60]
I didn't read the instructions carefully enough so instead of adding the lines in rc.local I overwrote the file. Could anyone post the rc.local as it should be? 

Thanks!

**Comment by rand256** [comment]
Generally it's almost empty. Looks like this:

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exit 0
```
