### ISSUE TITLE
After a certain uptime (several hours), map feature in the web UI no longer presents map

### ISSUE THREAD

**Issue by teixeluis** [rand256/valetudo#64]
Without any apparent reason, the map is no longer presented, showing up the message "Status: Connecting...".

In another occurence, a "dummy" map with vector drawn letters as the robot path (saying "NO MAP DATA" or something similar) would be presented.

The remaining features of the web UI appear to function normally.

The normal behavior is restored only after entering the console and performing a reboot.

It may be useful to have a feature in the UI to trigger a reboot, for these types of hanging scenarios. A watchdog timer addition/change that covers this issue could also help minimize frustration (in case it is not strictly a fixable software bug).

**Comment by teixeluis** [comment]
Btw I am using firmware 3.5.0 build 003532, and Valetudo RE version is 0.8.1

Normal robot features function normally nevertheless.

**Comment by Krazy998** [comment]
Also notices this issue with 0.8.1 I have noticed th map stops updating after about 1 hr in home assistant.

Issue was not there in my previous version 0.4.0-RE7.1

As you said restarting the robot fixes it.

**Comment by rand256** [comment]
> Issue was not there in my previous version 0.4.0-RE7.1

Was firmware version the same now and then?

**Comment by Krazy998** [comment]
Good question. I think i was running 1886 with 0.4.0-RE7.1. running 1898 image with 0.8.1

**Comment by teixeluis** [comment]
I'm guessing this may not be easy to reproduce. Haven't had more episodes of the problem since I opened the issue.

I'm using a gen1 vaccum btw.

**Comment by Krazy998** [comment]
I have a gen2 S50 bot and happens every couple of days mainly during cleaning. I notice the home assistant map stops refreshing. cleaning job completes. I reboot the robot and the map updates and I can see that everything is mapped as it should. It feels like the map display function / posting is failing after some time

**Comment by teixeluis** [comment]
In my case I am not using map transfer via MQTT. The robot have been quite stable afterwards, didn't have more occurences, and the uptime is a few days already. I have even been using the experimental multimap feature to reload the complete map. The feature seems to disable itself though ("Store map" and "Load map" buttons disappear when I open a new session or so).
