### ISSUE TITLE
Feature Request: remap power button to start a predefined zone cleanup

### ISSUE THREAD

**Issue by teixeluis** [rand256/valetudo#67]
This feature would be useful twofold: first, in gen1 vacuum cleaners the map is not persisted when you start a new cleanup, however when we define a zone that covers the entire house, and always select that zone cleanup, the stored map is always reused. Remapping the button to clean a predefined zone (e.g. the entire house) would preserve the same user experience, without losing the previous map. The second use would be for users who frequently clean a specific zone instead of the entire house, and are used to triggering the cleanup via the physical button, they could also benefit for this feature, even if having a gen2 vacuum cleaner.

I would expect something in the lines of: when the power button would be pressed, a default zone would be searched and a zone cleanup triggered. If it would not be defined (or enabled), it would assume the original behavior.

**Comment by rand256** [comment]
As far as i know, there's no way to remap physical buttons.

**Comment by teixeluis** [comment]
@rand256 I see. It's likely built into the native code that controls the robot. It's a whole different championship..

**Comment by teixeluis** [comment]
RoboController is the only process handling input from /dev/input/event0:

```
root@rockrobo:/proc/bus/input# lsof|grep -i "/dev/input/event0"
RoboContr   943         root   28r      CHR      13,64      0t0       4103 /dev/input/event0
RoboContr   943   954   root   28r      CHR      13,64      0t0       4103 /dev/input/event0
RoboContr   943   962   root   28r      CHR      13,64      0t0       4103 /dev/input/event0
RoboContr   943   963   root   28r      CHR      13,64      0t0       4103 /dev/input/event0
RoboContr   943   987   root   28r      CHR      13,64      0t0       4103 /dev/input/event0
RoboContr   943   988   root   28r      CHR      13,64      0t0       4103 /dev/input/event0
RoboContr   943   989   root   28r      CHR      13,64      0t0       4103 /dev/input/event0
```

Which appears to correspond to the AXP223 power chip:

```
root@rockrobo:/proc/bus/input# cat devices
I: Bus=0019 Vendor=0001 Product=0001 Version=0100
N: Name="axp22-supplyer"
P: Phys=m1kbd/input2
S: Sysfs=/devices/platform/axp22_board/axp22-supplyer.20/input/input0
U: Uniq=
H: Handlers=kbd ddrfreq_dsm event0 cpufreq_interactive
B: PROP=0
B: EV=7
B: KEY=100000 0 0 0
B: REL=0

....
```

Kind of wondering if this is where button events come from..
