### ISSUE TITLE
Dustbin warning via MQTT [feature request]

### ISSUE THREAD

**Issue by p1ranha** [rand256/valetudo#70]
Telegram bot is able to send information if the dustbin is full, so this information is available to Valetudo.
Is there possibility to expose any information about dustbin via MQTT, so I could process it via HomeAssistant?

**Comment by JurajNyiri** [comment]
Any update on this?

**Comment by rand256** [comment]
In detail: there is some "Dustbin full" event received by valetudo from the device. As far as I understand, this is calculated by just the time passed from the previous dustbin extraction from the vacuum, regardless of its actual filling level, so at most points it is just useless.

But anyway, that can be added somewhere, but the thing is that it's just an "event", not a flag or a counter with a value set. How exactly do you propose to publish that information? It should be noted that there's no event of the dustbin being extracted I'd be aware of, so it can't be done by setting some flag to true on "dustbin full" and resetting to false on "dustbin extracted". The only thing possible to publish is the date when "dustbin full" event was received. Is it useful?

**Comment by AtticusG3** [comment]
I think it's useful, and I would like to see it on MQTT even if it is just a timedate stamp for last event recieved.
