### ISSUE TITLE
[Feature Request] Inline Keyboard Buttons for Telegram Bot

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#75]
Does  the telegram bot service support the inline keyboard feature?
It would be nice, if the control of the robot via the telegram bot could be performed with these buttons instead of typing the `/`-commands. 
I'm thinking of a usage like: The saved zone could be displayed as separate buttons, so you could start the cleaning of specific zone by simply pressing the belonging inline keyboard button.

**Comment by rand256** [comment]
What if you want to clean multiple zones at once? Is there a way for doing complex option selection? Fairly speaking, I'm not quiet sure how that inline keyboard feature works in telegram, I don't use this messenger on the regular basis since it's forbidden by law in my country.

**Comment by pidator** [comment]
> What if you want to clean multiple zones at once?

hm, haven't thought about selecting multiple zones at once. I don't know if the inline keyboard achieves a feature like this, seems not so trivial. I've rather thought about an easier way to perform the basic actions, like "start", "stop", "pause", "map", "going to the dock" or "cleaning one specific zone". I think this are features the inline keyboard can easily provide, like shown in this example:

![ea6163411c7eb4f4dc](https://user-images.githubusercontent.com/59822549/73456475-3e5f7f00-4372-11ea-98c5-0608538e0b16.png)

And the normal commands starting with `/` will continue to work, I think. 
So the inline keyboards should help the users to perform some default actions, the users who wants to do some special stuff can still use the  `/`-command.
