### ISSUE TITLE
Valetudo "updated" it self

### ISSUE THREAD

**Issue by Xento** [rand256/valetudo#76]
**Describe the bug**

I flashed a Valetudo firmware. And after that I found your version of valetudo.
So I downloaded the deb and installed it over the original valetudo installation.
It seemed to work but yesterday the robot says "no map data".
After a reboot it worked again and I got the map, but now is valetudo 0.4 installed again.
Even an ssh key I added was removed.

**Vacuum Model:** S5

**Valetudo Version:** 0.8.1

Log from today morning:
> No configuration file present. Creating one at: /mnt/data/valetudo/config.json
> Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
> Webserver running on port 80
> Loading configuration file: /mnt/data/valetudo/config.json
> Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
> Webserver running on port 80
> Connected successfully to mqtt server
> Loading configuration file: /mnt/data/valetudo/config.json
> Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
> Webserver running on port 80
> Connected successfully to mqtt server
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Connected successfully to mqtt server
> Robot connected
> Connected successfully to mqtt server
> Robot connected
> Robot connected
> Connected successfully to mqtt server
> Connected successfully to mqtt server
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Loading configuration file: /mnt/data/valetudo/config.json
> Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
> Webserver running on port 80
> Robot connected
> Connected successfully to mqtt server
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected
> Robot connected

**Comment by rand256** [comment]
You've "discovered" random factory reset/firmware rollback "feature" which happens to all valetudo-enabled robots. No solution for that. It is advised to use firmware image with disabled logging.

**Comment by Xento** [comment]
It wasn't a complete factory reset.
Map and other settings are still correct.
I thought when this occours the original firmware would be installed wich came with the robot.
When this is the random reset bug, than I only have to build a firmware with valetudo re 0.8.1 and than this would be flashed but persist the settings and map.

I added the both "fixes" for coredumps and watchdog manually.
Let's see if that helps.

**Comment by rand256** [comment]
> It wasn't a complete factory reset.

I wrote "random factory reset/**firmware rollback**" for a reason. There are two system partitions on the device. When it decides that something went wrong, it marks current partition as broken and  tries to rollback to another partition, which usually contains previously installed system. If second partition is also marked broken, it does complete factory reset.

> I added the both "fixes" for coredumps and watchdog manually.

It doesn't help.

**Comment by pidator** [comment]
> It is advised to use firmware image with disabled logging.

You're talking about the imagebuilder.sh option --disable-logs?
What's the effect of an firmware build with this option? What log files will (or won't) be created after setting this option? The robot still keeps the cleaning history and it's more about syslog?

Thanks!

**Comment by Xento** [comment]
Would it be possible to change the cmdline to use partition A again.
It would be possible that this prevents a factory reset.

Random reset / factory reset:
partition A -- on failure --> partition B
partition B -- on failure --> rescue partition

May be fixed when it would be possible to change the cmdline
partition A -- on failure --> partition B
partition B -- script changes cmdline  --> partition A
partition A -- on failure --> partition B
partition B -- script changes cmdline  --> partition A
.........
