### ISSUE TITLE
Json API results

### ISSUE THREAD

**Issue by jacekpaszkowski** [rand256/valetudo#83]
**Description**
Any option to get api results in JSON like in orginal Valetudo?
eg. i used to get api/map/lates in json for use in my Home Assistant.

**Vacuum Model:** D55

**Valetudo Version:** 0.8.1

**Comment by rand256** [comment]
The reason why we began using binary data instead of JSON is shotrly described [there](https://github.com/rand256/valetudo/releases/tag/0.4.0-RE6).
But yeah, sure we can rollback all those changesets for you. Or should we make a public poll first?

**Comment by jacekpaszkowski** [comment]
Poll is ok ;)

Or maybe you can tell me is there any way to get map json data in Valetudo RE? I also wasn't able to get it working over mqqt...

**Comment by rand256** [comment]
The link I've posted above has the answer to your question.
The same is written in valetudo-mapper readme.

**Comment by jacekpaszkowski** [comment]
I've seen that post. But vacuum doesn't publish any map data to mqqt broker. The topic shoud be valetudo/rockrobo/map_data? Right? I only get state and attributes over mqtt

**Comment by rand256** [comment]
It does. If you set `provideMapData` to "true" in mqtt block of `config.json`. Exactly the same as in original valetudo.

**Comment by b2az** [comment]
> The reason why we began using binary data instead of JSON is shotrly described [there](https://github.com/rand256/valetudo/releases/tag/0.4.0-RE6).
> But yeah, sure we can rollback all those changesets for you. Or should we make a public poll first?

![image](https://user-images.githubusercontent.com/20790250/83228116-fe74a100-a185-11ea-80a7-49abede67074.png)
