### ISSUE TITLE
auto spotcleaning after point on map

### ISSUE THREAD

**Issue by qweiniq** [rand256/valetudo#85]
when point a goto on map, have a button on the map for goto and clean the spot

**Comment by rand256** [comment]
The app currently doesn't have a command queue, and this can't be implemented unless it appears. Maybe somebody wants to code it?

Also, I'm not sure we want to fill the entire interface with more and more buttons.

**Comment by qweiniq** [comment]
Thanks for the answer. It was just an idea.
