### ISSUE TITLE
Bug with "You've attempted to choose X subzones..."

### ISSUE THREAD

**Issue by waclaw66** [rand256/valetudo#88]
**Describe the bug**

I getting messages like... **You've attempted to choose 7 subzones, while it is possible to use 5 subzones at most.** while selecting zones.

![obrazek](https://user-images.githubusercontent.com/15554561/72923735-ef9d5e00-3d4f-11ea-86de-42e67325d87d.png)

**How to Reproduce**

1. Create multiple zones
2. Select some zones on various order.

The count of possible selected zones depends on the order of selection, that's weird. sometimes I can select 4, another time only 2.
![obrazek](https://user-images.githubusercontent.com/15554561/72924222-dea11c80-3d50-11ea-95b6-f4c53c8af8f7.png)

**Expected behavior**

There should be possible to select up to 5 zones.

**Screenshots**

**Vacuum Model:** 
Gen 1

**Valetudo Version:** 
0.8.2

**User-Agent** 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

**Additional context**

**Comment by pidator** [comment]
I don't think it's a bug: the roborock api does allow only 5 zones to be send to the robot (5 rectangles you've created/saved)! 
So if your zones consists of two or more rectangles, each reactangle counts as a single zone. In your second screenshot, you'll have to count the numbers after the "/". Your first "saved zone" consists of 4 subzones plus the second selection of 1 zone. Now you've reached the maximum of 5 zones and for every following selection you'll got the error message.

![zones](https://user-images.githubusercontent.com/59822549/72926270-718f8600-3d54-11ea-889f-54b418216ec0.jpg)

**Comment by waclaw66** [comment]
Thanks for explanation!
