### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by thundergreen** [rand256/valetudo#89]
**Describe the bug**

In IcantBeliveItsValetudo I had atransparent background and here I get a blue one. how Can i change this into transparent again?
**How to Reproduce**

**Expected behavior**

**Screenshots**

**Vacuum Model:** 

**Valetudo Version:** 

**User-Agent** 

**Additional context**

**Comment by rand256** [comment]
So, obviously you want to edit the code that describes backgrounds. What's the bug?

**Comment by thundergreen** [comment]
I thought there might be an option to have transparent background 8n the configuration but hassio add-on complains that there's not such kind of option .where would be the line to make background transparent..I might change it manually then
