### ISSUE TITLE
version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 on RE4

### ISSUE THREAD

**Issue by Yax** [rand256/valetudo#9]
Valetudo-RE crashes on start.

```
root@rockrobo:~# /usr/local/bin/valetudo 
/usr/local/bin/valetudo: relocation error: /usr/local/bin/valetudo: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

The same error happens whether I compile valetudo manually, or use released one.

**Comment by rand256** [comment]
The reason for this is described on the [deployment](https://github.com/rand256/valetudo/tree/testing/deployment) page.

In short, newer pkg requires newer libstdc++.so library than is available on the original firmware, thus the error you see. However I just found a way to rebuilt Valetudo so now it should run without any external libstdc++.so at all. Uploaded new binary into releases page and updated deployment guide.

**Comment by Yax** [comment]
Ops. I didn't read the file. Just downloaded binary and scped into vacuum.

**Comment by Yax** [comment]
New release file works.
