### ISSUE TITLE
Map disappears after zooming in/enlarge

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#90]
I don't know if it's a bug or if it's a known issue. But I've some issue when zooming into the map. 

I open map tab, map is shown in "normal" size. Then I zoom in (enlarge the map). This is possible till it's reaches a specific size of the map. After this point is crossed, the map first went black in total (buttons + status is still shown), then it's shown only the blue background of map with status and buttons. No rooms or robot-ways are displayed any more. It doesn't matter if I zoom out and in, the rooms aren't shown anymore. It doesn't make any difference if I changes the tabs (e.g. go to home and back to map) -> still no rooms are shown anymore.

I will have to close the whole Valetudo website and open it again in a new browser window/tab, only then the map is shown again!

**Vacuum Model:** Gen1
**Valetudo Version:** 0.8.2

**Comment by rand256** [comment]
Works for me on current chrome. Though I haven't tried to spend hours for zooming in - maybe the issue could appear somewhere there.

Nonetheless you're right, probably there should be set some limit for zooming, for people who can't stop themselves in time.

**Comment by pidator** [comment]
hey rand, you're right, when using chrome I didn't have this issue, zooming works like a charm.
It seems to be an browser issue, I normally use opera...
With opera the issue appears after a short time of zooming ;) so a general limit where the zoom stops could be an solution.

**Comment by p1ranha** [comment]
Same happens on Safari (default in iOS), and with pinch to zoom, there is little control of how much you want to zoom in - it just goes all the way in.

**Comment by rand256** [comment]
Some things were changed in 0.9.0 beta2 related to this issue. Did it help?

**Comment by pidator** [comment]
> Works for me on current chrome. 

> Some things were changed in 0.9.0 beta2 related to this issue. Did it help?

Switched to chrome after you shared this information, but I will check both browsers again:

- In the chrome android app the zooming now stopps after a certain steps - erverything's fine!
- Updated opera app to the newest version (based on Chromium 78): same here - zooming stops and map isn't disappearing anymore! Great :+1: 
- Firefox desktop app: the limit for zooming is available here, too :-)

**Comment by pidator** [comment]
> Same happens on Safari (default in iOS), and with pinch to zoom, there is little control of how much you want to zoom in - it just goes all the way in.

had yesterday the possiblity to check with an iphone/safari:
there is still some strange behaviour. the map is zooming when you just tap and hold with only one finger. also the limit isn't considered... the map furthermore disappears.

**Comment by rand256** [comment]
Well, I probably can't help with that as I don't have apple phones.

**Comment by bensweet86** [comment]
I have been able to replicate and *finally* debug my iPhone in Windows..  Issue covered in PR [https://github.com/rand256/valetudo/pull/383](https://github.com/rand256/valetudo/pull/383).  Reproducable if both fingers are lifted from a 2 finger pinch zoom event and captured within a single event in Safari / IOS.  Original code only removed one out of two touch events so continued to see one finger as being an active touch when both had been lifted.
