### ISSUE TITLE
Feature Request: Set alternate end location after cleaning process

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#93]
It would be nice to define an alternate end location (e.g. already saved 'GO TO' location) than the dock (e.g. next to the trash bin) after the cleaning process.

**Comment by rimrul** [comment]
This would require a command queue, like #85 and #16

**Comment by v-a-d-e-r** [comment]
Ah, ok. I thought there is a feedback from the robot when it is finished with cleaning. So we could use that information to send the command 'GO TO'.

**Comment by rand256** [comment]
Yeah, and until that feedback arrives you should store that 'GO TO' command somewhere. In a command queue, for example.

**Comment by v-a-d-e-r** [comment]
Why store that 'GO TO' command in a queue? Isn't there no 'main loop'? I would check in that loop if the 'task finished' command comes from the robot and check then if there is an alternate end location given. I see no need of a 'GO TO command' storage!?

**Comment by rimrul** [comment]
All commands (cleanup, goto, etc.) are async. There is no main loop and nothing currently waits for the end of anything. Without storing that information your robot would just exclaim "starting cleanup" and then go to your end point, without cleaning anything.

**Comment by v-a-d-e-r** [comment]
Ok, thanks for clearing this. ;-)
