### ISSUE TITLE
"no map data" and "Status: Connecting..."

### ISSUE THREAD

**Issue by Hacki1111** [rand256/valetudo#96]
On my Gen2 everything works fine with valetudo but the map isn´t working. I tried different versions of the firmware and valetudo and done many factory resets with complete new installations but I can´t solve this problem.
The rc.local and hosts file are correct.
In the filesystem of the robot the files were created correct so the problem must be something with the connection in den webinterface. The screenshot shows that the status in den corner keeps saying "Connecting...". But on the mainpage all infos are showing up and the controls are working fine too. A reboot doesn´t solve the problem.
With the original firmware everything works with the xiaomi app. 
![Bildschirmfoto 2020-01-29 um 14 26 12](https://user-images.githubusercontent.com/33983958/73362817-d2b0df80-42a7-11ea-8ecb-678056b6d99a.png)

EDIT!: It was es problem with my ssid, it works when I rename it. Maybe it can be fixed in a later version.

**Comment by pidator** [comment]
> EDIT!: It was es problem with my ssid, it works when I rename it. Maybe it can be fixed in a later version.

So what did your SSID looked like? Do you use some special charater that cause the problem?
If all the other views and controlsbuttons works, this sounds suspicious to me ;-)

**Comment by Hacki1111** [comment]
Yes, there must be a problem with special characters. The ssid contains a " \ " and a " / ". Try it! ;)
The Wifi led is now permanent on, before I renamed the network it flashed in short intervals. There must be a intern connection problem with these ssids. I can reproduce it by changing the ssid.

**Comment by pidator** [comment]
ok, thanks for clarification.
Perhaps this is import for @rand256, I don't know if the wifi-ssid-handling is a part of the roborock blackbox or part of valetudo code.

**Comment by rand256** [comment]
> The Wifi led is now permanent on, before I renamed the network it flashed in short intervals. There must be a intern connection problem with these ssids.

As far as I understand, if you have blinking wifi led on the device it means it's just not connected to Wi-Fi network. And if it's not connected then you shouldn't see its web interface at all, not only map. Unless you'd yourself connected to device's own access point. But as you didn't mention that so probably that's not the case.

**Comment by Hacki1111** [comment]
It was connected to the network, the router showed it as connected device and i was able to use the webinterface and all of the functions except the map.
I know that it is unlikely that the wifi led is blinking when everything works but you should be able to reproduce it easily.

**Comment by rand256** [comment]
It is either fully connected to the wifi or not connected at all. There's no position in between.
