### ISSUE TITLE
Loss of maps when saved Gen1 Valetudo Re

### ISSUE THREAD

**Issue by jackkitley** [rand256/valetudo#97]
The map saving functionality on the gen 1 works correctly initally but on a new clean and some other instances it creates a new map and discards the one that was saved. This causes an issue when cleaning zones as the vacuum does not know where the zone is in undiscovered territory.

**How to Reproduce**

**Expected behavior**

**Screenshots**

**Vacuum Model:** Gen1

**Valetudo Version:** 0.8.2

**Comment by pidator** [comment]
Map saving functionality on Gen1? Gen1 doesn't support persistend data, therefore you can't "save" a map like on a Gen2 device: Everytime you start a new full clean up, the map will be build again! You could prevent this behaviour with using only the cleaning of zones feature: create a full map with a complete run of cleaning and then create different zones and use only the zoned cleanup. This is the only way I know the Gen1 "saves" the map.

**Comment by rand256** [comment]
@pidator is correct, Gen1 devices can't have fully "persistent" maps, on every full cleaning the map will be wiped out. It's nothing to be done with that, use zoned cleaning instead. Save/restore feature is made only for restoring accidentally reset or broken maps, not to keep maps intact on Gen1 vacuums as that can't be done this way.
